<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class AllScenariosSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('scenarios')->delete();
        
        $scenarios = $this->getAllScenarios();

        foreach ($scenarios as $scenario) {
            $scenario['uuid'] = (string) Str::uuid();
            $scenario['is_active'] = true;
            $scenario['version'] = 1;
            DB::table('scenarios')->insert($scenario);
        }

        echo "Total: " . count($scenarios) . " scenarios\n";
    }

    private function getAllScenarios(): array
    {
        return [
            // ============ GENERAL EASY (15) ============
            ['title' => 'The Unlocked Workstation', 'description' => 'Learn why you must lock your screen', 'category' => 'physical_security', 'user_type' => 'general', 'level' => 'easy', 'stage' => 1, 'difficulty' => 'beginner', 'estimated_minutes' => 3, 'content' => json_encode(['scenario' => 'Sarah leaves her desk without locking her computer. A visitor sees confidential salary data on the screen and takes a photo.', 'question' => 'What should Sarah have done before leaving her desk?', 'options' => [['text' => 'Left the computer open - she was coming back soon', 'correct' => false], ['text' => 'Locked the screen by pressing Windows + L', 'correct' => true], ['text' => 'Turned off the monitor only', 'correct' => false], ['text' => 'Asked a colleague to watch her desk', 'correct' => false]], 'explanation' => 'Locking your screen takes one second but prevents unauthorized access to sensitive data.'])],

            ['title' => 'The Sticky Note Password', 'description': 'Why you should never write passwords on sticky notes', 'category' => 'password', 'user_type' => 'general', 'level' => 'easy', 'stage' => 1, 'difficulty' => 'beginner', 'estimated_minutes' => 3, 'content' => json_encode(['scenario' => 'Ahmed writes his admin password on a sticky note on his monitor. A client sees it and later uses it to access internal systems.', 'question' => 'What was Ahmed\'s mistake?', 'options' => [['text' => 'He used too many systems', 'correct' => false], ['text' => 'He wrote his password on a visible sticky note', 'correct' => true], ['text' => 'He worked in IT', 'correct' => false], ['text' => 'He had a visitor', 'correct' => false]], 'explanation' => 'Passwords should never be written on visible notes. Use a password manager instead.'])],

            ['title' => 'The Shared Password', 'description' => 'Why sharing credentials destroys accountability', 'category' => 'access_control', 'user_type' => 'general', 'level' => 'easy', 'stage' => 1, 'difficulty' => 'beginner', 'estimated_minutes' => 3, 'content' => json_encode(['scenario' => 'A supervisor gives his login to a new intern instead of requesting proper access from IT.', 'question' => 'What should the supervisor have done?', 'options' => [['text' => 'Shared his password to save time', 'correct' => false], ['text' => 'Requested separate access for the intern from IT', 'correct' => true], ['text' => 'Given written credentials', 'correct' => false], ['text' => 'Postponed the work', 'correct' => false]], 'explanation' => 'Each employee must have their own account for accountability and security tracking.'])],

            ['title' => 'The Unlocked Phone', 'description' => 'Why your phone must always have a lock screen', 'category' => 'physical_security', 'user_type' => 'general', 'level' => 'easy', 'stage' => 1, 'difficulty' => 'beginner', 'estimated_minutes' => 3, 'content' => json_encode(['scenario' => 'Fatima leaves her phone without a lock screen. Another employee reads confidential messages about upcoming layoffs.', 'question' => 'What should Fatima have enabled on her phone?', 'options' => [['text' => 'No lock - it\'s more convenient', 'correct' => false], ['text' => 'Fingerprint or PIN lock', 'correct' => true], ['text' => 'Lock only during meetings', 'correct' => false], ['text' => 'Hide the phone in a drawer', 'correct' => false]], 'explanation' => 'Phones with work data must always have a lock screen.'])],

            ['title' => 'The Public WiFi Trap', 'description' => 'How free WiFi exposed confidential work', 'category' => 'network_security', 'user_type' => 'general', 'level' => 'easy', 'stage' => 1, 'difficulty' => 'beginner', 'estimated_minutes' => 3, 'content' => json_encode(['scenario' => 'Omar connects to free airport WiFi to check work emails. A hacker runs a fake network and intercepts his data.', 'question' => 'What should Omar have done?', 'options' => [['text' => 'Used the free WiFi - it\'s convenient', 'correct' => false], ['text' => 'Used a VPN before connecting', 'correct' => true], ['text' => 'Connected quickly without thinking', 'correct' => false], ['text' => 'Used the airport computer', 'correct' => false]], 'explanation' => 'Always use a VPN for work data on public networks.'])],

            ['title' => 'The Ignored Updates', 'description' => 'Why security updates matter', 'category' => 'updates', 'user_type' => 'general', 'level' => 'easy', 'stage' => 1, 'difficulty' => 'beginner', 'estimated_minutes' => 3, 'content' => json_encode(['scenario' => 'Khalid postpones critical security updates for months. A known vulnerability is exploited.', 'question' => 'What should Khalid have done?', 'options' => [['text' => 'Delayed updates', 'correct' => false], ['text' => 'Installed updates immediately', 'correct' => true], ['text' => 'Ignored them', 'correct' => false], ['text' => 'Disabled notifications', 'correct' => false]], 'explanation' => 'Security updates patch known vulnerabilities. Delay leaves you exposed.'])],

            ['title' => 'The Work Email for Shopping', 'description' => 'Risks of using work email for personal registrations', 'category' => 'email_security', 'user_type' => 'general', 'level' => 'easy', 'stage' => 1, 'difficulty' => 'beginner', 'estimated_minutes' => 3, 'content' => json_encode(['scenario' => 'Nora registers on shopping sites with her work email. The sites are breached and her work email is leaked.', 'question' => 'Which email should she have used?', 'options' => [['text' => 'Work email - it\'s convenient', 'correct' => false], ['text' => 'Personal email - keep work separate', 'correct' => true], ['text' => 'Work email for trusted sites', 'correct' => false], ['text' => 'Any email works', 'correct' => false]], 'explanation' => 'Registering on untrusted sites with work email exposes it to data leaks.'])],

            ['title' => 'The Suspicious Ads', 'description' => 'Dangers of clicking fake download ads', 'category' => 'malware', 'user_type' => 'general', 'level' => 'easy', 'stage' => 1, 'difficulty' => 'beginner', 'estimated_minutes' => 3, 'content' => json_encode(['scenario' => 'Rami clicks a sponsored ad for a free PDF converter. The software installs ransomware.', 'question' => 'What should Rami have done?', 'options' => [['text' => 'Clicked the first ad', 'correct' => false], ['text' => 'Downloaded from official website only', 'correct' => true], ['text' => 'Clicked multiple ads', 'correct' => false], ['text' => 'Used any site', 'correct' => false]], 'explanation' => 'Sponsored ads often lead to fake sites hosting ransomware.'])],

            ['title' => 'The Browser Warnings', 'description' => 'Why you should never bypass security alerts', 'category' => 'web_security', 'user_type' => 'general', 'level' => 'easy', 'stage' => 1, 'difficulty' => 'beginner', 'estimated_minutes' => 3, 'content' => json_encode(['scenario' => 'Sara ignores a browser warning and proceeds to an unsafe site. Her credentials are stolen.', 'question' => 'What should Sara have done?', 'options' => [['text' => 'Clicked "Proceed anyway"', 'correct' => false], ['text' => 'Closed the page immediately', 'correct' => true], ['text' => 'Continued carefully', 'correct' => false], ['text' => 'Added exception', 'correct' => false]], 'explanation' => 'Browser security warnings protect you - never bypass them.'])],

            ['title' => 'The Forgot to Log Out', 'description' => 'Risks of leaving accounts open on shared computers', 'category' => 'access_control', 'user_type' => 'general', 'level' => 'easy', 'stage' => 1, 'difficulty' => 'beginner', 'estimated_minutes' => 3, 'content' => json_encode(['scenario' => 'Omar uses a shared computer and forgets to log out. The next user accesses his email.', 'question' => 'What should Omar have done?', 'options' => [['text' => 'Closed the browser', 'correct' => false], ['text' => 'Logged out and cleared cookies', 'correct' => true], ['text' => 'Just walked away', 'correct' => false], ['text' => 'Minimized the window', 'correct' => false]], 'explanation' => 'Always log out and clear browsing data on shared computers.'])],

            ['title' => 'The Notes App Passwords', 'description' => 'Why notes apps are not safe for passwords', 'category' => 'password', 'user_type' => 'general', 'level' => 'easy', 'stage' => 1, 'difficulty' => 'beginner', 'estimated_minutes' => 3, 'content' => json_encode(['scenario' => 'Nadia stores all passwords in her phone\'s Notes app. Her phone is stolen and all accounts are compromised.', 'question' => 'Where should she have stored passwords?', 'options' => [['text' => 'Notes app', 'correct' => false], ['text' => 'Password manager', 'correct' => true], ['text' => 'Email to herself', 'correct' => false], ['text' => 'Write in notebook', 'correct' => false]], 'explanation' => 'Notes apps are not encrypted. Use a password manager.'])],

            ['title' => 'The Skipped 2FA', 'description' => 'Why two-factor authentication is essential', 'category' => 'account_security', 'user_type' => 'general', 'level' => 'easy', 'stage' => 1, 'difficulty' => 'beginner', 'estimated_minutes' => 3, 'content' => json_encode(['scenario' => 'Rami skips enabling 2FA. His password leaks and hackers access his account instantly.', 'question' => 'What should Rami have done?', 'options' => [['text' => 'Skipped 2FA', 'correct' => false], ['text' => 'Enabled 2FA immediately', 'correct' => true], ['text' => 'Enabled only for banking', 'correct' => false], ['text' => 'Enabled later', 'correct' => false]], 'explanation' => '2FA adds a critical extra layer of security.'])],

            ['title' => 'The Printed Documents', 'description' => 'Risks of forgetting sensitive documents in printer', 'category' => 'physical_security', 'user_type' => 'general', 'level' => 'easy', 'stage' => 1, 'difficulty' => 'beginner', 'estimated_minutes' => 3, 'content' => json_encode(['scenario' => 'Fatima prints a confidential HR document and forgets it in the printer. Others see it.', 'question' => 'What should she have done?', 'options' => [['text' => 'Picked it up later', 'correct' => false], ['text' => 'Collected it immediately after printing', 'correct' => true], ['text' => 'Asked someone to bring it', 'correct' => false], ['text' => 'Left it for tomorrow', 'correct' => false]], 'explanation' => 'Confidential documents must be collected immediately from shared printers.'])],

            ['title' => 'The Unknown LinkedIn', 'description' => 'How fake profiles collect company intelligence', 'category' => 'social_engineering', 'user_type' => 'general', 'level' => 'easy', 'stage' => 1, 'difficulty' => 'beginner', 'estimated_minutes' => 3, 'content' => json_encode(['scenario' => 'Mohammed accepts a LinkedIn request from a stranger who later asks about company structure.', 'question' => 'What should he have done?', 'options' => [['text' => 'Accepted - more connections are good', 'correct' => false], ['text' => 'Ignored or verified identity first', 'correct' => true], ['text' => 'Accepted and shared info', 'correct' => false], ['text' => 'Accepted if profile looks nice', 'correct' => false]], 'explanation' => 'Fake profiles collect intelligence. Verify before connecting.'])],

            // ============ IT EASY (3 نماذج) ============
            ['title' => 'The Default Credentials', 'description' => 'Forgotten default password exposed the network', 'category' => 'it_security', 'user_type' => 'it_professional', 'level' => 'easy', 'stage' => 1, 'difficulty' => 'beginner', 'estimated_minutes' => 3, 'content' => json_encode(['scenario' => 'Ahmed deploys a firewall but leaves default credentials admin/admin. An attacker finds it and gains access.', 'question' => 'What critical mistake did Ahmed make?', 'options' => [['text' => 'He deployed a new firewall', 'correct' => false], ['text' => 'He left default credentials unchanged', 'correct' => true], ['text' => 'He connected to internet', 'correct' => false], ['text' => 'He forgot updates', 'correct' => false]], 'explanation' => 'Default credentials must be changed immediately after deployment.'])],

            ['title' => 'The Hardcoded API Key', 'description' => 'Developer exposed production credentials in code', 'category' => 'it_security', 'user_type' => 'it_professional', 'level' => 'easy', 'stage' => 1, 'difficulty' => 'beginner', 'estimated_minutes' => 3, 'content' => json_encode(['scenario' => 'Sara hardcodes API keys in source code on GitHub. The repo is compromised and keys are stolen.', 'question' => 'What was Sara\'s mistake?', 'options' => [['text' => 'She used GitHub', 'correct' => false], ['text' => 'She hardcoded credentials in source code', 'correct' => true], ['text' => 'She was developing', 'correct' => false], ['text' => 'She didn\'t use 2FA', 'correct' => false]], 'explanation' => 'Never hardcode credentials. Use environment variables.'])],

            ['title' => 'The Shared Admin Account', 'description' => 'One admin account shared by entire team', 'category' => 'it_security', 'user_type' => 'it_professional', 'level' => 'easy', 'stage' => 1, 'difficulty' => 'beginner', 'estimated_minutes' => 3, 'content' => json_encode(['scenario' => 'The IT team shares one Administrator account. No one knows who made a critical change.', 'question' => 'Why is a shared admin account dangerous?', 'options' => [['text' => 'It makes work slower', 'correct' => false], ['text' => 'It eliminates accountability', 'correct' => true], ['text' => 'It requires too many passwords', 'correct' => false], ['text' => 'It costs more money', 'correct' => false]], 'explanation' => 'Each admin must have a unique account for accountability.'])],

            // ============ SECURITY EXPERT (3 نماذج) ============
            ['title' => 'The SSRF Metadata Attack', 'description' => 'Exploiting SSRF to access cloud metadata', 'category' => 'appsec', 'user_type' => 'security_expert', 'level' => 'easy', 'stage' => 1, 'difficulty' => 'beginner', 'estimated_minutes' => 5, 'content' => json_encode(['scenario' => 'A security expert finds SSRF in a web app. They access cloud metadata and retrieve IAM credentials.', 'question' => 'What vulnerability was exploited?', 'options' => [['text' => 'SQL Injection', 'correct' => false], ['text' => 'SSRF to access cloud metadata', 'correct' => true], ['text' => 'XSS', 'correct' => false], ['text' => 'Buffer overflow', 'correct' => false]], 'explanation' => 'SSRF can access internal services. Block access to metadata endpoints.'])],

            ['title' => 'The BOLA Vulnerability', 'description' => 'Broken Object Level Authorization in APIs', 'category' => 'appsec', 'user_type' => 'security_expert', 'level' => 'easy', 'stage' => 1, 'difficulty' => 'beginner', 'estimated_minutes' => 5, 'content' => json_encode(['scenario' => 'A researcher changes user ID in API URL and accesses other users\' data.', 'question' => 'What vulnerability is this?', 'options' => [['text' => 'SQL Injection', 'correct' => false], ['text' => 'Broken Object Level Authorization', 'correct' => true], ['text' => 'XSS', 'correct' => false], ['text' => 'CSRF', 'correct' => false]], 'explanation' => 'APIs must verify user permission for each object.'])],

            ['title' => 'The NoSQL Injection', 'description' => 'Bypassing auth through NoSQL injection', 'category' => 'appsec', 'user_type' => 'security_expert', 'level' => 'easy', 'stage' => 1, 'difficulty' => 'beginner', 'estimated_minutes' => 5, 'content' => json_encode(['scenario' => 'A researcher submits JSON payload that bypasses MongoDB authentication.', 'question' => 'What type of injection was exploited?', 'options' => [['text' => 'SQL Injection', 'correct' => false], ['text' => 'NoSQL Injection', 'correct' => true], ['text' => 'Command Injection', 'correct' => false], ['text' => 'LDAP Injection', 'correct' => false]], 'explanation' => 'Sanitize all inputs before using in NoSQL queries.'])],
        ];
    }
}