<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CyberTasksPhase8Seeder extends Seeder
{
    public function run(): void
    {
        $tasks = [
            // ==================== NETWORK DEFENSE ====================
            [
                'reference_code' => 'NET-DEF-031',
                'section' => 'network_defense',
                'title' => 'Deep Packet Inspection (DPI) Deployment',
                'description' => 'Deploy DPI for advanced traffic analysis.',
                'overview' => 'DPI inspects packet contents for threats. Deploy it.',
                'objectives' => json_encode([
                    'Understand DPI',
                    'Deploy nDPI or Suricata',
                    'Configure inspection rules',
                    'Analyze results',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Install nDPI on Linux.',
                    'Configure interface to monitor.',
                    'Set up application detection.',
                    'Analyze encrypted vs plain traffic.',
                    'Set up alerts.',
                    'Test with simulated traffic.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'nDPI - https://github.com/ntop/nDPI',
                    'Suricata - https://suricata.io',
                    'Wireshark',
                ]),
                'resources' => json_encode([
                    'nDPI Documentation',
                    'DPI Best Practices',
                ]),
                'deliverables' => json_encode([
                    'DPI setup',
                    'Detection results',
                    'Alerts',
                    'Documentation',
                ]),
                'hints' => 'DPI struggles with encrypted traffic. Plan accordingly.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'NET-DEF-032',
                'section' => 'network_defense',
                'title' => 'Wi-Fi 6 Security Features',
                'description' => 'Configure Wi-Fi 6 security features (WPA3, OWE).',
                'overview' => 'Wi-Fi 6 brings new security. Configure it.',
                'objectives' => json_encode([
                    'Understand Wi-Fi 6 security',
                    'Set up WPA3-Enterprise',
                    'Configure OWE',
                    'Test with clients',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up Wi-Fi 6 AP.',
                    'Configure WPA3-Enterprise.',
                    'Set up OWE for open networks.',
                    'Test with modern clients.',
                    'Test backward compatibility.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'hostapd',
                    'Wi-Fi 6 AP',
                    'Wireshark',
                ]),
                'resources' => json_encode([
                    'Wi-Fi 6 Security - Wi-Fi Alliance',
                    'WPA3 Specification',
                ]),
                'deliverables' => json_encode([
                    'AP config',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'WPA3-Enterprise uses 192-bit security.',
                'estimated_time' => '4 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'NET-DEF-033',
                'section' => 'network_defense',
                'title' => '5G Network Security',
                'description' => 'Assess 5G network security features.',
                'overview' => '5G has new security features. Assess them.',
                'objectives' => json_encode([
                    'Understand 5G security',
                    'Assess authentication',
                    'Evaluate network slicing',
                    'Review encryption',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Research 5G security architecture.',
                    'Study 5G-AKA authentication.',
                    'Review network slicing isolation.',
                    'Evaluate encryption (SUCI).',
                    'Document findings.',
                ]),
                'tools_list' => json_encode([
                    'Open5GS - https://open5gs.org',
                    'srsRAN - https://www.srsran.com',
                ]),
                'resources' => json_encode([
                    '3GPP Security Standards',
                    '5G Security - GSMA',
                ]),
                'deliverables' => json_encode([
                    'Assessment report',
                    'Security analysis',
                    'Documentation',
                ]),
                'hints' => '5G security is complex. Focus on core features.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'NET-DEF-034',
                'section' => 'network_defense',
                'title' => 'DNS Security Extensions (DNSSEC)',
                'description' => 'Implement DNSSEC for DNS integrity.',
                'overview' => 'DNSSEC prevents DNS spoofing. Implement it.',
                'objectives' => json_encode([
                    'Understand DNSSEC',
                    'Sign zones',
                    'Configure validation',
                    'Test with dig',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up BIND with DNSSEC.',
                    'Generate keys.',
                    'Sign zones.',
                    'Publish DS records.',
                    'Configure resolvers for validation.',
                    'Test with dig +dnssec.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'BIND - https://www.isc.org/bind',
                    'dnssec-tools',
                    'dig',
                ]),
                'resources' => json_encode([
                    'DNSSEC Guide - ICANN',
                    'BIND DNSSEC',
                ]),
                'deliverables' => json_encode([
                    'Signed zones',
                    'Validation config',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'Key rotation is critical for DNSSEC.',
                'estimated_time' => '5 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'NET-DEF-035',
                'section' => 'network_defense',
                'title' => 'SDN Security (OpenFlow)',
                'description' => 'Secure Software-Defined Networking.',
                'overview' => 'SDN centralizes control. Secure the controller.',
                'objectives' => json_encode([
                    'Understand SDN',
                    'Set up ONOS or ODL',
                    'Secure controller',
                    'Configure flow rules',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up Mininet with controller.',
                    'Configure TLS between switch and controller.',
                    'Set up RBAC on controller.',
                    'Write flow rules.',
                    'Test with simulated attack.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Mininet - http://mininet.org',
                    'ONOS - https://onosproject.org',
                    'OpenDaylight',
                ]),
                'resources' => json_encode([
                    'SDN Security - ONF',
                    'OpenFlow Security',
                ]),
                'deliverables' => json_encode([
                    'SDN setup',
                    'Secure config',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'SDN controller is a single point of failure. Harden it.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== DFIR ====================
            [
                'reference_code' => 'DFIR-031',
                'section' => 'dfir',
                'title' => 'Cobalt Strike Beacon Analysis',
                'description' => 'Analyze Cobalt Strike beacon traffic.',
                'overview' => 'Cobalt Strike is common in attacks. Learn to detect it.',
                'objectives' => json_encode([
                    'Understand CS beacon',
                    'Analyze network traffic',
                    'Detect beacon patterns',
                    'Extract config',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Get sample CS PCAP.',
                    'Analyze with Wireshark.',
                    'Identify beaconing patterns.',
                    'Extract C2 profile.',
                    'Use CS decode tools.',
                    'Document IOCs.',
                ]),
                'tools_list' => json_encode([
                    'Wireshark',
                    'CobaltStrikeParser - https://github.com/Sentinel-One/CobaltStrikeParser',
                    'RITA - https://github.com/activecm/rita',
                ]),
                'resources' => json_encode([
                    'Cobalt Strike Detection',
                    'SANS CS Analysis',
                ]),
                'deliverables' => json_encode([
                    'Beacon analysis',
                    'C2 profile',
                    'IOCs',
                    'Report',
                ]),
                'hints' => 'Beaconing is often periodic. Look for patterns.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DFIR-032',
                'section' => 'dfir',
                'title' => 'WMI Persistence Investigation',
                'description' => 'Investigate WMI persistence mechanisms.',
                'overview' => 'WMI is a stealthy persistence. Learn to detect it.',
                'objectives' => json_encode([
                    'Understand WMI persistence',
                    'Detect WMI subscriptions',
                    'Analyze repository',
                    'Remove persistence',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up test system.',
                    'Create WMI persistence.',
                    'Detect with Autoruns.',
                    'Analyze WMI repository.',
                    'Use WMI Explorer.',
                    'Remove persistence.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Autoruns - https://docs.microsoft.com/sysinternals',
                    'WMI Explorer - https://github.com/vinaypamnani/wmie2',
                    'PowerShell',
                ]),
                'resources' => json_encode([
                    'WMI Persistence - SANS',
                    'WMI Forensics',
                ]),
                'deliverables' => json_encode([
                    'Detection methods',
                    'Analysis',
                    'Removal process',
                    'Documentation',
                ]),
                'hints' => 'Autoruns shows WMI persistence clearly.',
                'estimated_time' => '4 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DFIR-033',
                'section' => 'dfir',
                'title' => 'Log Correlation Across Sources',
                'description' => 'Correlate logs from multiple sources.',
                'overview' => 'Attacks span sources. Correlate for full picture.',
                'objectives' => json_encode([
                    'Understand log correlation',
                    'Set up SIEM',
                    'Create correlation rules',
                    'Test with attack',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up ELK or Splunk.',
                    'Ingest: Windows, Linux, firewall logs.',
                    'Create correlation rules.',
                    'Simulate attack.',
                    'Verify correlation works.',
                    'Document rules.',
                ]),
                'tools_list' => json_encode([
                    'ELK Stack - https://www.elastic.co',
                    'Splunk Free',
                    'Sigma - https://github.com/SigmaHQ/sigma',
                ]),
                'resources' => json_encode([
                    'Log Correlation - SANS',
                    'Sigma Rules',
                ]),
                'deliverables' => json_encode([
                    'SIEM setup',
                    'Correlation rules',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'Start with simple correlations. Add complexity.',
                'estimated_time' => '7 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DFIR-034',
                'section' => 'dfir',
                'title' => 'Supply Chain Attack Investigation',
                'description' => 'Investigate a supply chain attack.',
                'overview' => 'Supply chain attacks are growing. Learn to investigate.',
                'objectives' => json_encode([
                    'Understand supply chain attacks',
                    'Identify compromised component',
                    'Trace attack origin',
                    'Assess impact',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up test environment.',
                    'Simulate supply chain compromise.',
                    'Detect via monitoring.',
                    'Identify compromised component.',
                    'Trace back to source.',
                    'Assess blast radius.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'SBOM tools',
                    'YARA',
                    'Autopsy',
                ]),
                'resources' => json_encode([
                    'SolarWinds Investigation',
                    'Supply Chain Security - NIST',
                ]),
                'deliverables' => json_encode([
                    'Investigation report',
                    'IOCs',
                    'Impact assessment',
                    'Documentation',
                ]),
                'hints' => 'SBOMs help identify affected components.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DFIR-035',
                'section' => 'dfir',
                'title' => 'Forensic Report Writing',
                'description' => 'Write a professional forensic report.',
                'overview' => 'Reports must be clear and defensible. Learn to write.',
                'objectives' => json_encode([
                    'Understand report structure',
                    'Write executive summary',
                    'Document findings',
                    'Present evidence',
                    'Review',
                ]),
                'instructions' => json_encode([
                    'Review NIST report guidelines.',
                    'Write executive summary.',
                    'Document methodology.',
                    'Present findings with evidence.',
                    'Include recommendations.',
                    'Peer review.',
                    'Finalize.',
                ]),
                'tools_list' => json_encode([
                    'Word / LaTeX',
                    'Report Templates',
                ]),
                'resources' => json_encode([
                    'NIST Forensic Report Guide',
                    'SANS Report Writing',
                ]),
                'deliverables' => json_encode([
                    'Full report',
                    'Executive summary',
                    'Evidence appendix',
                    'Recommendations',
                ]),
                'hints' => 'Write for non-technical audience in executive summary.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== PENTEST ====================
            [
                'reference_code' => 'PT-031',
                'section' => 'pentest',
                'title' => 'Blind SQL Injection',
                'description' => 'Exploit blind SQL injection vulnerabilities.',
                'overview' => 'Blind SQLi is harder but powerful. Learn techniques.',
                'objectives' => json_encode([
                    'Understand blind SQLi',
                    'Boolean-based',
                    'Time-based',
                    'Use sqlmap',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up blind SQLi lab.',
                    'Test boolean-based: 1 AND 1=1.',
                    'Test time-based: 1 AND SLEEP(5).',
                    'Use sqlmap with --technique=B/T.',
                    'Extract data.',
                    'Document payloads.',
                ]),
                'tools_list' => json_encode([
                    'sqlmap - https://sqlmap.org',
                    'Burp Suite',
                ]),
                'resources' => json_encode([
                    'Blind SQLi - PortSwigger',
                    'SQLi Guide',
                ]),
                'deliverables' => json_encode([
                    'Payloads',
                    'Extracted data',
                    'Documentation',
                ]),
                'hints' => 'Time-based is slow but reliable.',
                'estimated_time' => '5 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'PT-032',
                'section' => 'pentest',
                'title' => 'XXE Injection Attacks',
                'description' => 'Exploit XML External Entity vulnerabilities.',
                'overview' => 'XXE can lead to file disclosure and SSRF. Learn it.',
                'objectives' => json_encode([
                    'Understand XXE',
                    'Test for XXE',
                    'Extract files',
                    'Perform SSRF',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up XXE lab.',
                    'Test with basic payload.',
                    'Extract /etc/passwd.',
                    'Test blind XXE with OOB.',
                    'Chain with SSRF.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Burp Suite',
                    'XXEinjector - https://github.com/enjoiz/XXEinjector',
                ]),
                'resources' => json_encode([
                    'XXE - PortSwigger',
                    'XXE Cheat Sheet - OWASP',
                ]),
                'deliverables' => json_encode([
                    'Payloads',
                    'Extracted files',
                    'Report',
                ]),
                'hints' => 'Blind XXE needs OOB channels.',
                'estimated_time' => '4 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'PT-033',
                'section' => 'pentest',
                'title' => 'NoSQL Injection',
                'description' => 'Exploit NoSQL injection vulnerabilities.',
                'overview' => 'NoSQL databases have injection too. Learn it.',
                'objectives' => json_encode([
                    'Understand NoSQL injection',
                    'Test MongoDB injection',
                    'Bypass authentication',
                    'Extract data',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up Node.js + MongoDB app.',
                    'Test basic injection: {$ne: null}.',
                    'Bypass auth.',
                    'Test $where injection.',
                    'Extract data.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Burp Suite',
                    'NoSQLMap - https://github.com/codingo/NoSQLMap',
                ]),
                'resources' => json_encode([
                    'NoSQL Injection - OWASP',
                    'NoSQL Injection Guide',
                ]),
                'deliverables' => json_encode([
                    'Payloads',
                    'Exploit proof',
                    'Report',
                ]),
                'hints' => 'NoSQL injection often uses operators like $ne, $gt.',
                'estimated_time' => '4 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'PT-034',
                'section' => 'pentest',
                'title' => 'HTTP Request Smuggling',
                'description' => 'Exploit HTTP request smuggling vulnerabilities.',
                'overview' => 'Smuggling bypasses security controls. Learn it.',
                'objectives' => json_encode([
                    'Understand smuggling',
                    'Test CL.TE',
                    'Test TE.CL',
                    'Exploit for cache poisoning',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up lab with frontend/backend.',
                    'Test CL.TE with Burp.',
                    'Test TE.CL.',
                    'Craft smuggling payload.',
                    'Verify impact.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Burp Suite',
                    'HTTP Request Smuggler - Burp Extension',
                ]),
                'resources' => json_encode([
                    'Request Smuggling - PortSwigger',
                    'HTTP Desync Attacks - James Kettle',
                ]),
                'deliverables' => json_encode([
                    'Payloads',
                    'Exploit proof',
                    'Report',
                ]),
                'hints' => 'HTTP/2 makes smuggling harder but not impossible.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'PT-035',
                'section' => 'pentest',
                'title' => 'Container Registry Attacks',
                'description' => 'Attack container registries.',
                'overview' => 'Registries store images. Attacks can poison them.',
                'objectives' => json_encode([
                    'Understand registry security',
                    'Enumerate images',
                    'Test for vulnerabilities',
                    'Attempt image tampering',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up Docker registry.',
                    'Enumerate images.',
                    'Test image vulnerabilities.',
                    'Attempt push without auth.',
                    'Tamper with image.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Trivy - https://github.com/aquasecurity/trivy',
                    'Docker',
                    'Crane - https://github.com/google/go-containerregistry',
                ]),
                'resources' => json_encode([
                    'Container Registry Security',
                    'SANS Container Security',
                ]),
                'deliverables' => json_encode([
                    'Enumeration results',
                    'Vulnerabilities',
                    'Report',
                ]),
                'hints' => 'Always use authentication for registries.',
                'estimated_time' => '5 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== DEVSECOPS ====================
            [
                'reference_code' => 'DEVSEC-031',
                'section' => 'devsecops',
                'title' => 'Threat Modeling Automation',
                'description' => 'Automate threat modeling in development.',
                'overview' => 'Manual threat modeling does not scale. Automate.',
                'objectives' => json_encode([
                    'Understand automated TM',
                    'Set up pytm',
                    'Write models as code',
                    'Integrate into CI/CD',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Install pytm.',
                    'Write threat model in Python.',
                    'Define elements, boundaries.',
                    'Generate report.',
                    'Integrate into PR process.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'pytm - https://github.com/izar/pytm',
                    'Threatspec - https://threatspec.org',
                ]),
                'resources' => json_encode([
                    'Threat Modeling as Code',
                    'pytm Documentation',
                ]),
                'deliverables' => json_encode([
                    'Threat model code',
                    'Generated report',
                    'CI/CD integration',
                    'Documentation',
                ]),
                'hints' => 'Start simple. Threat modeling as code is emerging.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DEVSEC-032',
                'section' => 'devsecops',
                'title' => 'Container Image Signing with Notary',
                'description' => 'Sign container images with Docker Notary.',
                'overview' => 'Signed images ensure integrity. Sign them.',
                'objectives' => json_encode([
                    'Understand image signing',
                    'Set up Notary',
                    'Sign images',
                    'Verify signatures',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Install Docker Notary.',
                    'Set up Notary server.',
                    'Generate keys.',
                    'Sign image: notary sign.',
                    'Verify signature.',
                    'Configure K8s to verify.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Notary - https://github.com/theupdateframework/notary',
                    'Cosign - https://github.com/sigstore/cosign',
                    'Docker Content Trust',
                ]),
                'resources' => json_encode([
                    'Notary Documentation',
                    'Image Signing Guide',
                ]),
                'deliverables' => json_encode([
                    'Signed images',
                    'Verification',
                    'K8s policy',
                    'Documentation',
                ]),
                'hints' => 'Cosign is the modern alternative to Notary.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DEVSEC-033',
                'section' => 'devsecops',
                'title' => 'Secure Feature Flag Management',
                'description' => 'Implement secure feature flags.',
                'overview' => 'Feature flags control production. Secure them.',
                'objectives' => json_encode([
                    'Understand feature flags',
                    'Set up secure platform',
                    'Configure access controls',
                    'Audit changes',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up Unleash or LaunchDarkly.',
                    'Integrate with app.',
                    'Configure RBAC.',
                    'Enable audit logging.',
                    'Test flag changes.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Unleash - https://www.getunleash.io',
                    'LaunchDarkly',
                    'Flagsmith',
                ]),
                'resources' => json_encode([
                    'Feature Flag Best Practices',
                    'Unleash Documentation',
                ]),
                'deliverables' => json_encode([
                    'Flag setup',
                    'RBAC config',
                    'Audit logs',
                    'Documentation',
                ]),
                'hints' => 'Audit every flag change.',
                'estimated_time' => '4 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DEVSEC-034',
                'section' => 'devsecops',
                'title' => 'API Fuzzing',
                'description' => 'Fuzz APIs to find vulnerabilities.',
                'overview' => 'Fuzzing finds bugs automation misses. Fuzz APIs.',
                'objectives' => json_encode([
                    'Understand API fuzzing',
                    'Set up RESTler',
                    'Generate tests',
                    'Analyze results',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Install RESTler.',
                    'Generate from OpenAPI spec.',
                    'Run fuzzing.',
                    'Analyze crashes/errors.',
                    'Document findings.',
                ]),
                'tools_list' => json_encode([
                    'RESTler - https://github.com/microsoft/restler-fuzzer',
                    'Burp Suite',
                ]),
                'resources' => json_encode([
                    'RESTler Documentation',
                    'API Fuzzing Guide',
                ]),
                'deliverables' => json_encode([
                    'Fuzzing setup',
                    'Results',
                    'Report',
                ]),
                'hints' => 'Fuzzing finds crashes, not logic flaws.',
                'estimated_time' => '5 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DEVSEC-035',
                'section' => 'devsecops',
                'title' => 'Infrastructure Drift Detection',
                'description' => 'Detect infrastructure drift from desired state.',
                'overview' => 'Drift creates security gaps. Detect it.',
                'objectives' => json_encode([
                    'Understand drift detection',
                    'Set up drift tool',
                    'Configure baselines',
                    'Alert on drift',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up Terraform with state.',
                    'Configure drift detection.',
                    'Run detection.',
                    'Alert on changes.',
                    'Remediate drift.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Terraform - https://www.terraform.io',
                    'Driftctl - https://driftctl.com',
                    'CloudQuery',
                ]),
                'resources' => json_encode([
                    'Drift Detection Guide',
                    'Terraform Best Practices',
                ]),
                'deliverables' => json_encode([
                    'Drift setup',
                    'Detections',
                    'Remediation',
                    'Documentation',
                ]),
                'hints' => 'Drift is inevitable. Detect and remediate quickly.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== GRC ====================
            [
                'reference_code' => 'GRC-031',
                'section' => 'grc',
                'title' => 'Security Program Maturity Assessment',
                'description' => 'Assess security program maturity.',
                'overview' => 'Programs mature over time. Assess them.',
                'objectives' => json_encode([
                    'Understand maturity models',
                    'Assess program',
                    'Identify gaps',
                    'Plan improvements',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Research maturity models (C2M2, CMMI).',
                    'Assess current state.',
                    'Score each domain.',
                    'Identify gaps.',
                    'Create roadmap.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'C2M2 - https://www.energy.gov',
                    'Assessment Templates',
                ]),
                'resources' => json_encode([
                    'C2M2 Model',
                    'Security Program Maturity',
                ]),
                'deliverables' => json_encode([
                    'Assessment',
                    'Gaps',
                    'Roadmap',
                    'Documentation',
                ]),
                'hints' => 'C2M2 is free and comprehensive.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'GRC-032',
                'section' => 'grc',
                'title' => 'Security Awareness for Developers',
                'description' => 'Design developer-focused security training.',
                'overview' => 'Developers need specific training. Design it.',
                'objectives' => json_encode([
                    'Understand developer needs',
                    'Design curriculum',
                    'Focus on secure coding',
                    'Include hands-on labs',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Assess developer security knowledge.',
                    'Design curriculum: OWASP Top 10, secure coding.',
                    'Create hands-on labs.',
                    'Schedule sessions.',
                    'Measure improvement.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'OWASP WebGoat - https://owasp.org/www-project-webgoat',
                    'Secure Code Warrior',
                ]),
                'resources' => json_encode([
                    'OWASP Training',
                    'Secure Coding Guide',
                ]),
                'deliverables' => json_encode([
                    'Curriculum',
                    'Labs',
                    'Metrics',
                    'Documentation',
                ]),
                'hints' => 'Hands-on labs are more effective than slides.',
                'estimated_time' => '7 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'GRC-033',
                'section' => 'grc',
                'title' => 'Merger & Acquisition Security Due Diligence',
                'description' => 'Perform security due diligence for M&A.',
                'overview' => 'M&A introduces security risks. Perform due diligence.',
                'objectives' => json_encode([
                    'Understand M&A security',
                    'Assess target security',
                    'Identify risks',
                    'Plan integration',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Define assessment scope.',
                    'Review security posture.',
                    'Identify incidents, breaches.',
                    'Assess compliance.',
                    'Plan integration.',
                    'Document findings.',
                ]),
                'tools_list' => json_encode([
                    'Due Diligence Checklists',
                    'Assessment Templates',
                ]),
                'resources' => json_encode([
                    'M&A Security - Gartner',
                    'Due Diligence Guide',
                ]),
                'deliverables' => json_encode([
                    'Assessment report',
                    'Risk analysis',
                    'Integration plan',
                    'Documentation',
                ]),
                'hints' => 'Focus on risks that affect deal value.',
                'estimated_time' => '10 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'GRC-034',
                'section' => 'grc',
                'title' => 'Cloud Governance Framework',
                'description' => 'Establish cloud governance.',
                'overview' => 'Cloud needs governance. Establish it.',
                'objectives' => json_encode([
                    'Understand cloud governance',
                    'Define policies',
                    'Set up controls',
                    'Enable monitoring',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Define cloud policies.',
                    'Set up organizational units.',
                    'Configure guardrails (SCP).',
                    'Enable monitoring.',
                    'Review regularly.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'AWS Organizations',
                    'Azure Management Groups',
                    'Cloud Custodian',
                ]),
                'resources' => json_encode([
                    'Cloud Governance - AWS',
                    'Azure Governance',
                ]),
                'deliverables' => json_encode([
                    'Policies',
                    'Guardrails',
                    'Monitoring',
                    'Documentation',
                ]),
                'hints' => 'Guardrails are more effective than manual review.',
                'estimated_time' => '7 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'GRC-035',
                'section' => 'grc',
                'title' => 'Security Awareness Metrics Dashboard',
                'description' => 'Build a dashboard for awareness metrics.',
                'overview' => 'Metrics drive improvement. Build a dashboard.',
                'objectives' => json_encode([
                    'Define metrics',
                    'Collect data',
                    'Build dashboard',
                    'Report to management',
                    'Improve program',
                ]),
                'instructions' => json_encode([
                    'Define awareness KPIs.',
                    'Collect data.',
                    'Build dashboard (Power BI).',
                    'Schedule reports.',
                    'Analyze trends.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Power BI - https://powerbi.microsoft.com',
                    'Tableau',
                    'Excel',
                ]),
                'resources' => json_encode([
                    'Awareness Metrics - SANS',
                    'Security Dashboard Best Practices',
                ]),
                'deliverables' => json_encode([
                    'Dashboard',
                    'Reports',
                    'Analysis',
                    'Documentation',
                ]),
                'hints' => 'Make metrics actionable.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== AUTOMATION ====================
            [
                'reference_code' => 'AUTO-031',
                'section' => 'automation',
                'title' => 'Automated Cloud Security Posture Management',
                'description' => 'Automate CSPM for cloud environments.',
                'overview' => 'Cloud posture changes constantly. Automate it.',
                'objectives' => json_encode([
                    'Understand CSPM',
                    'Set up Prowler',
                    'Schedule scans',
                    'Alert on findings',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Install Prowler.',
                    'Configure AWS credentials.',
                    'Run scans.',
                    'Parse findings.',
                    'Set up alerts.',
                    'Schedule scans.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Prowler - https://github.com/prowler-cloud/prowler',
                    'ScoutSuite',
                    'CloudSploit',
                ]),
                'resources' => json_encode([
                    'CSPM Guide - Gartner',
                    'Prowler Documentation',
                ]),
                'deliverables' => json_encode([
                    'CSPM setup',
                    'Scan results',
                    'Alerts',
                    'Documentation',
                ]),
                'hints' => 'Prowler has hundreds of checks.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'AUTO-032',
                'section' => 'automation',
                'title' => 'Automated User Entity Behavior Analytics',
                'description' => 'Set up automated UEBA.',
                'overview' => 'UEBA detects insider threats. Automate it.',
                'objectives' => json_encode([
                    'Understand UEBA',
                    'Collect user data',
                    'Build baselines',
                    'Detect anomalies',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up Elasticsearch.',
                    'Collect: login, file access.',
                    'Set up ML jobs.',
                    'Configure anomaly detection.',
                    'Alert on deviations.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Elasticsearch ML',
                    'Splunk UBA',
                    'Microsoft Sentinel',
                ]),
                'resources' => json_encode([
                    'UEBA Guide',
                    'Elastic ML Documentation',
                ]),
                'deliverables' => json_encode([
                    'UEBA setup',
                    'Baselines',
                    'Alerts',
                    'Documentation',
                ]),
                'hints' => 'Start with login anomalies.',
                'estimated_time' => '7 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'AUTO-033',
                'section' => 'automation',
                'title' => 'Automated Threat Hunting Queries',
                'description' => 'Build a library of automated hunting queries.',
                'overview' => 'Hunting queries can be reused. Build a library.',
                'objectives' => json_encode([
                    'Understand hunting queries',
                    'Build query library',
                    'Automate execution',
                    'Document results',
                    'Improve queries',
                ]),
                'instructions' => json_encode([
                    'Research Sigma rules.',
                    'Translate to SIEM queries.',
                    'Schedule execution.',
                    'Analyze results.',
                    'Refine queries.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Sigma - https://github.com/SigmaHQ/sigma',
                    'ELK / Splunk',
                ]),
                'resources' => json_encode([
                    'Sigma Rules',
                    'Threat Hunting Queries - SANS',
                ]),
                'deliverables' => json_encode([
                    'Query library',
                    'Automation',
                    'Results',
                    'Documentation',
                ]),
                'hints' => 'Sigma rules are portable across SIEMs.',
                'estimated_time' => '6 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'AUTO-034',
                'section' => 'automation',
                'title' => 'Automated Compliance Reporting',
                'description' => 'Automate compliance reports.',
                'overview' => 'Compliance reports take time. Automate them.',
                'objectives' => json_encode([
                    'Identify reports',
                    'Set up collection',
                    'Generate reports',
                    'Distribute',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'List required reports.',
                    'Identify data sources.',
                    'Write collection scripts.',
                    'Generate PDFs.',
                    'Schedule delivery.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Python (ReportLab)',
                    'Vanta / Drata',
                ]),
                'resources' => json_encode([
                    'Compliance Automation Guide',
                    'Report Generation Best Practices',
                ]),
                'deliverables' => json_encode([
                    'Scripts',
                    'Reports',
                    'Schedule',
                    'Documentation',
                ]),
                'hints' => 'Start with the most frequent report.',
                'estimated_time' => '6 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'AUTO-035',
                'section' => 'automation',
                'title' => 'Automated Incident Response Playbooks',
                'description' => 'Build automated IR playbooks.',
                'overview' => 'Playbooks reduce response time. Automate them.',
                'objectives' => json_encode([
                    'Understand playbooks',
                    'Build automation',
                    'Test playbooks',
                    'Integrate with tools',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Choose platform (Shuffle, n8n).',
                    'Build playbook: phishing response.',
                    'Add steps: enrichment, notification, containment.',
                    'Test with simulated incident.',
                    'Refine based on results.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Shuffle - https://shuffler.io',
                    'n8n - https://n8n.io',
                    'TheHive',
                ]),
                'resources' => json_encode([
                    'IR Playbook Guide - NIST',
                    'Shuffle Documentation',
                ]),
                'deliverables' => json_encode([
                    'Playbooks',
                    'Test results',
                    'Integration',
                    'Documentation',
                ]),
                'hints' => 'Start with the most common incident type.',
                'estimated_time' => '7 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
        ];

        foreach ($tasks as $task) {
            $task['created_at'] = now();
            $task['updated_at'] = now();
            DB::table('cyber_tasks')->updateOrInsert(
                ['reference_code' => $task['reference_code']],
                $task
            );
        }

        echo "Phase 8 - Cyber Tasks created!\n";
        echo "Total: " . count($tasks) . " new tasks\n";
    }
}