<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CyberTasksPhase7Seeder extends Seeder
{
    public function run(): void
    {
        $tasks = [
            // ==================== NETWORK DEFENSE ====================
            [
                'reference_code' => 'NET-DEF-026',
                'section' => 'network_defense',
                'title' => 'Network Function Virtualization (NFV) Security',
                'description' => 'Secure NFV infrastructure and virtual network functions.',
                'overview' => 'NFV replaces hardware appliances with software. Secure it.',
                'objectives' => json_encode([
                    'Understand NFV architecture',
                    'Secure hypervisor',
                    'Isolate VNFs',
                    'Monitor traffic between VNFs',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up NFV lab (OpenStack or KVM).',
                    'Deploy firewall VNF.',
                    'Configure VNF isolation.',
                    'Set up traffic mirroring.',
                    'Monitor inter-VNF traffic.',
                    'Test with simulated attacks.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'OpenStack - https://www.openstack.org',
                    'KVM - https://www.linux-kvm.org',
                    'Open vSwitch - https://www.openvswitch.org',
                ]),
                'resources' => json_encode([
                    'NFV Security - ETSI',
                    'OpenStack Security Guide',
                ]),
                'deliverables' => json_encode([
                    'NFV setup',
                    'Isolation config',
                    'Monitoring data',
                    'Documentation',
                ]),
                'hints' => 'VNFs share hypervisor. Isolation is critical.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'NET-DEF-027',
                'section' => 'network_defense',
                'title' => 'Network Time Protocol (NTP) Security',
                'description' => 'Secure NTP infrastructure to prevent time-based attacks.',
                'overview' => 'NTP attacks can disrupt logging and auth. Secure NTP.',
                'objectives' => json_encode([
                    'Understand NTP attacks',
                    'Set up authenticated NTP',
                    'Monitor NTP traffic',
                    'Detect amplification attacks',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up NTP server (chrony).',
                    'Configure NTS (Network Time Security).',
                    'Restrict NTP queries.',
                    'Monitor for amplification.',
                    'Set up alerts.',
                    'Test with NTP attacks.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Chrony - https://chrony.tuxfamily.org',
                    'NTPsec - https://www.ntpsec.org',
                    'Wireshark',
                ]),
                'resources' => json_encode([
                    'NTP Security - NIST',
                    'NTS Specification',
                ]),
                'deliverables' => json_encode([
                    'NTP setup',
                    'NTS config',
                    'Monitoring',
                    'Documentation',
                ]),
                'hints' => 'NTP amplification is a common DDoS vector.',
                'estimated_time' => '4 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'NET-DEF-028',
                'section' => 'network_defense',
                'title' => 'MACsec Implementation',
                'description' => 'Implement MACsec for Layer 2 encryption.',
                'overview' => 'MACsec encrypts Layer 2 traffic. Implement it.',
                'objectives' => json_encode([
                    'Understand MACsec',
                    'Set up MACsec on switches',
                    'Configure key management',
                    'Test encryption',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up switches with MACsec support.',
                    'Configure MKA (MACsec Key Agreement).',
                    'Test with Wireshark.',
                    'Verify encryption.',
                    'Test failover.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'MACsec-capable switches',
                    'Wireshark',
                    'hostapd (for testing)',
                ]),
                'resources' => json_encode([
                    'MACsec - IEEE 802.1AE',
                    'MACsec Deployment Guide - Cisco',
                ]),
                'deliverables' => json_encode([
                    'MACsec config',
                    'Encryption proof',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'MACsec protects against eavesdropping on LAN.',
                'estimated_time' => '5 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'NET-DEF-029',
                'section' => 'network_defense',
                'title' => 'Container Network Security',
                'description' => 'Secure container networking with policies.',
                'overview' => 'Container networks need policies. Implement them.',
                'objectives' => json_encode([
                    'Understand container networking',
                    'Set up Calico or Cilium',
                    'Configure network policies',
                    'Test isolation',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up Kubernetes with Calico.',
                    'Create default deny policy.',
                    'Allow only required traffic.',
                    'Test with pods.',
                    'Verify isolation.',
                    'Monitor traffic.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Calico - https://www.tigera.io/project-calico',
                    'Cilium - https://cilium.io',
                    'Kubernetes',
                ]),
                'resources' => json_encode([
                    'K8s Network Policies',
                    'Calico Documentation',
                ]),
                'deliverables' => json_encode([
                    'Network policies',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'Default deny is the safest starting point.',
                'estimated_time' => '5 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'NET-DEF-030',
                'section' => 'network_defense',
                'title' => 'SASE Architecture Security',
                'description' => 'Secure a SASE (Secure Access Service Edge) deployment.',
                'overview' => 'SASE combines network and security. Secure it.',
                'objectives' => json_encode([
                    'Understand SASE',
                    'Set up SASE lab',
                    'Configure identity-based access',
                    'Test with remote users',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Research SASE providers (Zscaler, Netskope).',
                    'Set up free tier.',
                    'Configure identity-based policies.',
                    'Test with remote users.',
                    'Verify security controls.',
                    'Document architecture.',
                ]),
                'tools_list' => json_encode([
                    'Zscaler - https://www.zscaler.com',
                    'Netskope - https://www.netskope.com',
                    'Cloudflare Zero Trust - https://www.cloudflare.com',
                ]),
                'resources' => json_encode([
                    'SASE - Gartner',
                    'SASE Best Practices',
                ]),
                'deliverables' => json_encode([
                    'SASE config',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'Cloudflare Zero Trust has a free tier.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== DFIR ====================
            [
                'reference_code' => 'DFIR-026',
                'section' => 'dfir',
                'title' => 'Kubernetes Forensics',
                'description' => 'Perform forensic investigation on Kubernetes.',
                'overview' => 'K8s incidents need specialized forensics.',
                'objectives' => json_encode([
                    'Understand K8s artifacts',
                    'Collect cluster logs',
                    'Analyze pod activity',
                    'Investigate container escapes',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up K8s cluster with sample activity.',
                    'Collect: audit logs, events, pod logs.',
                    'Analyze suspicious pod activity.',
                    'Review RBAC changes.',
                    'Check for privileged pods.',
                    'Investigate escapes.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'kubectl',
                    'Kube-bench - https://github.com/aquasecurity/kube-bench',
                    'Falco - https://falco.org',
                ]),
                'resources' => json_encode([
                    'K8s Forensics Guide',
                    'SANS Container Forensics',
                ]),
                'deliverables' => json_encode([
                    'Log analysis',
                    'Investigation report',
                    'Timeline',
                    'Documentation',
                ]),
                'hints' => 'Audit logs are the goldmine for K8s investigations.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DFIR-027',
                'section' => 'dfir',
                'title' => 'Email Forensics Deep Dive',
                'description' => 'Perform deep forensic analysis on email.',
                'overview' => 'Email forensics reveals BEC and phishing. Go deep.',
                'objectives' => json_encode([
                    'Extract PST/OST',
                    'Analyze message headers',
                    'Extract attachments',
                    'Analyze links',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Get a PST file.',
                    'Extract with libpff.',
                    'Analyze headers.',
                    'Extract attachments.',
                    'Analyze links with URLVoid.',
                    'Reconstruct message flow.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'libpff - https://github.com/libyal/libpff',
                    'Email Header Analyzer',
                    'URLVoid - https://www.urlvoid.com',
                ]),
                'resources' => json_encode([
                    'Email Forensics - SANS',
                    'libpff Documentation',
                ]),
                'deliverables' => json_encode([
                    'Extracted emails',
                    'Header analysis',
                    'IOC list',
                    'Report',
                ]),
                'hints' => 'Headers contain the truth of email origin.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DFIR-028',
                'section' => 'dfir',
                'title' => 'Database Forensics',
                'description' => 'Perform forensic analysis on database systems.',
                'overview' => 'Databases hold critical evidence. Learn forensics.',
                'objectives' => json_encode([
                    'Understand DB artifacts',
                    'Analyze transaction logs',
                    'Recover deleted records',
                    'Detect unauthorized access',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up MySQL/PostgreSQL.',
                    'Generate test activity.',
                    'Analyze binary logs.',
                    'Recover deleted records.',
                    'Review access logs.',
                    'Detect anomalies.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'MySQL Utilities',
                    'pgBadger - https://pgbadger.darold.net',
                    'Autopsy',
                ]),
                'resources' => json_encode([
                    'Database Forensics - SANS',
                    'MySQL Forensic Guide',
                ]),
                'deliverables' => json_encode([
                    'Log analysis',
                    'Recovered records',
                    'Access report',
                    'Documentation',
                ]),
                'hints' => 'Binary logs record every change.',
                'estimated_time' => '5 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DFIR-029',
                'section' => 'dfir',
                'title' => 'IoT Forensics',
                'description' => 'Perform forensic investigation on IoT devices.',
                'overview' => 'IoT devices have unique artifacts. Learn them.',
                'objectives' => json_encode([
                    'Extract firmware',
                    'Analyze file systems',
                    'Extract cloud data',
                    'Correlate with network',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Get sample IoT device (Raspberry Pi).',
                    'Extract SD card.',
                    'Analyze file system.',
                    'Extract firmware.',
                    'Analyze cloud API calls.',
                    'Correlate with network logs.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Binwalk - https://github.com/ReFirmLabs/binwalk',
                    'Autopsy - https://www.autopsy.com',
                    'Wireshark',
                ]),
                'resources' => json_encode([
                    'IoT Forensics Guide',
                    'Practical IoT Hacking (Book)',
                ]),
                'deliverables' => json_encode([
                    'Firmware analysis',
                    'File system analysis',
                    'Cloud correlation',
                    'Report',
                ]),
                'hints' => 'Firmware often contains hardcoded secrets.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DFIR-030',
                'section' => 'dfir',
                'title' => 'Threat Hunting Hypothesis Development',
                'description' => 'Develop and test threat hunting hypotheses.',
                'overview' => 'Threat hunting starts with hypotheses. Learn to develop them.',
                'objectives' => json_encode([
                    'Understand threat hunting',
                    'Develop hypotheses',
                    'Test with data',
                    'Document findings',
                    'Refine process',
                ]),
                'instructions' => json_encode([
                    'Research current threats (MITRE).',
                    'Develop hypothesis: "Attackers use X for Y".',
                    'Identify data sources.',
                    'Query data (SIEM).',
                    'Test hypothesis.',
                    'Document findings.',
                    'Refine.',
                ]),
                'tools_list' => json_encode([
                    'MITRE ATT&CK - https://attack.mitre.org',
                    'Splunk / ELK',
                    'Sigma - https://github.com/SigmaHQ/sigma',
                ]),
                'resources' => json_encode([
                    'Threat Hunting - SANS',
                    'The Threat Hunting Playbook',
                ]),
                'deliverables' => json_encode([
                    'Hypotheses',
                    'Test results',
                    'Findings',
                    'Report',
                ]),
                'hints' => 'Good hypotheses are specific and testable.',
                'estimated_time' => '5 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== PENTEST ====================
            [
                'reference_code' => 'PT-026',
                'section' => 'pentest',
                'title' => 'GraphQL Security Testing',
                'description' => 'Test GraphQL APIs for vulnerabilities.',
                'overview' => 'GraphQL has unique security issues. Test them.',
                'objectives' => json_encode([
                    'Understand GraphQL',
                    'Test introspection',
                    'Test for injection',
                    'Test authorization',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up vulnerable GraphQL (DVGA).',
                    'Test introspection.',
                    'Test for IDOR.',
                    'Test for injection in args.',
                    'Test batching attacks.',
                    'Document vulnerabilities.',
                    'Recommend fixes.',
                ]),
                'tools_list' => json_encode([
                    'InQL - https://github.com/doyensec/inql',
                    'GraphQL Voyager',
                    'Burp Suite',
                ]),
                'resources' => json_encode([
                    'GraphQL Security - OWASP',
                    'GraphQL Cheat Sheet',
                ]),
                'deliverables' => json_encode([
                    'Schema map',
                    'Vulnerabilities',
                    'Exploit proofs',
                    'Report',
                ]),
                'hints' => 'Introspection reveals the schema. Disable in production.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'PT-027',
                'section' => 'pentest',
                'title' => 'JWT Attacks',
                'description' => 'Test JWT implementations for vulnerabilities.',
                'overview' => 'JWT is common but often misimplemented. Test it.',
                'objectives' => json_encode([
                    'Understand JWT',
                    'Test algorithm confusion',
                    'Test none algorithm',
                    'Test weak keys',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Get sample JWT app.',
                    'Decode JWT.',
                    'Test alg=none.',
                    'Test RS256→HS256 confusion.',
                    'Try cracking secret.',
                    'Test kid injection.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'jwt_tool - https://github.com/ticarpi/jwt_tool',
                    'hashcat - https://hashcat.net',
                    'Burp JWT Editor',
                ]),
                'resources' => json_encode([
                    'JWT Security - OWASP',
                    'JWT Attacks - PortSwigger',
                ]),
                'deliverables' => json_encode([
                    'Vulnerabilities found',
                    'Exploit proofs',
                    'Report',
                    'Recommendations',
                ]),
                'hints' => 'Always test alg=none first.',
                'estimated_time' => '4 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'PT-028',
                'section' => 'pentest',
                'title' => 'Race Condition Attacks',
                'description' => 'Exploit race conditions in web applications.',
                'overview' => 'Race conditions are subtle but powerful. Learn to exploit.',
                'objectives' => json_encode([
                    'Understand race conditions',
                    'Identify vulnerable endpoints',
                    'Use Turbo Intruder',
                    'Exploit for profit',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up vulnerable app.',
                    'Identify state-changing endpoints.',
                    'Use Turbo Intruder for parallel requests.',
                    'Exploit coupon, withdrawal.',
                    'Document impact.',
                    'Recommend fixes.',
                ]),
                'tools_list' => json_encode([
                    'Burp Turbo Intruder',
                    'Raceocat',
                    'Custom scripts',
                ]),
                'resources' => json_encode([
                    'Race Conditions - PortSwigger',
                    'Race Condition Research',
                ]),
                'deliverables' => json_encode([
                    'Vulnerable endpoints',
                    'Exploit proof',
                    'Impact analysis',
                    'Report',
                ]),
                'hints' => 'Turbo Intruder sends requests in true parallel.',
                'estimated_time' => '5 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'PT-029',
                'section' => 'pentest',
                'title' => 'Deserialization Attacks',
                'description' => 'Exploit insecure deserialization.',
                'overview' => 'Deserialization can lead to RCE. Learn to exploit.',
                'objectives' => json_encode([
                    'Understand deserialization',
                    'Identify vulnerable endpoints',
                    'Build gadget chains',
                    'Achieve RCE',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up vulnerable app (Java/PHP).',
                    'Identify serialized data.',
                    'Use ysoserial for Java.',
                    'Use phpggc for PHP.',
                    'Build payload.',
                    'Achieve RCE.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'ysoserial - https://github.com/frohoff/ysoserial',
                    'phpggc - https://github.com/ambionics/phpggc',
                    'Burp Suite',
                ]),
                'resources' => json_encode([
                    'Deserialization - OWASP',
                    'Deserialization Attacks - PortSwigger',
                ]),
                'deliverables' => json_encode([
                    'Vulnerable code',
                    'Payload',
                    'RCE proof',
                    'Report',
                ]),
                'hints' => 'Deserialization often leads to RCE.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'PT-030',
                'section' => 'pentest',
                'title' => 'Cloud Metadata Service Attacks',
                'description' => 'Exploit cloud metadata services.',
                'overview' => 'Metadata services can leak credentials. Exploit them.',
                'objectives' => json_encode([
                    'Understand metadata services',
                    'Test SSRF to metadata',
                    'Extract credentials',
                    'Use credentials',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up cloud VM.',
                    'Test metadata endpoint (169.254.169.254).',
                    'Attempt SSRF from web app.',
                    'Extract IAM credentials.',
                    'Use credentials for access.',
                    'Document.',
                    'Recommend IMDSv2.',
                ]),
                'tools_list' => json_encode([
                    'curl',
                    'Burp Suite',
                    'AWS CLI',
                ]),
                'resources' => json_encode([
                    'SSRF to Metadata - Capital One',
                    'AWS IMDSv2',
                ]),
                'deliverables' => json_encode([
                    'SSRF proof',
                    'Extracted creds',
                    'Impact',
                    'Report',
                ]),
                'hints' => 'IMDSv2 prevents most SSRF attacks.',
                'estimated_time' => '5 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== DEVSECOPS ====================
            [
                'reference_code' => 'DEVSEC-026',
                'section' => 'devsecops',
                'title' => 'Security Requirements Engineering',
                'description' => 'Define security requirements for new features.',
                'overview' => 'Security starts with requirements. Define them.',
                'objectives' => json_encode([
                    'Understand security requirements',
                    'Elicit from stakeholders',
                    'Define acceptance criteria',
                    'Integrate into backlog',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Review new feature request.',
                    'Identify security requirements.',
                    'Define: auth, authz, data protection.',
                    'Write as user stories.',
                    'Add to backlog.',
                    'Review with team.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Jira',
                    'Confluence',
                ]),
                'resources' => json_encode([
                    'Security Requirements - OWASP',
                    'BSIMM Framework',
                ]),
                'deliverables' => json_encode([
                    'Requirements',
                    'Acceptance criteria',
                    'Backlog items',
                    'Documentation',
                ]),
                'hints' => 'Make requirements testable.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DEVSEC-027',
                'section' => 'devsecops',
                'title' => 'Supply Chain Security (SLSA)',
                'description' => 'Implement SLSA framework for supply chain security.',
                'overview' => 'Supply chain attacks are growing. Implement SLSA.',
                'objectives' => json_encode([
                    'Understand SLSA levels',
                    'Assess current level',
                    'Implement improvements',
                    'Sign artifacts',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Review SLSA framework.',
                    'Assess current build process.',
                    'Identify target level.',
                    'Implement signed commits.',
                    'Sign build artifacts.',
                    'Enable provenance.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'SLSA - https://slsa.dev',
                    'Sigstore - https://www.sigstore.dev',
                    'in-toto - https://in-toto.io',
                ]),
                'resources' => json_encode([
                    'SLSA Documentation',
                    'Supply Chain Security - Google',
                ]),
                'deliverables' => json_encode([
                    'Assessment',
                    'Implementation',
                    'Provenance',
                    'Documentation',
                ]),
                'hints' => 'Start with SLSA 1. Progress incrementally.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DEVSEC-028',
                'section' => 'devsecops',
                'title' => 'Secrets Detection in Git',
                'description' => 'Detect secrets committed to Git repositories.',
                'overview' => 'Secrets in Git leak. Detect and prevent.',
                'objectives' => json_encode([
                    'Understand secret scanning',
                    'Set up gitleaks',
                    'Scan repositories',
                    'Set up pre-commit hooks',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Install gitleaks.',
                    'Scan test repo.',
                    'Identify secrets.',
                    'Set up pre-commit hook.',
                    'Set up CI scan.',
                    'Rotate exposed secrets.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'gitleaks - https://github.com/gitleaks/gitleaks',
                    'trufflehog - https://github.com/trufflesecurity/trufflehog',
                    'git-secrets - https://github.com/awslabs/git-secrets',
                ]),
                'resources' => json_encode([
                    'Secret Scanning - GitHub',
                    'gitleaks Documentation',
                ]),
                'deliverables' => json_encode([
                    'Scan results',
                    'Pre-commit hook',
                    'CI integration',
                    'Documentation',
                ]),
                'hints' => 'Pre-commit hooks prevent secrets from ever entering Git.',
                'estimated_time' => '4 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DEVSEC-029',
                'section' => 'devsecops',
                'title' => 'WebAssembly (WASM) Security',
                'description' => 'Secure WebAssembly modules.',
                'overview' => 'WASM runs in browsers and servers. Secure it.',
                'objectives' => json_encode([
                    'Understand WASM security',
                    'Analyze WASM modules',
                    'Detect malicious code',
                    'Sandbox execution',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Get WASM module.',
                    'Analyze with wasm-decompile.',
                    'Check imports/exports.',
                    'Test in sandbox.',
                    'Run in browser sandbox.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'wasm-decompile - https://github.com/WebAssembly/wabt',
                    'wasm2wat',
                    'Wasmtime - https://wasmtime.dev',
                ]),
                'resources' => json_encode([
                    'WASM Security Guide',
                    'WebAssembly Specification',
                ]),
                'deliverables' => json_encode([
                    'Analysis',
                    'Sandbox setup',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'WASM is not inherently secure. Sandbox it.',
                'estimated_time' => '5 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DEVSEC-030',
                'section' => 'devsecops',
                'title' => 'API Gateway Security Advanced',
                'description' => 'Advanced API gateway security configuration.',
                'overview' => 'API gateways need advanced security. Configure them.',
                'objectives' => json_encode([
                    'Understand advanced features',
                    'Set up WAF rules',
                    'Configure bot detection',
                    'Set up schema validation',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up Kong or AWS API Gateway.',
                    'Configure WAF rules.',
                    'Set up bot detection.',
                    'Enable schema validation.',
                    'Configure JWT validation.',
                    'Set up rate limiting.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Kong - https://konghq.com',
                    'AWS WAF',
                    'Cloudflare',
                ]),
                'resources' => json_encode([
                    'API Gateway Security - AWS',
                    'Kong Security Guide',
                ]),
                'deliverables' => json_encode([
                    'Gateway config',
                    'WAF rules',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'WAF rules should be tuned to reduce false positives.',
                'estimated_time' => '5 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== GRC ====================
            [
                'reference_code' => 'GRC-026',
                'section' => 'grc',
                'title' => 'Security Architecture Review Process',
                'description' => 'Establish a security architecture review process.',
                'overview' => 'Architecture reviews prevent rework. Establish process.',
                'objectives' => json_encode([
                    'Understand review process',
                    'Define review criteria',
                    'Set up review board',
                    'Define escalation',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Define what needs review.',
                    'Create review checklist.',
                    'Set up review board.',
                    'Define SLA for reviews.',
                    'Track decisions.',
                    'Document process.',
                ]),
                'tools_list' => json_encode([
                    'Confluence',
                    'Jira',
                    'Review Templates',
                ]),
                'resources' => json_encode([
                    'Security Architecture - SABSA',
                    'Architecture Review Best Practices',
                ]),
                'deliverables' => json_encode([
                    'Process document',
                    'Review board',
                    'Templates',
                    'Documentation',
                ]),
                'hints' => 'Keep reviews focused on high-risk changes.',
                'estimated_time' => '6 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'GRC-027',
                'section' => 'grc',
                'title' => 'Security Training Curriculum Design',
                'description' => 'Design a comprehensive security training curriculum.',
                'overview' => 'Training is essential. Design a curriculum.',
                'objectives' => json_encode([
                    'Understand training needs',
                    'Design curriculum',
                    'Create materials',
                    'Plan delivery',
                    'Measure effectiveness',
                ]),
                'instructions' => json_encode([
                    'Assess training needs.',
                    'Design curriculum by role.',
                    'Create materials (slides, videos).',
                    'Plan delivery schedule.',
                    'Set up tracking.',
                    'Measure effectiveness.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'LMS (Moodle)',
                    'Articulate',
                    'Camtasia',
                ]),
                'resources' => json_encode([
                    'Training Design - ATD',
                    'Security Training Best Practices',
                ]),
                'deliverables' => json_encode([
                    'Curriculum',
                    'Materials',
                    'Delivery plan',
                    'Metrics',
                ]),
                'hints' => 'Role-based training is most effective.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'GRC-028',
                'section' => 'grc',
                'title' => 'Security Metrics Maturity Model',
                'description' => 'Assess and improve security metrics maturity.',
                'overview' => 'Metrics mature over time. Assess and improve.',
                'objectives' => json_encode([
                    'Understand maturity model',
                    'Assess current state',
                    'Identify improvements',
                    'Implement changes',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Research maturity models.',
                    'Assess current metrics.',
                    'Identify maturity level.',
                    'Plan improvements.',
                    'Implement.',
                    'Re-assess.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Maturity Models',
                    'Excel',
                ]),
                'resources' => json_encode([
                    'Security Metrics - Andrew Jaquith',
                    'CMMI',
                ]),
                'deliverables' => json_encode([
                    'Assessment',
                    'Improvement plan',
                    'Implementation',
                    'Documentation',
                ]),
                'hints' => 'Start with basic metrics. Add complexity gradually.',
                'estimated_time' => '6 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'GRC-029',
                'section' => 'grc',
                'title' => 'Security Awareness for Executives',
                'description' => 'Design executive-level security awareness.',
                'overview' => 'Executives need different training. Design it.',
                'objectives' => json_encode([
                    'Understand executive needs',
                    'Design briefings',
                    'Focus on risk and business',
                    'Plan cadence',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Understand executive priorities.',
                    'Design brief, business-focused sessions.',
                    'Focus on risk, not tech.',
                    'Plan quarterly cadence.',
                    'Prepare board-level reports.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'PowerPoint',
                    'Board Report Templates',
                ]),
                'resources' => json_encode([
                    'Board Communication - NACD',
                    'Executive Cyber Briefings',
                ]),
                'deliverables' => json_encode([
                    'Session materials',
                    'Cadence plan',
                    'Board reports',
                    'Documentation',
                ]),
                'hints' => 'Speak business language. Avoid tech jargon.',
                'estimated_time' => '6 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'GRC-030',
                'section' => 'grc',
                'title' => 'Cross-Border Data Transfer Compliance',
                'description' => 'Ensure compliance with cross-border data transfer rules.',
                'overview' => 'Data crossing borders has legal implications. Ensure compliance.',
                'objectives' => json_encode([
                    'Understand regulations',
                    'Map data flows',
                    'Identify legal mechanisms',
                    'Implement controls',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Identify cross-border data flows.',
                    'Research applicable laws.',
                    'Choose legal mechanism (SCCs, BCRs).',
                    'Implement technical controls.',
                    'Review contracts.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Data Flow Mapping Tools',
                    'Legal Templates',
                ]),
                'resources' => json_encode([
                    'GDPR Chapter V',
                    'Cross-Border Data Transfer Guide',
                ]),
                'deliverables' => json_encode([
                    'Data flow map',
                    'Legal analysis',
                    'Controls',
                    'Documentation',
                ]),
                'hints' => 'Involve legal team early.',
                'estimated_time' => '7 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== AUTOMATION ====================
            [
                'reference_code' => 'AUTO-026',
                'section' => 'automation',
                'title' => 'Automated Attack Surface Management',
                'description' => 'Automate attack surface discovery and monitoring.',
                'overview' => 'Attack surface changes constantly. Automate monitoring.',
                'objectives' => json_encode([
                    'Understand ASM',
                    'Set up discovery tools',
                    'Monitor continuously',
                    'Alert on changes',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Identify assets (domains, IPs, apps).',
                    'Set up automated discovery.',
                    'Monitor for new assets.',
                    'Alert on changes.',
                    'Track remediation.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Amass - https://github.com/OWASP/Amass',
                    'Shodan Monitor',
                    'SecurityScorecard',
                ]),
                'resources' => json_encode([
                    'ASM - Gartner',
                    'Attack Surface Management Guide',
                ]),
                'deliverables' => json_encode([
                    'Asset inventory',
                    'Discovery automation',
                    'Alerts',
                    'Documentation',
                ]),
                'hints' => 'Start with domain discovery. Expand to cloud.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'AUTO-027',
                'section' => 'automation',
                'title' => 'Automated Malware Analysis Pipeline',
                'description' => 'Set up automated malware analysis.',
                'overview' => 'Manual analysis does not scale. Automate it.',
                'objectives' => json_encode([
                    'Understand analysis pipeline',
                    'Set up Cuckoo/CAPE',
                    'Submit samples',
                    'Extract IOCs',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up CAPE sandbox.',
                    'Create submission API.',
                    'Automate sample submission.',
                    'Extract: IOCs, TTPs, network.',
                    'Push to threat intel.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'CAPE - https://github.com/kevoreilly/CAPEv2',
                    'Cuckoo',
                    'YARA',
                ]),
                'resources' => json_encode([
                    'CAPE Documentation',
                    'Malware Analysis Automation',
                ]),
                'deliverables' => json_encode([
                    'Sandbox setup',
                    'Automation',
                    'IOC extraction',
                    'Documentation',
                ]),
                'hints' => 'CAPE is the modern successor to Cuckoo.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'AUTO-028',
                'section' => 'automation',
                'title' => 'Automated Incident Notification',
                'description' => 'Automate incident notifications to stakeholders.',
                'overview' => 'Fast notification reduces impact. Automate it.',
                'objectives' => json_encode([
                    'Define notification matrix',
                    'Set up automation',
                    'Tier notifications',
                    'Test delivery',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Define who gets notified for what.',
                    'Set up n8n workflow.',
                    'Trigger on alert severity.',
                    'Send via Slack, email, SMS.',
                    'Track acknowledgments.',
                    'Test.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'n8n - https://n8n.io',
                    'Twilio',
                    'Slack API',
                ]),
                'resources' => json_encode([
                    'Incident Communication - NIST',
                    'Notification Best Practices',
                ]),
                'deliverables' => json_encode([
                    'Matrix',
                    'Workflow',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'Avoid alert fatigue. Notify only when needed.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'AUTO-029',
                'section' => 'automation',
                'title' => 'Automated Red Team Infrastructure',
                'description' => 'Automate red team infrastructure setup.',
                'overview' => 'Red team infra takes time. Automate it.',
                'objectives' => json_encode([
                    'Understand red team infra',
                    'Set up automation',
                    'Deploy C2 servers',
                    'Configure redirectors',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Use Terraform for cloud infra.',
                    'Deploy C2 (Cobalt Strike, Sliver).',
                    'Set up redirectors (Nginx).',
                    'Configure domains.',
                    'Automate teardown.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Terraform - https://www.terraform.io',
                    'Sliver - https://github.com/BishopFox/sliver',
                    'Ansible',
                ]),
                'resources' => json_encode([
                    'Red Team Infrastructure - Raphael Mudge',
                    'Red Team Ops',
                ]),
                'deliverables' => json_encode([
                    'Terraform config',
                    'C2 setup',
                    'Redirectors',
                    'Documentation',
                ]),
                'hints' => 'Always get authorization. Red teaming is serious.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'AUTO-030',
                'section' => 'automation',
                'title' => 'Automated Cyber Range',
                'description' => 'Set up an automated cyber range for training.',
                'overview' => 'Training needs realistic environments. Automate setup.',
                'objectives' => json_encode([
                    'Understand cyber range',
                    'Set up automation',
                    'Deploy vulnerable targets',
                    'Configure scoring',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Choose platform (Metasploitable, VulnHub).',
                    'Automate deployment (Terraform, Ansible).',
                    'Set up scoring system.',
                    'Configure isolation.',
                    'Test with users.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Metasploitable - https://github.com/rapid7/metasploitable3',
                    'VulnHub',
                    'Terraform',
                ]),
                'resources' => json_encode([
                    'Cyber Range Design',
                    'NIST Cyber Range Guide',
                ]),
                'deliverables' => json_encode([
                    'Automated deployment',
                    'Targets',
                    'Scoring',
                    'Documentation',
                ]),
                'hints' => 'Isolate range from production.',
                'estimated_time' => '10 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
        ];

        foreach ($tasks as $task) {
            $task['created_at'] = now();
            $task['updated_at'] = now();
            DB::table('cyber_tasks')->updateOrInsert(
                ['reference_code' => $task['reference_code']],
                $task
            );
        }

        echo "Phase 7 - Cyber Tasks created!\n";
        echo "Total: " . count($tasks) . " new tasks\n";
    }
}