<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CyberTasksPhase9Seeder extends Seeder
{
    public function run(): void
    {
        $tasks = [
            // ==================== NETWORK DEFENSE ====================
            [
                'reference_code' => 'NET-DEF-036',
                'section' => 'network_defense',
                'title' => 'Encrypted Traffic Analysis',
                'description' => 'Analyze encrypted traffic without decryption.',
                'overview' => 'Most traffic is encrypted. Analyze metadata for threats.',
                'objectives' => json_encode([
                    'Understand ETA',
                    'Analyze JA3/JA3S',
                    'Detect malicious TLS',
                    'Profile applications',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Capture TLS traffic.',
                    'Extract JA3 fingerprints.',
                    'Compare to known malicious.',
                    'Analyze certificate metadata.',
                    'Detect beaconing.',
                    'Document findings.',
                ]),
                'tools_list' => json_encode([
                    'Zeek - https://zeek.org',
                    'JA3 - https://github.com/salesforce/ja3',
                    'Wireshark',
                ]),
                'resources' => json_encode([
                    'JA3 Documentation',
                    'Encrypted Traffic Analysis - SANS',
                ]),
                'deliverables' => json_encode([
                    'JA3 fingerprints',
                    'Detection rules',
                    'Report',
                ]),
                'hints' => 'JA3 fingerprints identify client apps.',
                'estimated_time' => '5 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'NET-DEF-037',
                'section' => 'network_defense',
                'title' => 'Zero Trust Network Access (ZTNA)',
                'description' => 'Implement ZTNA solution.',
                'overview' => 'ZTNA replaces VPN. Implement it.',
                'objectives' => json_encode([
                    'Understand ZTNA',
                    'Set up Cloudflare Access',
                    'Configure identity-based access',
                    'Test with users',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up Cloudflare Access.',
                    'Configure identity provider.',
                    'Define access policies.',
                    'Test with users.',
                    'Verify least privilege.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Cloudflare Access - https://www.cloudflare.com',
                    'Tailscale - https://tailscale.com',
                    'Twingate - https://www.twingate.com',
                ]),
                'resources' => json_encode([
                    'ZTNA Guide - Gartner',
                    'Cloudflare Access Docs',
                ]),
                'deliverables' => json_encode([
                    'ZTNA setup',
                    'Policies',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'Tailscale is easiest for beginners.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'NET-DEF-038',
                'section' => 'network_defense',
                'title' => 'Network Detection and Response (NDR)',
                'description' => 'Deploy NDR for network threat detection.',
                'overview' => 'NDR detects threats in real-time. Deploy it.',
                'objectives' => json_encode([
                    'Understand NDR',
                    'Set up Zeek + RITA',
                    'Detect beaconing',
                    'Detect DNS tunneling',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Install Zeek on monitoring port.',
                    'Set up RITA for analysis.',
                    'Analyze traffic for threats.',
                    'Create detection rules.',
                    'Set up alerts.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Zeek - https://zeek.org',
                    'RITA - https://github.com/activecm/rita',
                    'Suricata',
                ]),
                'resources' => json_encode([
                    'NDR Guide - Gartner',
                    'Zeek Documentation',
                ]),
                'deliverables' => json_encode([
                    'NDR setup',
                    'Detections',
                    'Alerts',
                    'Documentation',
                ]),
                'hints' => 'RITA is excellent for detecting beaconing.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'NET-DEF-039',
                'section' => 'network_defense',
                'title' => 'Post-Quantum Cryptography Migration',
                'description' => 'Plan migration to post-quantum cryptography.',
                'overview' => 'Quantum computers will break RSA. Plan migration.',
                'objectives' => json_encode([
                    'Understand PQC',
                    'Inventory crypto usage',
                    'Prioritize migration',
                    'Test hybrid crypto',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Research NIST PQC standards.',
                    'Inventory current crypto.',
                    'Identify high-risk systems.',
                    'Test hybrid crypto.',
                    'Plan migration.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'OpenQuantumSafe - https://openquantumsafe.org',
                    'liboqs',
                ]),
                'resources' => json_encode([
                    'NIST PQC - https://csrc.nist.gov',
                    'PQC Migration Guide',
                ]),
                'deliverables' => json_encode([
                    'Inventory',
                    'Migration plan',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'Harvest-now-decrypt-later is a real threat.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'NET-DEF-040',
                'section' => 'network_defense',
                'title' => 'Network Security for OT/ICS',
                'description' => 'Secure OT/ICS networks.',
                'overview' => 'OT networks have unique security needs. Secure them.',
                'objectives' => json_encode([
                    'Understand OT/ICS',
                    'Assess security',
                    'Segment network',
                    'Monitor traffic',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Research OT protocols (Modbus, DNP3).',
                    'Set up OT lab.',
                    'Segment IT/OT.',
                    'Deploy passive monitoring.',
                    'Test with simulated attack.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Conpot - https://github.com/mushorg/conpot',
                    'Snort',
                    'Wireshark',
                ]),
                'resources' => json_encode([
                    'NIST OT Security Guide',
                    'SANS ICS Security',
                ]),
                'deliverables' => json_encode([
                    'Assessment',
                    'Segmentation',
                    'Monitoring',
                    'Documentation',
                ]),
                'hints' => 'Never actively scan OT networks.',
                'estimated_time' => '7 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== DFIR ====================
            [
                'reference_code' => 'DFIR-036',
                'section' => 'dfir',
                'title' => 'Rootkit Detection and Removal',
                'description' => 'Detect and remove kernel rootkits.',
                'overview' => 'Rootkits are stealthy. Learn to detect them.',
                'objectives' => json_encode([
                    'Understand rootkits',
                    'Detect with tools',
                    'Analyze behavior',
                    'Remove safely',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up test system with rootkit.',
                    'Detect with GMER, chkrootkit.',
                    'Analyze with Volatility.',
                    'Check for hidden processes.',
                    'Remove rootkit.',
                    'Verify removal.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'GMER - http://www.gmer.net',
                    'chkrootkit - http://www.chkrootkit.org',
                    'Volatility',
                ]),
                'resources' => json_encode([
                    'Rootkit Detection - SANS',
                    'The Rootkit Arsenal (Book)',
                ]),
                'deliverables' => json_encode([
                    'Detection methods',
                    'Analysis',
                    'Removal process',
                    'Report',
                ]),
                'hints' => 'Rootkits are rare but dangerous. Use multiple tools.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DFIR-037',
                'section' => 'dfir',
                'title' => 'Fileless Malware Analysis',
                'description' => 'Analyze fileless malware attacks.',
                'overview' => 'Fileless malware lives in memory. Learn to analyze.',
                'objectives' => json_encode([
                    'Understand fileless malware',
                    'Detect in memory',
                    'Analyze PowerShell/WMI',
                    'Extract IOCs',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up fileless attack (PowerShell).',
                    'Capture memory dump.',
                    'Analyze with Volatility.',
                    'Extract scripts.',
                    'Decode obfuscation.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Volatility 3',
                    'PowerShell Logs',
                    'PSDecode',
                ]),
                'resources' => json_encode([
                    'Fileless Malware - SANS',
                    'Memory Forensics',
                ]),
                'deliverables' => json_encode([
                    'Analysis',
                    'Decoded scripts',
                    'IOCs',
                    'Report',
                ]),
                'hints' => 'PowerShell logs are critical for fileless malware.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DFIR-038',
                'section' => 'dfir',
                'title' => 'Threat Actor Attribution',
                'description' => 'Attribute attacks to threat actors.',
                'overview' => 'Attribution is complex. Learn methodologies.',
                'objectives' => json_encode([
                    'Understand attribution',
                    'Analyze TTPs',
                    'Compare to known actors',
                    'Assess confidence',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Analyze attack TTPs.',
                    'Map to MITRE ATT&CK.',
                    'Compare with known APTs.',
                    'Analyze infrastructure.',
                    'Assess attribution confidence.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'MITRE ATT&CK',
                    'Maltego',
                    'VirusTotal',
                ]),
                'resources' => json_encode([
                    'Attribution Guide - RAND',
                    'APT Groups - MITRE',
                ]),
                'deliverables' => json_encode([
                    'TTP analysis',
                    'Attribution assessment',
                    'Confidence rating',
                    'Report',
                ]),
                'hints' => 'Attribution is rarely certain. Use probability.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DFIR-039',
                'section' => 'dfir',
                'title' => 'Digital Evidence Preservation',
                'description' => 'Preserve digital evidence for legal cases.',
                'overview' => 'Evidence must be preserved legally. Learn how.',
                'objectives' => json_encode([
                    'Understand legal requirements',
                    'Preserve evidence',
                    'Maintain chain of custody',
                    'Create forensic images',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Study legal requirements.',
                    'Create forensic image (dd, FTK).',
                    'Hash the image.',
                    'Document chain of custody.',
                    'Store securely.',
                    'Verify integrity.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'FTK Imager',
                    'dd',
                    'HashCalc',
                ]),
                'resources' => json_encode([
                    'SWGDE Standards',
                    'NIST Evidence Guide',
                ]),
                'deliverables' => json_encode([
                    'Forensic image',
                    'Hashes',
                    'Chain of custody',
                    'Documentation',
                ]),
                'hints' => 'Hash immediately after imaging.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DFIR-040',
                'section' => 'dfir',
                'title' => 'Cross-Platform Forensics',
                'description' => 'Perform forensics across Windows, Linux, and macOS.',
                'overview' => 'Investigations span platforms. Learn all three.',
                'objectives' => json_encode([
                    'Understand platform differences',
                    'Collect artifacts from each',
                    'Correlate across platforms',
                    'Document findings',
                    'Report',
                ]),
                'instructions' => json_encode([
                    'Set up multi-platform lab.',
                    'Generate activity on each.',
                    'Collect artifacts.',
                    'Correlate events.',
                    'Create unified timeline.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Autopsy',
                    'Volatility',
                    'Plaso',
                ]),
                'resources' => json_encode([
                    'Cross-Platform Forensics - SANS',
                    'Artifact Reference Guide',
                ]),
                'deliverables' => json_encode([
                    'Artifacts',
                    'Timeline',
                    'Correlation',
                    'Report',
                ]),
                'hints' => 'Time zones are a common pitfall.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== PENTEST ====================
            [
                'reference_code' => 'PT-036',
                'section' => 'pentest',
                'title' => 'Mobile App Reverse Engineering',
                'description' => 'Reverse engineer mobile apps for security.',
                'overview' => 'Mobile apps contain secrets. Learn to extract them.',
                'objectives' => json_encode([
                    'Understand mobile RE',
                    'Decompile APK/IPA',
                    'Extract secrets',
                    'Bypass protections',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Get APK.',
                    'Decompile with jadx.',
                    'Analyze source.',
                    'Extract API keys.',
                    'Bypass root detection.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'jadx - https://github.com/skylot/jadx',
                    'apktool - https://ibotpeaches.github.io/Apktool',
                    'Frida - https://frida.re',
                ]),
                'resources' => json_encode([
                    'Mobile RE Guide',
                    'OWASP MASTG',
                ]),
                'deliverables' => json_encode([
                    'Decompiled code',
                    'Extracted secrets',
                    'Bypass methods',
                    'Report',
                ]),
                'hints' => 'Hardcoded secrets are common in mobile apps.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'PT-037',
                'section' => 'pentest',
                'title' => 'SSRF to RCE Chains',
                'description' => 'Chain SSRF to achieve RCE.',
                'overview' => 'SSRF can be chained for RCE. Learn techniques.',
                'objectives' => json_encode([
                    'Understand SSRF chains',
                    'Exploit SSRF',
                    'Chain with internal services',
                    'Achieve RCE',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Find SSRF.',
                    'Test internal services.',
                    'Chain with Redis/Memcached.',
                    'Achieve RCE.',
                    'Document chain.',
                ]),
                'tools_list' => json_encode([
                    'Burp Suite',
                    'Gopherus - https://github.com/tarunkant/Gopherus',
                ]),
                'resources' => json_encode([
                    'SSRF to RCE - Research',
                    'Gopherus Documentation',
                ]),
                'deliverables' => json_encode([
                    'SSRF proof',
                    'Chain documentation',
                    'RCE proof',
                    'Report',
                ]),
                'hints' => 'Gopher protocol enables SSRF to many services.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'PT-038',
                'section' => 'pentest',
                'title' => 'Active Directory Certificate Services (ADCS) Attacks',
                'description' => 'Exploit ADCS misconfigurations.',
                'overview' => 'ADCS is often misconfigured. Exploit it.',
                'objectives' => json_encode([
                    'Understand ADCS',
                    'Enumerate templates',
                    'Exploit ESC1-ESC8',
                    'Get domain admin',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up ADCS lab.',
                    'Enumerate with Certipy.',
                    'Find vulnerable templates.',
                    'Exploit ESC1.',
                    'Get domain admin.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Certipy - https://github.com/ly4k/Certipy',
                    'Rubeus',
                    'BloodHound',
                ]),
                'resources' => json_encode([
                    'ADCS Attacks - SpecterOps',
                    'Certified Pre-Owned Whitepaper',
                ]),
                'deliverables' => json_encode([
                    'Enumeration',
                    'Exploitation',
                    'DA proof',
                    'Report',
                ]),
                'hints' => 'ESC8 (relay) is very common.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'PT-039',
                'section' => 'pentest',
                'title' => 'Firmware Analysis and Exploitation',
                'description' => 'Analyze and exploit firmware.',
                'overview' => 'Firmware contains vulnerabilities. Learn to find them.',
                'objectives' => json_encode([
                    'Extract firmware',
                    'Analyze file system',
                    'Find vulnerabilities',
                    'Exploit',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Get firmware image.',
                    'Extract with binwalk.',
                    'Analyze file system.',
                    'Find hardcoded secrets.',
                    'Analyze binaries with Ghidra.',
                    'Exploit vulnerability.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Binwalk - https://github.com/ReFirmLabs/binwalk',
                    'Ghidra - https://ghidra-sre.org',
                    'Firmware Analysis Toolkit',
                ]),
                'resources' => json_encode([
                    'Firmware Analysis Guide',
                    'Practical IoT Hacking (Book)',
                ]),
                'deliverables' => json_encode([
                    'Extracted files',
                    'Vulnerabilities',
                    'Exploit',
                    'Report',
                ]),
                'hints' => 'Firmware often contains hardcoded credentials.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'PT-040',
                'section' => 'pentest',
                'title' => 'Wi-Fi Evil Twin Attacks',
                'description' => 'Perform Evil Twin attacks.',
                'overview' => 'Evil Twin tricks users into connecting. Learn it.',
                'objectives' => json_encode([
                    'Understand Evil Twin',
                    'Set up fake AP',
                    'Capture credentials',
                    'Perform captive portal',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up fake AP (hostapd).',
                    'Configure captive portal.',
                    'Capture credentials.',
                    'Test with clients.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'hostapd-wpe',
                    'Wifiphisher - https://github.com/wifiphisher/wifiphisher',
                    'Fluxion',
                ]),
                'resources' => json_encode([
                    'Evil Twin Guide - SANS',
                    'Wi-Fi Pentesting',
                ]),
                'deliverables' => json_encode([
                    'AP setup',
                    'Captured creds',
                    'Report',
                ]),
                'hints' => 'Only test with authorization.',
                'estimated_time' => '5 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== DEVSECOPS ====================
            [
                'reference_code' => 'DEVSEC-036',
                'section' => 'devsecops',
                'title' => 'Software Composition Analysis (SCA)',
                'description' => 'Implement SCA for dependency security.',
                'overview' => 'Dependencies have vulnerabilities. Scan them.',
                'objectives' => json_encode([
                    'Understand SCA',
                    'Set up SCA tool',
                    'Scan dependencies',
                    'Integrate into CI/CD',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Choose SCA (Snyk, Dependabot).',
                    'Connect repository.',
                    'Scan dependencies.',
                    'Configure alerts.',
                    'Auto-fix where possible.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Snyk',
                    'Dependabot - https://github.com/dependabot',
                    'OWASP Dependency-Check',
                ]),
                'resources' => json_encode([
                    'SCA Guide - OWASP',
                    'Snyk Documentation',
                ]),
                'deliverables' => json_encode([
                    'SCA setup',
                    'Scan results',
                    'Fixes',
                    'Documentation',
                ]),
                'hints' => 'Dependabot is free for GitHub repos.',
                'estimated_time' => '4 hours',
                'difficulty' => 3,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DEVSEC-037',
                'section' => 'devsecops',
                'title' => 'Policy as Code',
                'description' => 'Implement policy as code with OPA.',
                'overview' => 'Policies should be code. Implement OPA.',
                'objectives' => json_encode([
                    'Understand policy as code',
                    'Set up OPA',
                    'Write policies',
                    'Integrate with K8s',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Install OPA.',
                    'Write policies in Rego.',
                    'Test policies.',
                    'Integrate with K8s.',
                    'Enforce policies.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'OPA - https://www.openpolicyagent.org',
                    'Gatekeeper',
                    'Conftest',
                ]),
                'resources' => json_encode([
                    'OPA Documentation',
                    'Rego Language Guide',
                ]),
                'deliverables' => json_encode([
                    'Policies',
                    'Integration',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'Rego is powerful but takes practice.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DEVSEC-038',
                'section' => 'devsecops',
                'title' => 'Security Chaos Engineering',
                'description' => 'Apply chaos engineering to security controls.',
                'overview' => 'Test security resilience with chaos.',
                'objectives' => json_encode([
                    'Understand security chaos',
                    'Design experiments',
                    'Execute experiments',
                    'Document findings',
                    'Improve controls',
                ]),
                'instructions' => json_encode([
                    'Design experiment: kill WAF.',
                    'Run with Chaos Toolkit.',
                    'Observe security behavior.',
                    'Identify gaps.',
                    'Improve controls.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Chaos Toolkit',
                    'Gremlin',
                    'Litmus',
                ]),
                'resources' => json_encode([
                    'Security Chaos Engineering - Kelly Shortridge',
                    'Chaos Toolkit Docs',
                ]),
                'deliverables' => json_encode([
                    'Experiments',
                    'Results',
                    'Improvements',
                    'Documentation',
                ]),
                'hints' => 'Start small. Chaos can break things.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DEVSEC-039',
                'section' => 'devsecops',
                'title' => 'API Rate Limiting Advanced',
                'description' => 'Implement advanced rate limiting.',
                'overview' => 'Basic rate limiting is not enough. Add advanced.',
                'objectives' => json_encode([
                    'Understand advanced rate limiting',
                    'Implement per-user limits',
                    'Add sliding windows',
                    'Detect abuse',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up Redis.',
                    'Implement sliding window.',
                    'Add per-user limits.',
                    'Configure different tiers.',
                    'Detect abuse patterns.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Redis - https://redis.io',
                    'Kong',
                    'Nginx',
                ]),
                'resources' => json_encode([
                    'Rate Limiting Patterns - Stripe',
                    'Redis Rate Limiting',
                ]),
                'deliverables' => json_encode([
                    'Rate limiting code',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'Sliding window is more accurate than fixed.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DEVSEC-040',
                'section' => 'devsecops',
                'title' => 'Secure Multi-Tenancy',
                'description' => 'Implement secure multi-tenancy.',
                'overview' => 'Multi-tenancy needs strong isolation. Implement it.',
                'objectives' => json_encode([
                    'Understand multi-tenancy',
                    'Design isolation',
                    'Implement controls',
                    'Test isolation',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Design tenancy model.',
                    'Implement: DB, cache, storage isolation.',
                    'Test cross-tenant access.',
                    'Verify isolation.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'PostgreSQL RLS',
                    'Kubernetes Namespaces',
                ]),
                'resources' => json_encode([
                    'Multi-Tenancy Guide - AWS',
                    'SaaS Security Best Practices',
                ]),
                'deliverables' => json_encode([
                    'Design',
                    'Controls',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'Row-level security is essential for shared DBs.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== GRC ====================
            [
                'reference_code' => 'GRC-036',
                'section' => 'grc',
                'title' => 'Security Program KPIs',
                'description' => 'Define and track security program KPIs.',
                'overview' => 'KPIs measure program effectiveness. Define them.',
                'objectives' => json_encode([
                    'Understand KPIs',
                    'Define relevant KPIs',
                    'Set targets',
                    'Track and report',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Identify key areas.',
                    'Define KPIs (MTTD, MTTR, patch rate).',
                    'Set targets.',
                    'Track monthly.',
                    'Report to management.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Excel',
                    'Power BI',
                    'Metrics Tools',
                ]),
                'resources' => json_encode([
                    'Security KPIs - Gartner',
                    'CISO Metrics',
                ]),
                'deliverables' => json_encode([
                    'KPI definitions',
                    'Targets',
                    'Reports',
                    'Documentation',
                ]),
                'hints' => 'Fewer, better KPIs beat many poor ones.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'GRC-037',
                'section' => 'grc',
                'title' => 'Security Awareness for Remote Workers',
                'description' => 'Design awareness for remote workforce.',
                'overview' => 'Remote workers have unique risks. Train them.',
                'objectives' => json_encode([
                    'Understand remote risks',
                    'Design training',
                    'Cover home network, VPN',
                    'Measure effectiveness',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Identify remote-specific risks.',
                    'Design training modules.',
                    'Cover: home Wi-Fi, VPN, phishing.',
                    'Deliver training.',
                    'Measure effectiveness.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'LMS',
                    'Video Tools',
                ]),
                'resources' => json_encode([
                    'Remote Worker Security - NIST',
                    'SANS Remote Work Guide',
                ]),
                'deliverables' => json_encode([
                    'Training modules',
                    'Delivery',
                    'Metrics',
                    'Documentation',
                ]),
                'hints' => 'Home routers are often insecure.',
                'estimated_time' => '6 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'GRC-038',
                'section' => 'grc',
                'title' => 'Security Due Diligence for Startups',
                'description' => 'Perform security due diligence for startup investments.',
                'overview' => 'Startups often lack security. Assess them.',
                'objectives' => json_encode([
                    'Understand startup security',
                    'Assess posture',
                    'Identify risks',
                    'Plan improvements',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Review security policies.',
                    'Assess technical controls.',
                    'Review incidents.',
                    'Assess compliance.',
                    'Plan improvements.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Due Diligence Checklists',
                ]),
                'resources' => json_encode([
                    'Startup Security - YC',
                    'Due Diligence Guide',
                ]),
                'deliverables' => json_encode([
                    'Assessment',
                    'Risk analysis',
                    'Recommendations',
                    'Documentation',
                ]),
                'hints' => 'Focus on deal-breakers.',
                'estimated_time' => '7 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'GRC-039',
                'section' => 'grc',
                'title' => 'Zero Trust Maturity Assessment',
                'description' => 'Assess Zero Trust maturity.',
                'overview' => 'Zero Trust is a journey. Assess maturity.',
                'objectives' => json_encode([
                    'Understand ZT maturity',
                    'Assess current state',
                    'Identify gaps',
                    'Plan roadmap',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Use CISA ZT Maturity Model.',
                    'Assess each pillar.',
                    'Score maturity.',
                    'Identify gaps.',
                    'Create roadmap.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'CISA ZT Maturity Model',
                ]),
                'resources' => json_encode([
                    'CISA Zero Trust Maturity',
                    'NIST ZT Guide',
                ]),
                'deliverables' => json_encode([
                    'Assessment',
                    'Roadmap',
                    'Gaps',
                    'Documentation',
                ]),
                'hints' => 'ZT is a journey, not a destination.',
                'estimated_time' => '7 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'GRC-040',
                'section' => 'grc',
                'title' => 'Board-Level Cyber Risk Reporting',
                'description' => 'Prepare board-level cyber risk reports.',
                'overview' => 'Boards need cyber risk in business terms.',
                'objectives' => json_encode([
                    'Understand board reporting',
                    'Translate risk to business',
                    'Create dashboards',
                    'Present effectively',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Identify board priorities.',
                    'Translate technical to business.',
                    'Create risk dashboard.',
                    'Prepare quarterly report.',
                    'Present to board.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'PowerPoint',
                    'Power BI',
                ]),
                'resources' => json_encode([
                    'Board Reporting - NACD',
                    'Cyber Risk Reporting',
                ]),
                'deliverables' => json_encode([
                    'Board report',
                    'Dashboard',
                    'Presentation',
                    'Documentation',
                ]),
                'hints' => 'Speak dollars and risk, not CVEs.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== AUTOMATION ====================
            [
                'reference_code' => 'AUTO-036',
                'section' => 'automation',
                'title' => 'Automated Digital Forensics Triage',
                'description' => 'Automate initial forensic triage.',
                'overview' => 'Triage takes time. Automate it.',
                'objectives' => json_encode([
                    'Understand triage',
                    'Set up automation',
                    'Collect key artifacts',
                    'Generate reports',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Write triage script (KAPE).',
                    'Collect: registry, event logs, prefetch.',
                    'Parse artifacts.',
                    'Generate triage report.',
                    'Test with sample system.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'KAPE - https://www.kroll.com/kape',
                    'Velociraptor',
                    'Eric Zimmerman Tools',
                ]),
                'resources' => json_encode([
                    'KAPE Documentation',
                    'SANS Triage Guide',
                ]),
                'deliverables' => json_encode([
                    'Triage script',
                    'Sample report',
                    'Documentation',
                ]),
                'hints' => 'KAPE is the industry standard.',
                'estimated_time' => '6 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'AUTO-037',
                'section' => 'automation',
                'title' => 'Automated Network Discovery',
                'description' => 'Automate network asset discovery.',
                'overview' => 'You cannot secure unknown assets. Automate discovery.',
                'objectives' => json_encode([
                    'Understand discovery',
                    'Set up scanning',
                    'Schedule scans',
                    'Track changes',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Install Nmap/Netdiscover.',
                    'Scan network weekly.',
                    'Compare with inventory.',
                    'Alert on new assets.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Nmap - https://nmap.org',
                    'Netdiscover',
                    'Fing',
                ]),
                'resources' => json_encode([
                    'Network Discovery Guide',
                    'Nmap Book',
                ]),
                'deliverables' => json_encode([
                    'Scan config',
                    'Inventory',
                    'Alerts',
                    'Documentation',
                ]),
                'hints' => 'Scan during off-hours to reduce impact.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'AUTO-038',
                'section' => 'automation',
                'title' => 'Automated Security Metrics Collection',
                'description' => 'Automate security metrics collection.',
                'overview' => 'Manual metrics collection wastes time. Automate.',
                'objectives' => json_encode([
                    'Define metrics',
                    'Identify sources',
                    'Automate collection',
                    'Build dashboard',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Define metrics.',
                    'Identify APIs.',
                    'Write Python collectors.',
                    'Store in time-series DB.',
                    'Build Grafana dashboard.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Python',
                    'Prometheus',
                    'Grafana',
                ]),
                'resources' => json_encode([
                    'Metrics Collection Guide',
                    'Prometheus Documentation',
                ]),
                'deliverables' => json_encode([
                    'Collectors',
                    'Dashboard',
                    'Documentation',
                ]),
                'hints' => 'Prometheus is great for time-series.',
                'estimated_time' => '6 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'AUTO-039',
                'section' => 'automation',
                'title' => 'Automated Red Team Reporting',
                'description' => 'Automate red team report generation.',
                'overview' => 'Red team reports take days. Automate parts.',
                'objectives' => json_encode([
                    'Understand report automation',
                    'Set up templates',
                    'Automate data collection',
                    'Generate reports',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Create report templates.',
                    'Collect findings in structured format.',
                    'Auto-generate PDFs with Python.',
                    'Include evidence.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Python (ReportLab)',
                    'Serpico - https://github.com/SerpicoProject/Serpico',
                ]),
                'resources' => json_encode([
                    'Report Automation Guide',
                    'Serpico Documentation',
                ]),
                'deliverables' => json_encode([
                    'Templates',
                    'Scripts',
                    'Sample reports',
                    'Documentation',
                ]),
                'hints' => 'Serpico is designed for pentest reports.',
                'estimated_time' => '6 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'AUTO-040',
                'section' => 'automation',
                'title' => 'Automated Purple Team Exercises',
                'description' => 'Automate purple team exercises.',
                'overview' => 'Purple teaming improves detection. Automate it.',
                'objectives' => json_encode([
                    'Understand purple teaming',
                    'Set up automation',
                    'Run attacks and detect',
                    'Measure coverage',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Use Atomic Red Team.',
                    'Run attacks from ATT&CK.',
                    'Check if detected.',
                    'Measure detection coverage.',
                    'Improve rules.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Atomic Red Team - https://github.com/redcanaryco/atomic-red-team',
                    'Caldera - https://github.com/mitre/caldera',
                    'MITRE ATT&CK',
                ]),
                'resources' => json_encode([
                    'Atomic Red Team',
                    'Purple Team Guide',
                ]),
                'deliverables' => json_encode([
                    'Automation setup',
                    'Coverage report',
                    'Improvements',
                    'Documentation',
                ]),
                'hints' => 'Atomic Red Team is simple and effective.',
                'estimated_time' => '7 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
        ];

        foreach ($tasks as $task) {
            $task['created_at'] = now();
            $task['updated_at'] = now();
            DB::table('cyber_tasks')->updateOrInsert(
                ['reference_code' => $task['reference_code']],
                $task
            );
        }

        echo "Phase 9 - Cyber Tasks created!\n";
        echo "Total: " . count($tasks) . " new tasks\n";
    }
}