<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CyberTasksPhase11Seeder extends Seeder
{
    public function run(): void
    {
        $tasks = [
            // ==================== NETWORK DEFENSE ====================
            [
                'reference_code' => 'NET-DEF-046',
                'section' => 'network_defense',
                'title' => 'Quantum-Safe VPN Migration',
                'description' => 'Migrate VPN to quantum-safe cryptography.',
                'overview' => 'VPNs will be broken by quantum. Migrate to PQC.',
                'objectives' => json_encode([
                    'Understand PQC VPN',
                    'Set up OpenVPN with PQC',
                    'Test hybrid mode',
                    'Measure performance',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Install OpenVPN with OQS provider.',
                    'Configure hybrid key exchange.',
                    'Test client connection.',
                    'Measure performance impact.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'OpenVPN',
                    'OpenQuantumSafe - https://openquantumsafe.org',
                ]),
                'resources' => json_encode([
                    'PQC Migration Guide',
                    'OpenVPN PQC',
                ]),
                'deliverables' => json_encode([
                    'VPN config',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'PQC has performance overhead. Test carefully.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'NET-DEF-047',
                'section' => 'network_defense',
                'title' => 'Blockchain Network Security',
                'description' => 'Secure blockchain network infrastructure.',
                'overview' => 'Blockchain nodes need hardening. Secure them.',
                'objectives' => json_encode([
                    'Understand blockchain security',
                    'Harden nodes',
                    'Monitor peer connections',
                    'Detect attacks',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up blockchain node (Ethereum).',
                    'Harden node config.',
                    'Monitor peer traffic.',
                    'Detect eclipse attacks.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Geth',
                    'Wireshark',
                ]),
                'resources' => json_encode([
                    'Blockchain Security Guide',
                    'Ethereum Node Security',
                ]),
                'deliverables' => json_encode([
                    'Node config',
                    'Monitoring',
                    'Documentation',
                ]),
                'hints' => 'Blockchain nodes are often exposed.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'NET-DEF-048',
                'section' => 'network_defense',
                'title' => 'Satellite Communication Security',
                'description' => 'Secure satellite communications.',
                'overview' => 'Satellite comms are critical. Secure them.',
                'objectives' => json_encode([
                    'Understand satcom security',
                    'Assess encryption',
                    'Test jamming resistance',
                    'Document findings',
                ]),
                'instructions' => json_encode([
                    'Research satcom protocols.',
                    'Assess encryption.',
                    'Test jamming.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'SDR Tools',
                ]),
                'resources' => json_encode([
                    'Satellite Security Guide',
                ]),
                'deliverables' => json_encode([
                    'Assessment',
                    'Report',
                ]),
                'hints' => 'Satcom is a niche but critical area.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'NET-DEF-049',
                'section' => 'network_defense',
                'title' => 'Edge Computing Security',
                'description' => 'Secure edge computing deployments.',
                'overview' => 'Edge computing is growing. Secure it.',
                'objectives' => json_encode([
                    'Understand edge security',
                    'Set up edge node',
                    'Secure communications',
                    'Monitor edge',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up edge device (Raspberry Pi).',
                    'Harden OS.',
                    'Secure edge-cloud comms.',
                    'Monitor edge.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Raspberry Pi',
                    'Tailscale',
                ]),
                'resources' => json_encode([
                    'Edge Security - NIST',
                    'IoT Edge Security',
                ]),
                'deliverables' => json_encode([
                    'Edge setup',
                    'Hardening',
                    'Monitoring',
                    'Documentation',
                ]),
                'hints' => 'Edge devices are often physically accessible.',
                'estimated_time' => '6 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'NET-DEF-050',
                'section' => 'network_defense',
                'title' => 'Mesh Network Security',
                'description' => 'Secure mesh networks.',
                'overview' => 'Mesh networks have unique risks. Secure them.',
                'objectives' => json_encode([
                    'Understand mesh networks',
                    'Set up secure mesh',
                    'Test with node failure',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up mesh network (Batman-adv).',
                    'Configure encryption.',
                    'Test resilience.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Batman-adv',
                    'WireGuard',
                ]),
                'resources' => json_encode([
                    'Mesh Network Security',
                ]),
                'deliverables' => json_encode([
                    'Mesh setup',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'Mesh networks are self-healing.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== DFIR ====================
            [
                'reference_code' => 'DFIR-046',
                'section' => 'dfir',
                'title' => 'Advanced Persistent Threat (APT) Investigation',
                'description' => 'Investigate APT intrusions.',
                'overview' => 'APTs are sophisticated. Investigate them.',
                'objectives' => json_encode([
                    'Understand APT TTPs',
                    'Detect long-term persistence',
                    'Trace C2 infrastructure',
                    'Document findings',
                ]),
                'instructions' => json_encode([
                    'Analyze environment.',
                    'Hunt for persistence.',
                    'Trace C2.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'MITRE ATT&CK',
                    'Volatility',
                    'YARA',
                ]),
                'resources' => json_encode([
                    'APT Investigation - SANS',
                    'Threat Hunting Guide',
                ]),
                'deliverables' => json_encode([
                    'Investigation report',
                    'IOCs',
                    'Timeline',
                    'Documentation',
                ]),
                'hints' => 'APTs often use legitimate tools.',
                'estimated_time' => '10 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DFIR-047',
                'section' => 'dfir',
                'title' => 'Deepfake Investigation',
                'description' => 'Investigate deepfake-based fraud.',
                'overview' => 'Deepfakes enable fraud. Learn to investigate.',
                'objectives' => json_encode([
                    'Understand deepfakes',
                    'Analyze media',
                    'Detect manipulation',
                    'Document findings',
                ]),
                'instructions' => json_encode([
                    'Research deepfake tools.',
                    'Analyze sample media.',
                    'Detect manipulation markers.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Deepware Scanner',
                    'Forensically',
                ]),
                'resources' => json_encode([
                    'Deepfake Detection Guide',
                ]),
                'deliverables' => json_encode([
                    'Analysis report',
                    'Detection methods',
                    'Documentation',
                ]),
                'hints' => 'Deepfakes often have artifacts.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DFIR-048',
                'section' => 'dfir',
                'title' => 'Cryptocurrency Investigation',
                'description' => 'Investigate cryptocurrency-related crime.',
                'overview' => 'Crypto crime is growing. Learn to investigate.',
                'objectives' => json_encode([
                    'Understand blockchain analysis',
                    'Trace transactions',
                    'Identify wallets',
                    'Document findings',
                ]),
                'instructions' => json_encode([
                    'Use blockchain explorers.',
                    'Trace transactions.',
                    'Cluster wallets.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Chainalysis',
                    'Blockchair',
                ]),
                'resources' => json_encode([
                    'Crypto Investigation Guide',
                ]),
                'deliverables' => json_encode([
                    'Transaction analysis',
                    'Wallet identification',
                    'Report',
                ]),
                'hints' => 'Blockchain analysis requires patience.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DFIR-049',
                'section' => 'dfir',
                'title' => 'Stolen Device Investigation',
                'description' => 'Investigate stolen device incidents.',
                'overview' => 'Stolen devices contain data. Respond effectively.',
                'objectives' => json_encode([
                    'Understand response',
                    'Remote wipe',
                    'Investigate access',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Locate device (Find My).',
                    'Remote wipe.',
                    'Change passwords.',
                    'Investigate access.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Find My / Find My Device',
                    'MDM Tools',
                ]),
                'resources' => json_encode([
                    'Stolen Device Response',
                ]),
                'deliverables' => json_encode([
                    'Response records',
                    'Investigation',
                    'Documentation',
                ]),
                'hints' => 'Always enable remote wipe.',
                'estimated_time' => '4 hours',
                'difficulty' => 3,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DFIR-050',
                'section' => 'dfir',
                'title' => 'Witness Interview Techniques',
                'description' => 'Conduct effective witness interviews.',
                'overview' => 'Interviews yield key evidence. Learn techniques.',
                'objectives' => json_encode([
                    'Understand interview techniques',
                    'Prepare questions',
                    'Conduct interview',
                    'Document findings',
                ]),
                'instructions' => json_encode([
                    'Research interview techniques.',
                    'Prepare open-ended questions.',
                    'Conduct interview.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Interview Templates',
                ]),
                'resources' => json_encode([
                    'Investigative Interviewing',
                ]),
                'deliverables' => json_encode([
                    'Interview plan',
                    'Notes',
                    'Report',
                ]),
                'hints' => 'Open-ended questions yield more info.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== PENTEST ====================
            [
                'reference_code' => 'PT-046',
                'section' => 'pentest',
                'title' => 'Advanced Web Cache Deception',
                'description' => 'Exploit web cache deception attacks.',
                'overview' => 'Cache deception tricks caches. Learn it.',
                'objectives' => json_encode([
                    'Understand cache deception',
                    'Identify cacheable endpoints',
                    'Exploit with path confusion',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Identify cacheable endpoints.',
                    'Test path confusion.',
                    'Exploit with crafted URL.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Burp Suite',
                ]),
                'resources' => json_encode([
                    'Web Cache Deception - PortSwigger',
                ]),
                'deliverables' => json_encode([
                    'Exploit proof',
                    'Report',
                ]),
                'hints' => 'Trailing slashes often trick caches.',
                'estimated_time' => '5 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'PT-047',
                'section' => 'pentest',
                'title' => 'OAuth 2.0 Attacks',
                'description' => 'Attack OAuth 2.0 implementations.',
                'overview' => 'OAuth is complex. Attacks are common.',
                'objectives' => json_encode([
                    'Understand OAuth',
                    'Test redirect_uri',
                    'Test CSRF',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Analyze OAuth flow.',
                    'Test redirect_uri manipulation.',
                    'Test state parameter.',
                    'Test token leakage.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Burp Suite',
                ]),
                'resources' => json_encode([
                    'OAuth Attacks - PortSwigger',
                    'OAuth Security - OWASP',
                ]),
                'deliverables' => json_encode([
                    'Vulnerabilities',
                    'Exploit proofs',
                    'Report',
                ]),
                'hints' => 'redirect_uri is often exploitable.',
                'estimated_time' => '5 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'PT-048',
                'section' => 'pentest',
                'title' => 'SAML Attacks',
                'description' => 'Attack SAML implementations.',
                'overview' => 'SAML is common in SSO. Learn attacks.',
                'objectives' => json_encode([
                    'Understand SAML',
                    'Test signature bypass',
                    'Test XXE',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Analyze SAML flow.',
                    'Test signature stripping.',
                    'Test XXE.',
                    'Test comment injection.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'SAML Raider - Burp Extension',
                ]),
                'resources' => json_encode([
                    'SAML Attacks - OWASP',
                ]),
                'deliverables' => json_encode([
                    'Exploit proofs',
                    'Report',
                ]),
                'hints' => 'Signature validation is often broken.',
                'estimated_time' => '5 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'PT-049',
                'section' => 'pentest',
                'title' => 'Zero-Day Research Methodology',
                'description' => 'Develop a zero-day research methodology.',
                'overview' => 'Finding zero-days requires methodology. Develop it.',
                'objectives' => json_encode([
                    'Understand research',
                    'Set up fuzzing',
                    'Analyze crashes',
                    'Develop exploit',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Choose target software.',
                    'Set up fuzzing (AFL).',
                    'Analyze crashes.',
                    'Develop PoC.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'AFL++ - https://github.com/AFLplusplus/AFLplusplus',
                    'Ghidra',
                ]),
                'resources' => json_encode([
                    'Fuzzing Guide',
                    'Zero-Day Research',
                ]),
                'deliverables' => json_encode([
                    'Fuzzing setup',
                    'Crashes',
                    'PoC',
                    'Documentation',
                ]),
                'hints' => 'Fuzzing finds bugs, not exploits.',
                'estimated_time' => '10 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'PT-050',
                'section' => 'pentest',
                'title' => 'Hardware Hacking',
                'description' => 'Perform hardware security testing.',
                'overview' => 'Hardware has security too. Learn to test it.',
                'objectives' => json_encode([
                    'Understand hardware attacks',
                    'Identify interfaces (UART, JTAG)',
                    'Extract firmware',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Get test device.',
                    'Identify UART/JTAG.',
                    'Connect with adapter.',
                    'Extract firmware.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Bus Pirate',
                    'Logic Analyzer',
                    'Binwalk',
                ]),
                'resources' => json_encode([
                    'Hardware Hacking Handbook',
                    'Practical IoT Hacking',
                ]),
                'deliverables' => json_encode([
                    'Interface identification',
                    'Extracted firmware',
                    'Report',
                ]),
                'hints' => 'UART is often unsecured.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== DEVSECOPS ====================
            [
                'reference_code' => 'DEVSEC-046',
                'section' => 'devsecops',
                'title' => 'Firmware SBOM',
                'description' => 'Generate SBOM for firmware.',
                'overview' => 'Firmware has components. Generate SBOM.',
                'objectives' => json_encode([
                    'Understand firmware SBOM',
                    'Extract firmware',
                    'Generate SBOM',
                    'Analyze',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Extract firmware.',
                    'Use Binwalk.',
                    'Identify components.',
                    'Generate SBOM.',
                    'Analyze vulnerabilities.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Binwalk',
                    'Syft',
                ]),
                'resources' => json_encode([
                    'Firmware SBOM Guide',
                ]),
                'deliverables' => json_encode([
                    'SBOM',
                    'Vulnerability analysis',
                    'Documentation',
                ]),
                'hints' => 'Firmware SBOM is emerging.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DEVSEC-047',
                'section' => 'devsecops',
                'title' => 'Homomorphic Encryption',
                'description' => 'Implement homomorphic encryption.',
                'overview' => 'FHE allows computing on encrypted data.',
                'objectives' => json_encode([
                    'Understand FHE',
                    'Set up library',
                    'Test computation',
                    'Measure performance',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Install Microsoft SEAL.',
                    'Write test program.',
                    'Compute on encrypted data.',
                    'Measure overhead.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Microsoft SEAL - https://github.com/microsoft/SEAL',
                ]),
                'resources' => json_encode([
                    'FHE Guide',
                    'SEAL Documentation',
                ]),
                'deliverables' => json_encode([
                    'Test program',
                    'Performance data',
                    'Documentation',
                ]),
                'hints' => 'FHE is slow but powerful.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DEVSEC-048',
                'section' => 'devsecops',
                'title' => 'Differential Privacy',
                'description' => 'Implement differential privacy.',
                'overview' => 'DP protects individual data in aggregates.',
                'objectives' => json_encode([
                    'Understand DP',
                    'Set up library',
                    'Test queries',
                    'Measure privacy',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Install OpenDP.',
                    'Write DP query.',
                    'Test with data.',
                    'Measure privacy budget.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'OpenDP - https://opendp.org',
                ]),
                'resources' => json_encode([
                    'DP Guide',
                    'OpenDP Documentation',
                ]),
                'deliverables' => json_encode([
                    'DP queries',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'DP is critical for privacy.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DEVSEC-049',
                'section' => 'devsecops',
                'title' => 'Attack Surface Reduction',
                'description' => 'Reduce application attack surface.',
                'overview' => 'Smaller surface = fewer attacks.',
                'objectives' => json_encode([
                    'Understand ASR',
                    'Identify surface',
                    'Reduce features',
                    'Test reduction',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Map attack surface.',
                    'Identify unused features.',
                    'Remove/disable features.',
                    'Test.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Attack Surface Analyzer - https://github.com/microsoft/AttackSurfaceAnalyzer',
                ]),
                'resources' => json_encode([
                    'ASR Guide - Microsoft',
                ]),
                'deliverables' => json_encode([
                    'Surface map',
                    'Reductions',
                    'Documentation',
                ]),
                'hints' => 'Less code = less risk.',
                'estimated_time' => '6 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DEVSEC-050',
                'section' => 'devsecops',
                'title' => 'Secure Multi-Party Computation',
                'description' => 'Implement secure multi-party computation.',
                'overview' => 'MPC allows joint computation without sharing.',
                'objectives' => json_encode([
                    'Understand MPC',
                    'Set up framework',
                    'Test computation',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Install MP-SPDZ.',
                    'Write MPC program.',
                    'Test with parties.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'MP-SPDZ - https://github.com/data61/MP-SPDZ',
                ]),
                'resources' => json_encode([
                    'MPC Guide',
                    'MP-SPDZ Documentation',
                ]),
                'deliverables' => json_encode([
                    'MPC program',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'MPC is complex but powerful.',
                'estimated_time' => '10 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== GRC ====================
            [
                'reference_code' => 'GRC-046',
                'section' => 'grc',
                'title' => 'Cyber Crisis Communication',
                'description' => 'Plan cyber crisis communication.',
                'overview' => 'Crises need communication. Plan it.',
                'objectives' => json_encode([
                    'Understand crisis comms',
                    'Identify stakeholders',
                    'Prepare templates',
                    'Practice',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Identify stakeholders.',
                    'Prepare templates.',
                    'Set up communication channels.',
                    'Practice with tabletop.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Communication Platforms',
                    'Templates',
                ]),
                'resources' => json_encode([
                    'Crisis Communication - FEMA',
                ]),
                'deliverables' => json_encode([
                    'Plan',
                    'Templates',
                    'Practice notes',
                    'Documentation',
                ]),
                'hints' => 'Plan before crisis hits.',
                'estimated_time' => '7 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'GRC-047',
                'section' => 'grc',
                'title' => 'Security Program ROI',
                'description' => 'Calculate security program ROI.',
                'overview' => 'ROI justifies investment. Calculate it.',
                'objectives' => json_encode([
                    'Understand ROI',
                    'Identify metrics',
                    'Calculate',
                    'Present',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Identify costs.',
                    'Identify benefits (prevented incidents).',
                    'Calculate ROI.',
                    'Present.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Excel',
                ]),
                'resources' => json_encode([
                    'ROI Guide - Gartner',
                ]),
                'deliverables' => json_encode([
                    'ROI analysis',
                    'Presentation',
                    'Documentation',
                ]),
                'hints' => 'Quantify prevented costs.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'GRC-048',
                'section' => 'grc',
                'title' => 'Regulatory Horizon Scanning',
                'description' => 'Scan for upcoming regulations.',
                'overview' => 'Regulations change. Scan for upcoming.',
                'objectives' => json_encode([
                    'Understand horizon scanning',
                    'Set up sources',
                    'Monitor changes',
                    'Assess impact',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Identify regulatory sources.',
                    'Set up RSS/news alerts.',
                    'Monitor monthly.',
                    'Assess impact.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'RSS Readers',
                    'Legal Databases',
                ]),
                'resources' => json_encode([
                    'Regulatory Monitoring Guide',
                ]),
                'deliverables' => json_encode([
                    'Sources list',
                    'Monitoring',
                    'Impact analysis',
                    'Documentation',
                ]),
                'hints' => 'Regulations can change fast.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'GRC-049',
                'section' => 'grc',
                'title' => 'Cyber Diplomacy',
                'description' => 'Understand cyber diplomacy.',
                'overview' => 'Cyber is diplomatic. Understand it.',
                'objectives' => json_encode([
                    'Understand cyber diplomacy',
                    'Identify norms',
                    'Assess implications',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Research cyber norms (UN GGE).',
                    'Assess implications.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Research Tools',
                ]),
                'resources' => json_encode([
                    'Cyber Diplomacy - UN',
                ]),
                'deliverables' => json_encode([
                    'Analysis',
                    'Documentation',
                ]),
                'hints' => 'Diplomacy shapes cyber policy.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'GRC-050',
                'section' => 'grc',
                'title' => 'Cybersecurity Workforce Development',
                'description' => 'Develop cybersecurity workforce.',
                'overview' => 'Talent is scarce. Develop your workforce.',
                'objectives' => json_encode([
                    'Understand workforce needs',
                    'Identify skills gaps',
                    'Plan development',
                    'Implement',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Assess current skills.',
                    'Identify gaps.',
                    'Plan training.',
                    'Implement.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Skills Matrix',
                    'LMS',
                ]),
                'resources' => json_encode([
                    'NICE Framework - NIST',
                ]),
                'deliverables' => json_encode([
                    'Assessment',
                    'Development plan',
                    'Documentation',
                ]),
                'hints' => 'NICE Framework guides workforce.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== AUTOMATION ====================
            [
                'reference_code' => 'AUTO-046',
                'section' => 'automation',
                'title' => 'AI Security Assistant',
                'description' => 'Build an AI security assistant.',
                'overview' => 'AI can assist security. Build an assistant.',
                'objectives' => json_encode([
                    'Understand AI assistants',
                    'Set up LLM',
                    'Integrate security tools',
                    'Test',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up LLM (OpenAI, Ollama).',
                    'Integrate with SIEM.',
                    'Add functions.',
                    'Test.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'OpenAI API',
                    'Ollama',
                    'LangChain',
                ]),
                'resources' => json_encode([
                    'AI Security Guide',
                ]),
                'deliverables' => json_encode([
                    'AI setup',
                    'Integrations',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'Ollama runs local models.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'AUTO-047',
                'section' => 'automation',
                'title' => 'Automated Deception Technology',
                'description' => 'Deploy deception technology.',
                'overview' => 'Deception catches attackers. Deploy it.',
                'objectives' => json_encode([
                    'Understand deception',
                    'Deploy honeypots',
                    'Set up monitoring',
                    'Test',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Deploy honeypots.',
                    'Set up monitoring.',
                    'Configure alerts.',
                    'Test.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'T-Pot',
                    'Canarytokens',
                ]),
                'resources' => json_encode([
                    'Deception Guide',
                ]),
                'deliverables' => json_encode([
                    'Deployment',
                    'Monitoring',
                    'Documentation',
                ]),
                'hints' => 'Deception is high-signal.',
                'estimated_time' => '6 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'AUTO-048',
                'section' => 'automation',
                'title' => 'Automated Tabletop Exercises',
                'description' => 'Automate tabletop exercises.',
                'overview' => 'Tabletops need practice. Automate them.',
                'objectives' => json_encode([
                    'Understand tabletops',
                    'Set up automation',
                    'Run exercises',
                    'Measure',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Build scenario library.',
                    'Set up automation.',
                    'Run exercises.',
                    'Score responses.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Scenario Tools',
                    'LMS',
                ]),
                'resources' => json_encode([
                    'Tabletop Guide - CISA',
                ]),
                'deliverables' => json_encode([
                    'Scenarios',
                    'Automation',
                    'Results',
                    'Documentation',
                ]),
                'hints' => 'Vary scenarios. Avoid habituation.',
                'estimated_time' => '7 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'AUTO-049',
                'section' => 'automation',
                'title' => 'Automated Risk Quantification',
                'description' => 'Automate risk quantification with FAIR.',
                'overview' => 'Risk quantification needs data. Automate it.',
                'objectives' => json_encode([
                    'Understand FAIR',
                    'Set up automation',
                    'Run simulations',
                    'Present results',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Learn FAIR.',
                    'Set up tool.',
                    'Run Monte Carlo.',
                    'Present results.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'FAIR Tools',
                    'Excel',
                ]),
                'resources' => json_encode([
                    'FAIR Institute - https://www.fairinstitute.org',
                ]),
                'deliverables' => json_encode([
                    'Risk analysis',
                    'Simulations',
                    'Documentation',
                ]),
                'hints' => 'FAIR quantifies risk in dollars.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'AUTO-050',
                'section' => 'automation',
                'title' => 'Automated Bug Bounty Triage',
                'description' => 'Automate bug bounty triage.',
                'overview' => 'Bug bounty reports need triage. Automate it.',
                'objectives' => json_encode([
                    'Understand triage',
                    'Set up automation',
                    'Prioritize reports',
                    'Track remediation',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up bug bounty program.',
                    'Automate triage.',
                    'Prioritize.',
                    'Track.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'HackerOne',
                    'Bugcrowd',
                ]),
                'resources' => json_encode([
                    'Bug Bounty Guide',
                ]),
                'deliverables' => json_encode([
                    'Triage setup',
                    'Prioritization',
                    'Tracking',
                    'Documentation',
                ]),
                'hints' => 'Automate the boring parts.',
                'estimated_time' => '6 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
        ];

        foreach ($tasks as $task) {
            $task['created_at'] = now();
            $task['updated_at'] = now();
            DB::table('cyber_tasks')->updateOrInsert(
                ['reference_code' => $task['reference_code']],
                $task
            );
        }

        echo "Phase 11 - Cyber Tasks created!\n";
        echo "Total: " . count($tasks) . " new tasks\n";
        echo "\n🎉 ====================================== 🎉\n";
        echo "   CONGRATULATIONS! 300 TASKS COMPLETE!   \n";
        echo "🎉 ====================================== 🎉\n";
    }
}