<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CyberTasksPhase10Seeder extends Seeder
{
    public function run(): void
    {
        $tasks = [
            // ==================== NETWORK DEFENSE ====================
            [
                'reference_code' => 'NET-DEF-041',
                'section' => 'network_defense',
                'title' => 'Cloud Workload Protection Platform (CWPP)',
                'description' => 'Deploy CWPP for cloud workload security.',
                'overview' => 'Cloud workloads need runtime protection. Deploy CWPP.',
                'objectives' => json_encode([
                    'Understand CWPP',
                    'Set up Sysdig or Falco',
                    'Configure runtime rules',
                    'Detect threats',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Install Falco on K8s.',
                    'Configure runtime rules.',
                    'Simulate attack.',
                    'Detect suspicious activity.',
                    'Set up alerts.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Falco - https://falco.org',
                    'Sysdig - https://sysdig.com',
                    'Aqua Security',
                ]),
                'resources' => json_encode([
                    'CWPP Guide - Gartner',
                    'Falco Documentation',
                ]),
                'deliverables' => json_encode([
                    'CWPP setup',
                    'Detection rules',
                    'Alerts',
                    'Documentation',
                ]),
                'hints' => 'Falco is open-source and powerful.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'NET-DEF-042',
                'section' => 'network_defense',
                'title' => 'Cloud Access Security Broker (CASB)',
                'description' => 'Deploy CASB for cloud app security.',
                'overview' => 'CASB monitors cloud app usage. Deploy it.',
                'objectives' => json_encode([
                    'Understand CASB',
                    'Set up CASB',
                    'Configure policies',
                    'Test with cloud apps',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up CASB (Cloudflare, Zscaler).',
                    'Connect cloud apps.',
                    'Configure DLP policies.',
                    'Monitor usage.',
                    'Test with sanctioned/unsanctioned apps.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Cloudflare CASB - https://www.cloudflare.com',
                    'Zscaler',
                    'Netskope',
                ]),
                'resources' => json_encode([
                    'CASB Guide - Gartner',
                    'CASB Best Practices',
                ]),
                'deliverables' => json_encode([
                    'CASB setup',
                    'Policies',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'CASB is critical for shadow IT.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'NET-DEF-043',
                'section' => 'network_defense',
                'title' => 'eBPF Security Monitoring',
                'description' => 'Use eBPF for advanced security monitoring.',
                'overview' => 'eBPF provides kernel-level visibility. Use it.',
                'objectives' => json_encode([
                    'Understand eBPF',
                    'Set up Tetragon',
                    'Configure monitoring',
                    'Detect anomalies',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Install Tetragon on K8s.',
                    'Configure tracing policies.',
                    'Monitor system calls.',
                    'Detect suspicious behavior.',
                    'Set up alerts.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Tetragon - https://github.com/cilium/tetragon',
                    'Cilium',
                    'bpftrace',
                ]),
                'resources' => json_encode([
                    'eBPF Documentation',
                    'Tetragon Guide',
                ]),
                'deliverables' => json_encode([
                    'Setup',
                    'Policies',
                    'Detections',
                    'Documentation',
                ]),
                'hints' => 'eBPF is the future of security monitoring.',
                'estimated_time' => '7 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'NET-DEF-044',
                'section' => 'network_defense',
                'title' => 'Service Mesh Security',
                'description' => 'Secure service mesh communications.',
                'overview' => 'Service mesh secures microservices. Configure it.',
                'objectives' => json_encode([
                    'Understand service mesh',
                    'Set up Istio',
                    'Configure mTLS',
                    'Set up authorization',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Install Istio.',
                    'Enable mTLS.',
                    'Configure authorization policies.',
                    'Test service-to-service.',
                    'Monitor traffic.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Istio - https://istio.io',
                    'Linkerd',
                    'Consul',
                ]),
                'resources' => json_encode([
                    'Istio Security',
                    'Service Mesh Guide',
                ]),
                'deliverables' => json_encode([
                    'Istio setup',
                    'mTLS config',
                    'Policies',
                    'Documentation',
                ]),
                'hints' => 'mTLS is essential in zero trust.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'NET-DEF-045',
                'section' => 'network_defense',
                'title' => 'Confidential Computing',
                'description' => 'Implement confidential computing for sensitive workloads.',
                'overview' => 'Confidential computing protects data in use. Implement it.',
                'objectives' => json_encode([
                    'Understand confidential computing',
                    'Set up enclave',
                    'Test with sensitive data',
                    'Measure overhead',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Research Intel SGX / AMD SEV.',
                    'Set up test environment.',
                    'Run sensitive workload in enclave.',
                    'Verify protection.',
                    'Measure performance.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Intel SGX',
                    'AMD SEV',
                    'Open Enclave',
                ]),
                'resources' => json_encode([
                    'Confidential Computing Consortium',
                    'SGX Documentation',
                ]),
                'deliverables' => json_encode([
                    'Setup',
                    'Test results',
                    'Performance data',
                    'Documentation',
                ]),
                'hints' => 'Confidential computing is emerging.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== DFIR ====================
            [
                'reference_code' => 'DFIR-041',
                'section' => 'dfir',
                'title' => 'Ransomware Negotiation Strategy',
                'description' => 'Develop a ransomware negotiation strategy.',
                'overview' => 'Negotiation is sensitive. Develop strategy.',
                'objectives' => json_encode([
                    'Understand negotiation',
                    'Assess options',
                    'Plan communication',
                    'Involve stakeholders',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Research ransomware groups.',
                    'Assess pay/no-pay.',
                    'Plan communication.',
                    'Involve legal, PR, insurance.',
                    'Document strategy.',
                ]),
                'tools_list' => json_encode([
                    'Negotiation Frameworks',
                    'Legal Counsel',
                ]),
                'resources' => json_encode([
                    'Ransomware Negotiation - Coveware',
                    'CISA Ransomware Guide',
                ]),
                'deliverables' => json_encode([
                    'Strategy document',
                    'Communication plan',
                    'Stakeholder list',
                    'Documentation',
                ]),
                'hints' => 'Never negotiate alone. Involve experts.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DFIR-042',
                'section' => 'dfir',
                'title' => 'Data Breach Notification Compliance',
                'description' => 'Handle data breach notifications legally.',
                'overview' => 'Breach notification has legal requirements. Comply.',
                'objectives' => json_encode([
                    'Understand notification laws',
                    'Identify requirements',
                    'Prepare notifications',
                    'Coordinate with legal',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Identify applicable laws.',
                    'Determine notification timeline.',
                    'Prepare notification letters.',
                    'Coordinate with legal.',
                    'Notify regulators.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Notification Templates',
                    'Legal Counsel',
                ]),
                'resources' => json_encode([
                    'GDPR Breach Notification',
                    'State Breach Laws',
                ]),
                'deliverables' => json_encode([
                    'Compliance analysis',
                    'Notifications',
                    'Documentation',
                ]),
                'hints' => 'Timelines vary (72 hours for GDPR).',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DFIR-043',
                'section' => 'dfir',
                'title' => 'Insider Threat Investigation',
                'description' => 'Investigate insider threat incidents.',
                'overview' => 'Insider threats are hard to detect. Learn investigation.',
                'objectives' => json_encode([
                    'Understand insider threats',
                    'Detect behavioral anomalies',
                    'Collect evidence',
                    'Coordinate with HR/Legal',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Analyze UEBA alerts.',
                    'Investigate suspicious behavior.',
                    'Collect evidence (emails, files).',
                    'Coordinate with HR/Legal.',
                    'Interview if needed.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'UEBA Tools',
                    'DFIR Tools',
                ]),
                'resources' => json_encode([
                    'Insider Threat - CERT',
                    'Insider Threat Guide',
                ]),
                'deliverables' => json_encode([
                    'Investigation report',
                    'Evidence',
                    'Recommendations',
                    'Documentation',
                ]),
                'hints' => 'Involve HR/Legal from the start.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DFIR-044',
                'section' => 'dfir',
                'title' => 'Nation-State Attack Response',
                'description' => 'Respond to nation-state attacks.',
                'overview' => 'Nation-state attacks are sophisticated. Respond.',
                'objectives' => json_encode([
                    'Understand nation-state TTPs',
                    'Detect advanced threats',
                    'Coordinate with government',
                    'Contain and eradicate',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Analyze TTPs (MITRE).',
                    'Hunt for IOCs.',
                    'Coordinate with CISA/FBI.',
                    'Contain and eradicate.',
                    'Recover.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Threat Intel',
                    'DFIR Tools',
                    'Government Contacts',
                ]),
                'resources' => json_encode([
                    'Nation-State Threats - CISA',
                    'MITRE ATT&CK',
                ]),
                'deliverables' => json_encode([
                    'Investigation',
                    'Government coordination',
                    'Recovery',
                    'Documentation',
                ]),
                'hints' => 'Government coordination is critical.',
                'estimated_time' => '10 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DFIR-045',
                'section' => 'dfir',
                'title' => 'Cyber Insurance Claim Process',
                'description' => 'Handle cyber insurance claims.',
                'overview' => 'Insurance claims need documentation. Handle them.',
                'objectives' => json_encode([
                    'Understand claim process',
                    'Document incident',
                    'Coordinate with insurer',
                    'Provide evidence',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Notify insurer immediately.',
                    'Document all costs.',
                    'Coordinate with adjuster.',
                    'Provide evidence.',
                    'Track claim.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Insurance Documents',
                    'Cost Tracking',
                ]),
                'resources' => json_encode([
                    'Cyber Insurance Claims Guide',
                    'Insurance Best Practices',
                ]),
                'deliverables' => json_encode([
                    'Claim documentation',
                    'Evidence',
                    'Communication log',
                    'Documentation',
                ]),
                'hints' => 'Document everything from day one.',
                'estimated_time' => '6 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== PENTEST ====================
            [
                'reference_code' => 'PT-041',
                'section' => 'pentest',
                'title' => 'Advanced Web Shell Techniques',
                'description' => 'Master advanced web shell techniques.',
                'overview' => 'Web shells are powerful. Master advanced techniques.',
                'objectives' => json_encode([
                    'Understand web shells',
                    'Build custom shells',
                    'Evade detection',
                    'Maintain access',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Research web shell techniques.',
                    'Build custom PHP shell.',
                    'Add obfuscation.',
                    'Test detection evasion.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Weevely - https://github.com/epinna/weevely3',
                    'Custom shells',
                ]),
                'resources' => json_encode([
                    'Web Shell Techniques - SANS',
                    'Weevely Documentation',
                ]),
                'deliverables' => json_encode([
                    'Custom shells',
                    'Evasion methods',
                    'Documentation',
                ]),
                'hints' => 'Only use in authorized tests.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'PT-042',
                'section' => 'pentest',
                'title' => 'Cloud Native Attacks',
                'description' => 'Perform cloud-native attacks.',
                'overview' => 'Cloud-native attacks target containers, K8s, serverless.',
                'objectives' => json_encode([
                    'Understand cloud-native attacks',
                    'Attack containers',
                    'Attack K8s',
                    'Attack serverless',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up K8s lab.',
                    'Attack container escapes.',
                    'Attack K8s API.',
                    'Attack Lambda/serverless.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'kube-hunter - https://github.com/aquasecurity/kube-hunter',
                    'Peirates',
                    'Cloudsplaining',
                ]),
                'resources' => json_encode([
                    'Cloud Native Attacks - NCC Group',
                    'K8s Security',
                ]),
                'deliverables' => json_encode([
                    'Attack proofs',
                    'Vulnerabilities',
                    'Report',
                ]),
                'hints' => 'K8s default config is insecure.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'PT-043',
                'section' => 'pentest',
                'title' => 'Advanced Phishing Evasion',
                'description' => 'Bypass email security with advanced phishing.',
                'overview' => 'Email security blocks basic phishing. Evade it.',
                'objectives' => json_encode([
                    'Understand email security',
                    'Bypass filters',
                    'Evade sandboxes',
                    'Test delivery',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Test SPF/DKIM/DMARC bypasses.',
                    'Use HTML smuggling.',
                    'Test sandbox evasion.',
                    'Test link obfuscation.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'GoPhish',
                    'Evilginx2',
                    'Custom scripts',
                ]),
                'resources' => json_encode([
                    'Phishing Evasion Techniques',
                    'Red Team Phishing',
                ]),
                'deliverables' => json_encode([
                    'Bypass methods',
                    'Delivery results',
                    'Report',
                ]),
                'hints' => 'HTML smuggling is very effective.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'PT-044',
                'section' => 'pentest',
                'title' => 'IoT/OT Pivoting',
                'description' => 'Pivot through IoT/OT devices.',
                'overview' => 'IoT/OT devices are weak entry points. Pivot through them.',
                'objectives' => json_encode([
                    'Understand IoT/OT pivoting',
                    'Compromise IoT device',
                    'Pivot to network',
                    'Reach critical systems',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up IoT/OT lab.',
                    'Compromise IoT device.',
                    'Pivot to internal network.',
                    'Reach critical systems.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Nmap',
                    'Metasploit',
                    'Custom scripts',
                ]),
                'resources' => json_encode([
                    'IoT Pentesting Guide',
                    'OT Security - SANS',
                ]),
                'deliverables' => json_encode([
                    'Pivot proof',
                    'Access proof',
                    'Report',
                ]),
                'hints' => 'IoT devices often lack security.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'PT-045',
                'section' => 'pentest',
                'title' => 'Mainframe Security Assessment',
                'description' => 'Assess mainframe security.',
                'overview' => 'Mainframes are still critical. Assess their security.',
                'objectives' => json_encode([
                    'Understand mainframe security',
                    'Enumerate services',
                    'Test access controls',
                    'Document findings',
                    'Report',
                ]),
                'instructions' => json_encode([
                    'Research z/OS security.',
                    'Enumerate services.',
                    'Test RACF controls.',
                    'Assess access.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'z/OS Tools',
                    'Nmap',
                ]),
                'resources' => json_encode([
                    'Mainframe Security - IBM',
                    'z/OS Security Guide',
                ]),
                'deliverables' => json_encode([
                    'Assessment',
                    'Findings',
                    'Report',
                ]),
                'hints' => 'Mainframe is a niche but critical area.',
                'estimated_time' => '10 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== DEVSECOPS ====================
            [
                'reference_code' => 'DEVSEC-041',
                'section' => 'devsecops',
                'title' => 'Secure Kubernetes Operators',
                'description' => 'Secure Kubernetes operators.',
                'overview' => 'Operators have high privileges. Secure them.',
                'objectives' => json_encode([
                    'Understand operators',
                    'Review operator security',
                    'Apply least privilege',
                    'Monitor operator actions',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Review operator code.',
                    'Check RBAC permissions.',
                    'Apply least privilege.',
                    'Monitor actions.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Kubernetes',
                    'kube-bench',
                    'OPA',
                ]),
                'resources' => json_encode([
                    'Operator Security Guide',
                    'K8s Security Best Practices',
                ]),
                'deliverables' => json_encode([
                    'Review',
                    'Improved RBAC',
                    'Monitoring',
                    'Documentation',
                ]),
                'hints' => 'Operators can do anything K8s can.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DEVSEC-042',
                'section' => 'devsecops',
                'title' => 'Serverless Security',
                'description' => 'Secure serverless applications.',
                'overview' => 'Serverless has unique risks. Secure them.',
                'objectives' => json_encode([
                    'Understand serverless security',
                    'Review function permissions',
                    'Secure secrets',
                    'Monitor invocations',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Review Lambda permissions.',
                    'Apply least privilege.',
                    'Secure env variables.',
                    'Monitor with CloudWatch.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'AWS Lambda',
                    'Serverless Framework',
                    'AWS X-Ray',
                ]),
                'resources' => json_encode([
                    'Serverless Security - OWASP',
                    'AWS Lambda Security',
                ]),
                'deliverables' => json_encode([
                    'Permission review',
                    'Hardening',
                    'Monitoring',
                    'Documentation',
                ]),
                'hints' => 'Functions often have excessive permissions.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DEVSEC-043',
                'section' => 'devsecops',
                'title' => 'Database Security Hardening',
                'description' => 'Harden database security.',
                'overview' => 'Databases are critical. Harden them.',
                'objectives' => json_encode([
                    'Understand DB hardening',
                    'Review configurations',
                    'Apply CIS benchmarks',
                    'Encrypt data',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Review current config.',
                    'Apply CIS benchmark.',
                    'Enable encryption.',
                    'Restrict access.',
                    'Audit logging.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'CIS Benchmarks',
                    'Database audit tools',
                ]),
                'resources' => json_encode([
                    'CIS Database Benchmarks',
                    'Database Security Guide',
                ]),
                'deliverables' => json_encode([
                    'Hardening report',
                    'Config changes',
                    'Documentation',
                ]),
                'hints' => 'CIS benchmarks are excellent starting points.',
                'estimated_time' => '6 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DEVSEC-044',
                'section' => 'devsecops',
                'title' => 'Zero Trust for APIs',
                'description' => 'Implement Zero Trust for APIs.',
                'overview' => 'APIs need Zero Trust. Implement it.',
                'objectives' => json_encode([
                    'Understand ZT for APIs',
                    'Implement authentication',
                    'Configure mTLS',
                    'Add rate limiting',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Configure OAuth2/OIDC.',
                    'Enable mTLS.',
                    'Configure rate limits.',
                    'Add request signing.',
                    'Monitor.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Keycloak',
                    'OAuth2 Proxy',
                    'Kong',
                ]),
                'resources' => json_encode([
                    'API Zero Trust',
                    'OWASP API Security',
                ]),
                'deliverables' => json_encode([
                    'API security config',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'Every API call should be authenticated.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DEVSEC-045',
                'section' => 'devsecops',
                'title' => 'DevSecOps Culture Transformation',
                'description' => 'Transform culture to DevSecOps.',
                'overview' => 'Tools alone do not secure. Culture matters.',
                'objectives' => json_encode([
                    'Understand culture change',
                    'Assess current culture',
                    'Plan transformation',
                    'Implement changes',
                    'Measure progress',
                ]),
                'instructions' => json_encode([
                    'Assess current culture.',
                    'Identify champions.',
                    'Pilot changes.',
                    'Scale successful practices.',
                    'Measure progress.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Surveys',
                    'Confluence',
                ]),
                'resources' => json_encode([
                    'DevSecOps Culture - Google',
                    'Accelerate (Book)',
                ]),
                'deliverables' => json_encode([
                    'Assessment',
                    'Transformation plan',
                    'Pilot results',
                    'Documentation',
                ]),
                'hints' => 'Culture change takes time. Be patient.',
                'estimated_time' => '10 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== GRC ====================
            [
                'reference_code' => 'GRC-041',
                'section' => 'grc',
                'title' => 'Security Program Business Case',
                'description' => 'Build a business case for security investment.',
                'overview' => 'Security needs investment. Build a business case.',
                'objectives' => json_encode([
                    'Understand business cases',
                    'Identify needs',
                    'Quantify risks',
                    'Build ROI',
                    'Present',
                ]),
                'instructions' => json_encode([
                    'Identify security gaps.',
                    'Quantify financial impact.',
                    'Estimate investment.',
                    'Build ROI.',
                    'Present to executives.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Excel',
                    'Business Case Templates',
                ]),
                'resources' => json_encode([
                    'Security Business Case - Gartner',
                    'FAIR Methodology',
                ]),
                'deliverables' => json_encode([
                    'Business case',
                    'ROI analysis',
                    'Presentation',
                    'Documentation',
                ]),
                'hints' => 'FAIR quantifies risk in dollars.',
                'estimated_time' => '7 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'GRC-042',
                'section' => 'grc',
                'title' => 'Third-Party Breach Response',
                'description' => 'Respond to third-party breaches.',
                'overview' => 'Your vendors can be breached. Respond effectively.',
                'objectives' => json_encode([
                    'Understand vendor breaches',
                    'Detect impact',
                    'Coordinate with vendor',
                    'Notify stakeholders',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Monitor vendor notifications.',
                    'Assess impact on your org.',
                    'Coordinate with vendor.',
                    'Notify affected parties.',
                    'Update contracts.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Vendor Monitoring',
                    'Legal Counsel',
                ]),
                'resources' => json_encode([
                    'Third-Party Breach Response',
                    'Vendor Risk Management',
                ]),
                'deliverables' => json_encode([
                    'Impact analysis',
                    'Coordination records',
                    'Notifications',
                    'Documentation',
                ]),
                'hints' => 'Know your vendor dependencies.',
                'estimated_time' => '6 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'GRC-043',
                'section' => 'grc',
                'title' => 'Privacy Impact Assessment (PIA)',
                'description' => 'Conduct a Privacy Impact Assessment.',
                'overview' => 'New systems need PIA. Conduct it.',
                'objectives' => json_encode([
                    'Understand PIA',
                    'Assess privacy risks',
                    'Document findings',
                    'Mitigate risks',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Understand PIA requirements.',
                    'Assess data collection.',
                    'Assess data usage.',
                    'Identify privacy risks.',
                    'Mitigate.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'PIA Templates',
                    'OneTrust',
                ]),
                'resources' => json_encode([
                    'PIA Guide - ICO',
                    'Privacy by Design',
                ]),
                'deliverables' => json_encode([
                    'PIA',
                    'Mitigations',
                    'Documentation',
                ]),
                'hints' => 'PIA is required for GDPR compliance.',
                'estimated_time' => '6 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'GRC-044',
                'section' => 'grc',
                'title' => 'Security Awareness Program Measurement',
                'description' => 'Measure awareness program effectiveness.',
                'overview' => 'Awareness programs need measurement. Measure them.',
                'objectives' => json_encode([
                    'Understand measurement',
                    'Define metrics',
                    'Collect data',
                    'Analyze trends',
                    'Improve program',
                ]),
                'instructions' => json_encode([
                    'Define metrics (click rate, report rate).',
                    'Collect baseline.',
                    'Run campaigns.',
                    'Measure changes.',
                    'Improve program.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'KnowBe4',
                    'Excel',
                ]),
                'resources' => json_encode([
                    'Awareness Measurement - SANS',
                    'Metrics Guide',
                ]),
                'deliverables' => json_encode([
                    'Metrics',
                    'Trends',
                    'Improvements',
                    'Documentation',
                ]),
                'hints' => 'Measure behavior, not knowledge.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'GRC-045',
                'section' => 'grc',
                'title' => 'Security Program Roadmap',
                'description' => 'Build a multi-year security roadmap.',
                'overview' => 'Security needs long-term planning. Build a roadmap.',
                'objectives' => json_encode([
                    'Understand roadmapping',
                    'Assess current state',
                    'Define target state',
                    'Build phased plan',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Assess current maturity.',
                    'Define target maturity.',
                    'Identify gaps.',
                    'Build 3-year roadmap.',
                    'Get buy-in.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Roadmap Tools',
                    'Excel',
                ]),
                'resources' => json_encode([
                    'Security Roadmap - Gartner',
                    'Strategic Planning',
                ]),
                'deliverables' => json_encode([
                    'Roadmap',
                    'Budget',
                    'Stakeholder buy-in',
                    'Documentation',
                ]),
                'hints' => 'Roadmap should align with business goals.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== AUTOMATION ====================
            [
                'reference_code' => 'AUTO-041',
                'section' => 'automation',
                'title' => 'Automated Cloud Cost Security',
                'description' => 'Monitor and secure cloud costs.',
                'overview' => 'Cloud costs can be attacked. Monitor costs.',
                'objectives' => json_encode([
                    'Understand cost security',
                    'Set up monitoring',
                    'Detect anomalies',
                    'Alert on spikes',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Enable cost monitoring.',
                    'Set up budgets.',
                    'Detect anomalies.',
                    'Alert on spikes.',
                    'Investigate.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'AWS Cost Explorer',
                    'CloudHealth',
                ]),
                'resources' => json_encode([
                    'Cloud Cost Security',
                    'FinOps Guide',
                ]),
                'deliverables' => json_encode([
                    'Monitoring setup',
                    'Alerts',
                    'Documentation',
                ]),
                'hints' => 'Crypto mining shows as cost spikes.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'AUTO-042',
                'section' => 'automation',
                'title' => 'Automated Secrets Rotation',
                'description' => 'Automate secrets rotation.',
                'overview' => 'Static secrets are risky. Rotate automatically.',
                'objectives' => json_encode([
                    'Understand rotation',
                    'Set up Vault',
                    'Configure rotation',
                    'Test rotation',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up Vault.',
                    'Configure DB secrets.',
                    'Enable auto-rotation.',
                    'Test rotation.',
                    'Monitor.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'HashiCorp Vault',
                    'AWS Secrets Manager',
                ]),
                'resources' => json_encode([
                    'Vault Rotation Guide',
                    'Secrets Management',
                ]),
                'deliverables' => json_encode([
                    'Vault setup',
                    'Rotation config',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'Rotate database credentials frequently.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'AUTO-043',
                'section' => 'automation',
                'title' => 'Automated Security Testing in CI/CD',
                'description' => 'Automate security testing in pipelines.',
                'overview' => 'Security tests should be automated.',
                'objectives' => json_encode([
                    'Understand security testing',
                    'Set up pipeline',
                    'Integrate multiple tools',
                    'Configure gates',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up CI/CD pipeline.',
                    'Integrate SAST, DAST, SCA.',
                    'Configure quality gates.',
                    'Test with vulnerable code.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'GitLab CI / GitHub Actions',
                    'SonarQube, ZAP, Snyk',
                ]),
                'resources' => json_encode([
                    'DevSecOps Pipeline Guide',
                    'OWASP CI/CD',
                ]),
                'deliverables' => json_encode([
                    'Pipeline config',
                    'Tool integration',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'Fail builds on critical issues.',
                'estimated_time' => '7 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'AUTO-044',
                'section' => 'automation',
                'title' => 'Automated Incident Response Orchestration',
                'description' => 'Orchestrate incident response.',
                'overview' => 'Manual IR is slow. Orchestrate it.',
                'objectives' => json_encode([
                    'Understand orchestration',
                    'Set up SOAR',
                    'Build workflows',
                    'Test playbooks',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up Shuffle or n8n.',
                    'Build phishing playbook.',
                    'Add enrichment, notification, containment.',
                    'Test with simulated incident.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Shuffle - https://shuffler.io',
                    'n8n',
                    'TheHive',
                ]),
                'resources' => json_encode([
                    'SOAR Guide - Gartner',
                    'Shuffle Documentation',
                ]),
                'deliverables' => json_encode([
                    'SOAR setup',
                    'Playbooks',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'Start with the most common incident.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'AUTO-045',
                'section' => 'automation',
                'title' => 'Automated Security Awareness Delivery',
                'description' => 'Automate security awareness delivery.',
                'overview' => 'Awareness needs automation. Deliver it automatically.',
                'objectives' => json_encode([
                    'Understand automation',
                    'Set up LMS',
                    'Automate delivery',
                    'Track completion',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up LMS (Moodle).',
                    'Create course content.',
                    'Automate enrollment.',
                    'Track completion.',
                    'Send reminders.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Moodle - https://moodle.org',
                    'KnowBe4',
                ]),
                'resources' => json_encode([
                    'LMS Automation',
                    'Awareness Delivery Guide',
                ]),
                'deliverables' => json_encode([
                    'LMS setup',
                    'Course content',
                    'Tracking',
                    'Documentation',
                ]),
                'hints' => 'Automate reminders. Do not nag manually.',
                'estimated_time' => '6 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
        ];

        foreach ($tasks as $task) {
            $task['created_at'] = now();
            $task['updated_at'] = now();
            DB::table('cyber_tasks')->updateOrInsert(
                ['reference_code' => $task['reference_code']],
                $task
            );
        }

        echo "Phase 10 - Cyber Tasks created!\n";
        echo "Total: " . count($tasks) . " new tasks\n";
    }
}