<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CyberTasksPhase6Seeder extends Seeder
{
    public function run(): void
    {
        $tasks = [
            // ==================== NETWORK DEFENSE (5 new) ====================
            [
                'reference_code' => 'NET-DEF-021',
                'section' => 'network_defense',
                'title' => 'Next-Generation Firewall (NGFW) Configuration',
                'description' => 'Configure a next-gen firewall with application awareness.',
                'overview' => 'NGFWs inspect traffic at application layer. Configure one.',
                'objectives' => json_encode([
                    'Understand NGFW features',
                    'Set up pfSense with Suricata',
                    'Configure application control',
                    'Set up SSL inspection',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Install pfSense with Suricata package.',
                    'Configure application detection.',
                    'Block high-risk apps (Tor, P2P).',
                    'Set up SSL/TLS inspection.',
                    'Create exception lists.',
                    'Test with various applications.',
                    'Document rules.',
                ]),
                'tools_list' => json_encode([
                    'pfSense - https://www.pfsense.org',
                    'OPNsense - https://opnsense.org',
                    'Suricata - https://suricata.io',
                ]),
                'resources' => json_encode([
                    'NGFW Best Practices',
                    'Suricata Documentation',
                ]),
                'deliverables' => json_encode([
                    'NGFW config',
                    'Application rules',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'SSL inspection breaks some apps. Start with exceptions.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'NET-DEF-022',
                'section' => 'network_defense',
                'title' => 'Network Traffic Baselining',
                'description' => 'Establish a baseline for normal network traffic.',
                'overview' => 'You cannot detect anomalies without a baseline. Establish one.',
                'objectives' => json_encode([
                    'Understand baselining',
                    'Capture normal traffic',
                    'Analyze patterns',
                    'Document baseline',
                    'Set up anomaly detection',
                ]),
                'instructions' => json_encode([
                    'Set up monitoring on network (Zeek/Suricata).',
                    'Capture traffic for 1 week.',
                    'Analyze protocols, ports, volumes.',
                    'Create baseline profile.',
                    'Set up alerts for deviations.',
                    'Test with simulated anomaly.',
                    'Document baseline.',
                ]),
                'tools_list' => json_encode([
                    'Zeek - https://zeek.org',
                    'Suricata - https://suricata.io',
                    'ELK Stack - https://www.elastic.co',
                ]),
                'resources' => json_encode([
                    'Network Baselining - SANS',
                    'Zeek Documentation',
                ]),
                'deliverables' => json_encode([
                    'Traffic captures',
                    'Baseline profile',
                    'Anomaly detection rules',
                    'Documentation',
                ]),
                'hints' => 'Baseline changes over time. Update quarterly.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'NET-DEF-023',
                'section' => 'network_defense',
                'title' => 'Software-Defined Perimeter (SDP)',
                'description' => 'Set up a Software-Defined Perimeter for Zero Trust.',
                'overview' => 'SDP hides resources from unauthorized users. Set it up.',
                'objectives' => json_encode([
                    'Understand SDP',
                    'Set up OpenZiti',
                    'Configure identity-based access',
                    'Test access controls',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Install OpenZiti.',
                    'Define services.',
                    'Configure identities.',
                    'Set up policies.',
                    'Test access from different identities.',
                    'Verify hidden from unauthorized.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'OpenZiti - https://openziti.io',
                    'Cloudflare Access - https://www.cloudflare.com',
                ]),
                'resources' => json_encode([
                    'SDP - Cloud Security Alliance',
                    'OpenZiti Documentation',
                ]),
                'deliverables' => json_encode([
                    'SDP setup',
                    'Access policies',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'SDP is the future of network security.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'NET-DEF-024',
                'section' => 'network_defense',
                'title' => 'BGP Security (RPKI)',
                'description' => 'Implement RPKI to prevent BGP hijacking.',
                'overview' => 'BGP is insecure. RPKI adds validation.',
                'objectives' => json_encode([
                    'Understand BGP security',
                    'Set up RPKI validation',
                    'Configure routers',
                    'Test with invalid routes',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up BGP lab (GNS3, FRR).',
                    'Create ROAs for your prefixes.',
                    'Configure RPKI validator.',
                    'Enable validation on routers.',
                    'Test with invalid announcement.',
                    'Verify rejection.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'FRRouting - https://frrouting.org',
                    'Routinator - https://nlnetlabs.nl',
                    'GNS3 - https://www.gns3.com',
                ]),
                'resources' => json_encode([
                    'RPKI Documentation - APNIC',
                    'BGP Security - NIST',
                ]),
                'deliverables' => json_encode([
                    'BGP lab',
                    'RPKI config',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'RPKI prevents route hijacking. Essential for ISPs.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'NET-DEF-025',
                'section' => 'network_defense',
                'title' => 'Network Forensics Capture Setup',
                'description' => 'Set up continuous network forensics capture.',
                'overview' => 'You cannot investigate what you did not capture. Set up capture.',
                'objectives' => json_encode([
                    'Understand capture architecture',
                    'Set up full packet capture',
                    'Configure retention',
                    'Set up indexing',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up dedicated capture server.',
                    'Configure port mirroring (SPAN).',
                    'Install Arkime or Moloch.',
                    'Configure retention (e.g., 30 days).',
                    'Set up indexing for search.',
                    'Test retrieval of old sessions.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Arkime - https://arkime.com',
                    'Moloch',
                    'Stenographer - https://github.com/google/stenographer',
                ]),
                'resources' => json_encode([
                    'Network Forensics - SANS',
                    'Arkime Documentation',
                ]),
                'deliverables' => json_encode([
                    'Capture setup',
                    'Retention policy',
                    'Search interface',
                    'Documentation',
                ]),
                'hints' => 'Storage is the biggest cost. Plan carefully.',
                'estimated_time' => '7 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== DFIR (5 new) ====================
            [
                'reference_code' => 'DFIR-021',
                'section' => 'dfir',
                'title' => 'Memory Forensics with Volatility Plugins',
                'description' => 'Use advanced Volatility plugins for deep analysis.',
                'overview' => 'Volatility has many plugins. Master the advanced ones.',
                'objectives' => json_encode([
                    'Understand plugin categories',
                    'Use advanced plugins',
                    'Extract hidden artifacts',
                    'Correlate findings',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Get a memory dump.',
                    'Run plugins: psscan, dlllist, handles, callbacks.',
                    'Analyze: svcscan, scheduled_tasks, shimcache.',
                    'Extract: cmdline, envars, getsids.',
                    'Run: yarascan for IOCs.',
                    'Correlate findings.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Volatility 3 - https://github.com/volatilityfoundation/volatility3',
                    'Volatility Workbench',
                ]),
                'resources' => json_encode([
                    'Volatility Plugin Reference',
                    'The Art of Memory Forensics (Book)',
                ]),
                'deliverables' => json_encode([
                    'Plugin outputs',
                    'Hidden artifacts',
                    'IOC list',
                    'Report',
                ]),
                'hints' => 'psscan finds hidden processes that pslist misses.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DFIR-022',
                'section' => 'dfir',
                'title' => 'Cloud Forensics (Azure)',
                'description' => 'Perform forensic investigation in Azure.',
                'overview' => 'Azure forensics is different from AWS. Learn it.',
                'objectives' => json_encode([
                    'Understand Azure logging',
                    'Analyze Activity Logs',
                    'Investigate Azure AD',
                    'Analyze NSG Flow Logs',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up Azure account with activity.',
                    'Enable Activity Log export.',
                    'Analyze sign-in logs.',
                    'Investigate suspicious sign-ins.',
                    'Review NSG Flow Logs.',
                    'Check Azure AD audit logs.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Azure Monitor',
                    'Azure Sentinel',
                    'Azure AD Logs',
                ]),
                'resources' => json_encode([
                    'Azure Security Documentation',
                    'Cloud Forensics - SANS',
                ]),
                'deliverables' => json_encode([
                    'Log analysis',
                    'Investigation report',
                    'Timeline',
                    'Documentation',
                ]),
                'hints' => 'Azure AD logs are crucial for identity investigations.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DFIR-023',
                'section' => 'dfir',
                'title' => 'macOS Forensics',
                'description' => 'Perform forensic investigation on macOS.',
                'overview' => 'macOS has unique artifacts. Learn them.',
                'objectives' => json_encode([
                    'Understand macOS structure',
                    'Analyze Unified Logs',
                    'Extract user artifacts',
                    'Analyze APFS',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Get macOS disk image.',
                    'Mount with APFS support.',
                    'Analyze Unified Logs.',
                    'Extract Safari history, Downloads.',
                    'Check Login Items, LaunchAgents.',
                    'Analyze Time Machine.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Autopsy - https://www.autopsy.com',
                    'mac_apt - https://github.com/ydkhatri/mac_apt',
                    'APFS FUSE',
                ]),
                'resources' => json_encode([
                    'macOS Forensics Guide',
                    'SANS macOS Forensics',
                ]),
                'deliverables' => json_encode([
                    'Log analysis',
                    'User artifacts',
                    'Timeline',
                    'Report',
                ]),
                'hints' => 'Unified Logs replaced many older log files.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DFIR-024',
                'section' => 'dfir',
                'title' => 'Disk Encryption Forensics',
                'description' => 'Analyze encrypted disks and volumes.',
                'overview' => 'Encryption complicates forensics. Learn techniques.',
                'objectives' => json_encode([
                    'Understand encryption types',
                    'Acquire encrypted image',
                    'Attempt recovery',
                    'Analyze metadata',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up BitLocker/LUKS disk.',
                    'Acquire image without keys.',
                    'Analyze metadata, headers.',
                    'Try recovery keys (if available).',
                    'Mount decrypted volume.',
                    'Extract artifacts.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Autopsy - https://www.autopsy.com',
                    'Dislocker - https://github.com/Aorimn/dislocker',
                    'Cryptsetup',
                ]),
                'resources' => json_encode([
                    'Encryption Forensics Guide',
                    'BitLocker Forensics - SANS',
                ]),
                'deliverables' => json_encode([
                    'Recovery methods',
                    'Extracted data',
                    'Metadata analysis',
                    'Documentation',
                ]),
                'hints' => 'Always look for recovery keys in AD or Azure.',
                'estimated_time' => '5 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DFIR-025',
                'section' => 'dfir',
                'title' => 'Incident Response Plan Execution',
                'description' => 'Execute a full incident response plan.',
                'overview' => 'Practice executing your IR plan end-to-end.',
                'objectives' => json_encode([
                    'Follow IR plan',
                    'Coordinate team',
                    'Document every step',
                    'Communicate effectively',
                    'Write after-action report',
                ]),
                'instructions' => json_encode([
                    'Set up IR plan.',
                    'Simulate incident (ransomware or phishing).',
                    'Execute: detect, contain, eradicate, recover.',
                    'Document each step.',
                    'Run team communications.',
                    'Post-incident review.',
                    'Write after-action report.',
                ]),
                'tools_list' => json_encode([
                    'IR Plan Templates - SANS',
                    'Communication Tools',
                    'Ticketing System',
                ]),
                'resources' => json_encode([
                    'NIST IR Framework',
                    'SANS Incident Handler Handbook',
                ]),
                'deliverables' => json_encode([
                    'Incident log',
                    'Communication records',
                    'After-action report',
                    'Lessons learned',
                ]),
                'hints' => 'Document as you go, not after.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== PENTEST (5 new) ====================
            [
                'reference_code' => 'PT-021',
                'section' => 'pentest',
                'title' => 'Web Shell Detection & Analysis',
                'description' => 'Detect and analyze web shells on compromised servers.',
                'overview' => 'Web shells are common post-exploitation. Learn to detect.',
                'objectives' => json_encode([
                    'Understand web shells',
                    'Detect common shells',
                    'Analyze shell code',
                    'Remove safely',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Deploy test web shell (China Chopper).',
                    'Detect via file monitoring.',
                    'Analyze shell code.',
                    'Check logs for access.',
                    'Remove shell.',
                    'Patch vulnerability.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'YARA - https://virustotal.github.io/yara',
                    'NeoPI - https://github.com/irsdl/NeoPI',
                    'Grep',
                ]),
                'resources' => json_encode([
                    'Web Shell Detection - SANS',
                    'YARA Rules for Web Shells',
                ]),
                'deliverables' => json_encode([
                    'Detection methods',
                    'Analysis notes',
                    'Removal process',
                    'Report',
                ]),
                'hints' => 'Look for eval(), base64_decode(), system() in PHP files.',
                'estimated_time' => '4 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'PT-022',
                'section' => 'pentest',
                'title' => 'Kerberos Attacks (Kerberoasting)',
                'description' => 'Perform Kerberoasting attack against AD.',
                'overview' => 'Kerberoasting cracks service account passwords. Learn it.',
                'objectives' => json_encode([
                    'Understand Kerberos',
                    'Request service tickets',
                    'Extract and crack hashes',
                    'Escalate privileges',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up AD lab.',
                    'Create service account with SPN.',
                    'Use Rubeus or GetUserSPNs.',
                    'Request service tickets.',
                    'Extract hashes.',
                    'Crack with Hashcat.',
                    'Use credentials for escalation.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Rubeus - https://github.com/GhostPack/Rubeus',
                    'Impacket - https://github.com/SecureAuthCorp/impacket',
                    'Hashcat - https://hashcat.net',
                ]),
                'resources' => json_encode([
                    'Kerberoasting - Harmj0y',
                    'AD Security - adsecurity.org',
                ]),
                'deliverables' => json_encode([
                    'Requested tickets',
                    'Cracked passwords',
                    'Escalation proof',
                    'Report',
                ]),
                'hints' => 'Service accounts often have weak passwords.',
                'estimated_time' => '5 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'PT-023',
                'section' => 'pentest',
                'title' => 'Web Cache Poisoning',
                'description' => 'Perform web cache poisoning attacks.',
                'overview' => 'Cache poisoning affects all users. Learn it.',
                'objectives' => json_encode([
                    'Understand cache poisoning',
                    'Identify cacheable endpoints',
                    'Test unkeyed headers',
                    'Poison cache',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Identify target with caching.',
                    'Test unkeyed headers (X-Forwarded-Host).',
                    'Test cache deception.',
                    'Craft poisoning payload.',
                    'Verify poisoning.',
                    'Document impact.',
                    'Recommend fixes.',
                ]),
                'tools_list' => json_encode([
                    'Burp Suite - https://portswigger.net/burp',
                    'Param Miner - Burp Extension',
                ]),
                'resources' => json_encode([
                    'Web Cache Poisoning - PortSwigger',
                    'Cache Poisoning Research',
                ]),
                'deliverables' => json_encode([
                    'Poisoning proof',
                    'Impact analysis',
                    'Report',
                    'Recommendations',
                ]),
                'hints' => 'X-Forwarded-Host is a common unkeyed header.',
                'estimated_time' => '5 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'PT-024',
                'section' => 'pentest',
                'title' => 'Subdomain Takeover',
                'description' => 'Find and exploit subdomain takeovers.',
                'overview' => 'Dangling DNS records allow subdomain takeover.',
                'objectives' => json_encode([
                    'Enumerate subdomains',
                    'Identify dangling records',
                    'Claim subdomain',
                    'Document impact',
                    'Recommend fixes',
                ]),
                'instructions' => json_encode([
                    'Enumerate subdomains (Amass, Subfinder).',
                    'Check each for takeover.',
                    'Use subjack or can-i-take-over-xyz.',
                    'Verify vulnerability.',
                    'Claim a subdomain (test).',
                    'Document.',
                    'Recommend DNS cleanup.',
                ]),
                'tools_list' => json_encode([
                    'Amass - https://github.com/OWASP/Amass',
                    'Subfinder - https://github.com/projectdiscovery/subfinder',
                    'Subjack - https://github.com/haccer/subjack',
                ]),
                'resources' => json_encode([
                    'Can I Take Over XYZ - https://github.com/EdOverflow/can-i-take-over-xyz',
                ]),
                'deliverables' => json_encode([
                    'Subdomain list',
                    'Vulnerable subdomains',
                    'Takeover proof',
                    'Report',
                ]),
                'hints' => 'Common with S3, GitHub Pages, Heroku.',
                'estimated_time' => '4 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'PT-025',
                'section' => 'pentest',
                'title' => 'Server-Side Template Injection (SSTI)',
                'description' => 'Exploit Server-Side Template Injection.',
                'overview' => 'SSTI can lead to RCE. Learn to exploit it.',
                'objectives' => json_encode([
                    'Understand SSTI',
                    'Identify template engines',
                    'Exploit Jinja2/Twig',
                    'Achieve RCE',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up vulnerable app (Flask with Jinja2).',
                    'Test payloads: {{7*7}}.',
                    'Identify engine.',
                                        "Exploit: {{config}}, {{''.__class__}}.",
                    'Achieve RCE.',
                    'Document payloads.',
                    'Recommend fixes.',
                ]),
                'tools_list' => json_encode([
                    'tplmap - https://github.com/epinna/tplmap',
                    'Burp Suite',
                    'PayloadsAllTheThings - https://github.com/swisskyrepo/PayloadsAllTheThings',
                ]),
                'resources' => json_encode([
                    'SSTI Guide - PortSwigger',
                    'PayloadsAllTheThings - SSTI',
                ]),
                'deliverables' => json_encode([
                    'Identified engine',
                    'Exploit payloads',
                    'RCE proof',
                    'Report',
                ]),
                'hints' => 'SSTI is often missed. Look for user input in templates.',
                'estimated_time' => '5 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== DEVSECOPS (5 new) ====================
            [
                'reference_code' => 'DEVSEC-021',
                'section' => 'devsecops',
                'title' => 'Blue/Green Deployment Security',
                'description' => 'Secure blue/green deployments.',
                'overview' => 'Blue/green deployments reduce risk. Secure them.',
                'objectives' => json_encode([
                    'Understand blue/green',
                    'Set up deployment',
                    'Secure transition',
                    'Enable rollback',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up blue and green environments.',
                    'Configure load balancer.',
                    'Test deployment to green.',
                    'Verify with smoke tests.',
                    'Switch traffic.',
                    'Test rollback.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'AWS CodeDeploy',
                    'Kubernetes',
                    'Nginx',
                ]),
                'resources' => json_encode([
                    'Blue/Green Best Practices',
                    'AWS CodeDeploy Docs',
                ]),
                'deliverables' => json_encode([
                    'Deployment config',
                    'Test results',
                    'Rollback procedure',
                    'Documentation',
                ]),
                'hints' => 'Always test rollback before deploying.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DEVSEC-022',
                'section' => 'devsecops',
                'title' => 'API Schema Validation',
                'description' => 'Implement strict API schema validation.',
                'overview' => 'Schema validation prevents injection. Implement it.',
                'objectives' => json_encode([
                    'Understand schema validation',
                    'Define OpenAPI schema',
                    'Implement validation',
                    'Test invalid inputs',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Write OpenAPI schema.',
                    'Integrate validator (express-validator, pydantic).',
                    'Enforce types, lengths, patterns.',
                    'Reject invalid requests.',
                    'Test with malformed input.',
                    'Log rejections.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'OpenAPI - https://www.openapis.org',
                    'express-validator - https://express-validator.github.io',
                    'Pydantic - https://pydantic-docs.helpmanual.io',
                ]),
                'resources' => json_encode([
                    'OWASP API Security',
                    'OpenAPI Specification',
                ]),
                'deliverables' => json_encode([
                    'Schema definition',
                    'Validation code',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'Always validate on server-side, not just client.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DEVSEC-023',
                'section' => 'devsecops',
                'title' => 'Penetration Testing as Code',
                'description' => 'Automate penetration testing in CI/CD.',
                'overview' => 'Manual pentests are slow. Automate parts.',
                'objectives' => json_encode([
                    'Understand automated pentest',
                    'Set up Nuclei',
                    'Write custom templates',
                    'Integrate into CI/CD',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Install Nuclei.',
                    'Run default templates.',
                    'Write custom templates for app.',
                    'Integrate into CI/CD.',
                    'Configure thresholds.',
                    'Generate reports.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Nuclei - https://github.com/projectdiscovery/nuclei',
                    'OWASP ZAP',
                    'Burp Enterprise',
                ]),
                'resources' => json_encode([
                    'Nuclei Documentation',
                    'Automated Pentesting Guide',
                ]),
                'deliverables' => json_encode([
                    'Nuclei setup',
                    'Custom templates',
                    'CI/CD integration',
                    'Documentation',
                ]),
                'hints' => 'Nuclei is fast and has thousands of templates.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DEVSEC-024',
                'section' => 'devsecops',
                'title' => 'Security Metrics Dashboard',
                'description' => 'Build a security metrics dashboard for DevOps.',
                'overview' => 'DevOps teams need security metrics. Build a dashboard.',
                'objectives' => json_encode([
                    'Define DevOps security metrics',
                    'Set up data collection',
                    'Build dashboard',
                    'Automate updates',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Define metrics: vulns found/fixed, time to patch, SAST/DAST pass rate.',
                    'Collect from tools (SonarQube, Snyk).',
                    'Send to Grafana.',
                    'Create panels.',
                    'Set up alerts.',
                    'Share with team.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Grafana - https://grafana.com',
                    'SonarQube - https://www.sonarqube.org',
                    'Snyk - https://snyk.io',
                ]),
                'resources' => json_encode([
                    'DevSecOps Metrics - DORA',
                    'Grafana Documentation',
                ]),
                'deliverables' => json_encode([
                    'Metrics definition',
                    'Dashboard',
                    'Automation',
                    'Documentation',
                ]),
                'hints' => 'Focus on actionable metrics.',
                'estimated_time' => '6 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DEVSEC-025',
                'section' => 'devsecops',
                'title' => 'Chaos Engineering for Security',
                'description' => 'Apply chaos engineering to test security resilience.',
                'overview' => 'Chaos engineering tests resilience. Apply to security.',
                'objectives' => json_encode([
                    'Understand chaos engineering',
                    'Set up Chaos Toolkit',
                    'Design security experiments',
                    'Run experiments',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Install Chaos Toolkit.',
                    'Define experiment: kill auth service.',
                    'Run experiment.',
                    'Observe system behavior.',
                    'Test security controls under stress.',
                    'Document findings.',
                    'Improve resilience.',
                ]),
                'tools_list' => json_encode([
                    'Chaos Toolkit - https://chaostoolkit.org',
                    'Gremlin - https://www.gremlin.com',
                    'Litmus - https://litmuschaos.io',
                ]),
                'resources' => json_encode([
                    'Chaos Engineering (Book)',
                    'Principles of Chaos',
                ]),
                'deliverables' => json_encode([
                    'Experiment definitions',
                    'Results',
                    'Improvements',
                    'Documentation',
                ]),
                'hints' => 'Start small. Chaos engineering can break things.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== GRC (5 new) ====================
            [
                'reference_code' => 'GRC-021',
                'section' => 'grc',
                'title' => 'Security Culture Assessment',
                'description' => 'Assess and improve security culture.',
                'overview' => 'Security culture drives behavior. Assess it.',
                'objectives' => json_encode([
                    'Understand security culture',
                    'Assess current state',
                    'Identify gaps',
                    'Design interventions',
                    'Measure improvement',
                ]),
                'instructions' => json_encode([
                    'Use surveys (Security Culture Framework).',
                    'Conduct interviews.',
                    'Analyze results.',
                    'Identify weak areas.',
                    'Design interventions.',
                    'Re-assess after 6 months.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'SurveyMonkey',
                    'Security Culture Framework - https://securitycultureframework.net',
                ]),
                'resources' => json_encode([
                    'Security Culture - Kai Roer',
                    'SANS Security Culture',
                ]),
                'deliverables' => json_encode([
                    'Assessment report',
                    'Gap analysis',
                    'Intervention plan',
                    'Metrics',
                ]),
                'hints' => 'Culture eats strategy for breakfast.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'GRC-022',
                'section' => 'grc',
                'title' => 'Vendor Security Questionnaire',
                'description' => 'Create and use a vendor security questionnaire.',
                'overview' => 'Vendors need security assessment. Create a questionnaire.',
                'objectives' => json_encode([
                    'Understand vendor assessment',
                    'Design questionnaire',
                    'Send to vendors',
                    'Analyze responses',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Design questionnaire (SIG Lite).',
                    'Include: security controls, incident history, compliance.',
                    'Send to top vendors.',
                    'Review responses.',
                    'Score each vendor.',
                    'Identify high-risk vendors.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'SIG Questionnaire - https://sharedassessments.org',
                    'Excel',
                ]),
                'resources' => json_encode([
                    'SIG Lite',
                    'Vendor Risk Management - SANS',
                ]),
                'deliverables' => json_encode([
                    'Questionnaire',
                    'Responses',
                    'Risk scores',
                    'Report',
                ]),
                'hints' => 'SIG Lite is free and widely accepted.',
                'estimated_time' => '6 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'GRC-023',
                'section' => 'grc',
                'title' => 'Security Awareness Training Program',
                'description' => 'Develop a comprehensive security awareness program.',
                'overview' => 'Awareness is continuous. Develop a program.',
                'objectives' => json_encode([
                    'Understand awareness best practices',
                    'Design curriculum',
                    'Implement program',
                    'Measure effectiveness',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Assess current awareness.',
                    'Design curriculum (monthly topics).',
                    'Create content (videos, quizzes).',
                    'Schedule training.',
                    'Run phishing simulations.',
                    'Measure improvement.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'KnowBe4 - https://www.knowbe4.com',
                    'Proofpoint - https://www.proofpoint.com',
                    'LMS (Moodle)',
                ]),
                'resources' => json_encode([
                    'SANS Awareness Program',
                    'NIST Awareness Guide',
                ]),
                'deliverables' => json_encode([
                    'Program plan',
                    'Content',
                    'Metrics',
                    'Documentation',
                ]),
                'hints' => 'Short, frequent training beats long sessions.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'GRC-024',
                'section' => 'grc',
                'title' => 'Regulatory Compliance Mapping',
                'description' => 'Map controls to multiple regulations.',
                'overview' => 'Multiple regulations apply. Map them.',
                'objectives' => json_encode([
                    'Identify applicable regulations',
                    'Map controls',
                    'Find overlaps',
                    'Document compliance',
                    'Simplify reporting',
                ]),
                'instructions' => json_encode([
                    'List applicable regulations (GDPR, HIPAA, PCI).',
                    'Map controls for each.',
                    'Identify overlapping controls.',
                    'Create unified control matrix.',
                    'Simplify compliance reporting.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Compliance Mapping Tools',
                    'Excel',
                ]),
                'resources' => json_encode([
                    'NIST Compliance Guide',
                    'Unified Compliance Framework - https://www.unifiedcompliance.com',
                ]),
                'deliverables' => json_encode([
                    'Regulation list',
                    'Control matrix',
                    'Overlap analysis',
                    'Documentation',
                ]),
                'hints' => 'Many regulations overlap. Map once, comply many.',
                'estimated_time' => '7 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'GRC-025',
                'section' => 'grc',
                'title' => 'Business Continuity Testing',
                'description' => 'Test business continuity plans.',
                'overview' => 'BCP must be tested. Test it.',
                'objectives' => json_encode([
                    'Understand BCP testing',
                    'Design test scenarios',
                    'Execute tests',
                    'Document results',
                    'Improve plans',
                ]),
                'instructions' => json_encode([
                    'Choose test type: tabletop, simulation, full.',
                    'Design scenarios (natural disaster, cyber).',
                    'Execute with stakeholders.',
                    'Document decisions.',
                    'Identify gaps.',
                    'Update BCP.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'BCP Testing Templates',
                    'Tabletop Kits',
                ]),
                'resources' => json_encode([
                    'ISO 22301 Testing',
                    'FEMA Exercise Guide',
                ]),
                'deliverables' => json_encode([
                    'Test plan',
                    'Execution log',
                    'Gap analysis',
                    'Updated BCP',
                ]),
                'hints' => 'Test annually at minimum.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== AUTOMATION (5 new) ====================
            [
                'reference_code' => 'AUTO-021',
                'section' => 'automation',
                'title' => 'Automated Firewall Rule Deployment',
                'description' => 'Automate firewall rule deployment with IaC.',
                'overview' => 'Manual firewall changes are risky. Automate.',
                'objectives' => json_encode([
                    'Understand IaC for firewalls',
                    'Set up Terraform for pfSense',
                    'Define rules as code',
                    'Test deployment',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Install Terraform.',
                    'Get pfSense provider.',
                    'Write rule definitions.',
                    'Run terraform plan.',
                    'Apply rules.',
                    'Test connectivity.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Terraform - https://www.terraform.io',
                    'pfSense Provider',
                    'Ansible',
                ]),
                'resources' => json_encode([
                    'Terraform Documentation',
                    'Infrastructure as Code - Kief Morris',
                ]),
                'deliverables' => json_encode([
                    'Terraform config',
                    'Deployment results',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'Always run plan before apply.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'AUTO-022',
                'section' => 'automation',
                'title' => 'Automated User Behavior Analytics',
                'description' => 'Set up UEBA for anomaly detection.',
                'overview' => 'UEBA detects insider threats. Set it up.',
                'objectives' => json_encode([
                    'Understand UEBA',
                    'Collect user data',
                    'Set up baselines',
                    'Detect anomalies',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Collect: login, file access, email.',
                    'Set up Elasticsearch.',
                    'Create baseline models.',
                    'Configure anomaly detection.',
                    'Test with simulated behavior.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Elasticsearch - https://www.elastic.co',
                    'Splunk UBA',
                    'Microsoft Sentinel',
                ]),
                'resources' => json_encode([
                    'UEBA Guide - Gartner',
                    'Elastic ML',
                ]),
                'deliverables' => json_encode([
                    'Data collection',
                    'Baseline',
                    'Anomaly rules',
                    'Documentation',
                ]),
                'hints' => 'Start with login anomalies. Expand over time.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'AUTO-023',
                'section' => 'automation',
                'title' => 'Automated Vulnerability Remediation',
                'description' => 'Automate vulnerability remediation with Ansible.',
                'overview' => 'Manual patching does not scale. Automate.',
                'objectives' => json_encode([
                    'Understand automated remediation',
                    'Set up Ansible',
                    'Create playbooks',
                    'Test in lab',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Install Ansible.',
                    'Create inventory.',
                    'Write patch playbook.',
                    'Test on lab systems.',
                    'Deploy to production (staged).',
                    'Track remediation.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Ansible - https://www.ansible.com',
                    'Red Hat Satellite',
                    'Tanium',
                ]),
                'resources' => json_encode([
                    'Ansible Documentation',
                    'Patch Management Best Practices',
                ]),
                'deliverables' => json_encode([
                    'Playbooks',
                    'Test results',
                    'Production deployment',
                    'Documentation',
                ]),
                'hints' => 'Test playbooks on non-production first.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'AUTO-024',
                'section' => 'automation',
                'title' => 'Automated Threat Feed Integration',
                'description' => 'Integrate threat feeds into security tools.',
                'overview' => 'Threat feeds need integration. Automate it.',
                'objectives' => json_encode([
                    'Identify feeds',
                    'Set up integration',
                    'Automate updates',
                    'Test detection',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Choose feeds (AlienVault, MISP).',
                    'Set up collection.',
                    'Push to firewall, SIEM.',
                    'Configure auto-updates.',
                    'Test with known IOCs.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'MISP - https://www.misp-project.org',
                    'AlienVault OTX - https://otx.alienvault.com',
                    'TheHive',
                ]),
                'resources' => json_encode([
                    'Threat Intel Integration - SANS',
                    'MISP Documentation',
                ]),
                'deliverables' => json_encode([
                    'Feed integration',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'Do not block based on low-confidence feeds.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'AUTO-025',
                'section' => 'automation',
                'title' => 'Automated Security Awareness Testing',
                'description' => 'Automate security awareness testing.',
                'overview' => 'Awareness testing should be continuous. Automate.',
                'objectives' => json_encode([
                    'Understand automated testing',
                    'Set up phishing automation',
                    'Track metrics',
                    'Report automatically',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up GoPhish.',
                    'Create templates library.',
                    'Schedule campaigns.',
                    'Track click rates.',
                    'Auto-generate reports.',
                    'Trigger training for failures.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'GoPhish - https://getgophish.com',
                    'KnowBe4',
                    'LMS',
                ]),
                'resources' => json_encode([
                    'GoPhish Documentation',
                    'Awareness Metrics - SANS',
                ]),
                'deliverables' => json_encode([
                    'Automation setup',
                    'Campaign results',
                    'Reports',
                    'Documentation',
                ]),
                'hints' => 'Rotate templates. Avoid habituation.',
                'estimated_time' => '6 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
        ];

        foreach ($tasks as $task) {
            $task['created_at'] = now();
            $task['updated_at'] = now();
            DB::table('cyber_tasks')->updateOrInsert(
                ['reference_code' => $task['reference_code']],
                $task
            );
        }

        echo "Phase 6 - Cyber Tasks created!\n";
        echo "Total: " . count($tasks) . " new tasks\n";
        echo "  - Network Defense: 5\n";
        echo "  - DFIR: 5\n";
        echo "  - Pentest: 5\n";
        echo "  - DevSecOps: 5\n";
        echo "  - GRC: 5\n";
        echo "  - Automation: 5\n";
    }
}