<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CyberTasksPhase5Seeder extends Seeder
{
    public function run(): void
    {
        $tasks = [
            // ==================== NETWORK DEFENSE (5 new) ====================
            [
                'reference_code' => 'NET-DEF-016',
                'section' => 'network_defense',
                'title' => 'Email Security Gateway Configuration',
                'description' => 'Configure an email security gateway to filter spam, phishing, and malware.',
                'overview' => 'Email is the #1 attack vector. Configure a gateway to filter threats before they reach users.',
                'objectives' => json_encode([
                    'Understand email security layers',
                    'Set up SPF, DKIM, DMARC',
                    'Configure spam filtering',
                    'Set up attachment sandboxing',
                    'Test with simulated attacks',
                ]),
                'instructions' => json_encode([
                    'Choose gateway: Proxmox Mail Gateway or Mailcow.',
                    'Set up on a Linux VM.',
                    'Configure SPF, DKIM, DMARC for your domain.',
                    'Enable spam filtering (SpamAssassin).',
                    'Configure attachment scanning (ClamAV).',
                    'Set up URL rewriting and sandboxing.',
                    'Test with EICAR and phishing samples.',
                    'Document configuration.',
                ]),
                'tools_list' => json_encode([
                    'Proxmox Mail Gateway - https://www.proxmox.com',
                    'Mailcow - https://mailcow.email',
                    'SpamAssassin - https://spamassassin.apache.org',
                    'ClamAV - https://www.clamav.net',
                ]),
                'resources' => json_encode([
                    'DMARC Guide - https://dmarc.org',
                    'Email Security Best Practices - SANS',
                ]),
                'deliverables' => json_encode([
                    'Gateway configuration',
                    'SPF/DKIM/DMARC records',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'DMARC is essential. Set it to "quarantine" first, then "reject".',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'NET-DEF-017',
                'section' => 'network_defense',
                'title' => 'SD-WAN Security Assessment',
                'description' => 'Assess security of SD-WAN deployment.',
                'overview' => 'SD-WAN changes network security. Assess it.',
                'objectives' => json_encode([
                    'Understand SD-WAN architecture',
                    'Identify security risks',
                    'Test encryption',
                    'Verify segmentation',
                    'Document findings',
                ]),
                'instructions' => json_encode([
                    'Set up SD-WAN lab (OpenWrt or VyOS).',
                    'Configure multiple WAN links.',
                    'Enable encryption (IPsec).',
                    'Configure segmentation between sites.',
                    'Test failover.',
                    'Verify encryption with Wireshark.',
                    'Document security posture.',
                ]),
                'tools_list' => json_encode([
                    'VyOS - https://vyos.io',
                    'OpenWrt - https://openwrt.org',
                    'Wireshark - https://www.wireshark.org',
                ]),
                'resources' => json_encode([
                    'SD-WAN Security - NIST',
                    'SD-WAN Best Practices - Cisco',
                ]),
                'deliverables' => json_encode([
                    'SD-WAN setup',
                    'Encryption verification',
                    'Test results',
                    'Report',
                ]),
                'hints' => 'SD-WAN often bypasses traditional security. Segment carefully.',
                'estimated_time' => '5 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'NET-DEF-018',
                'section' => 'network_defense',
                'title' => 'IoT Device Security Assessment',
                'description' => 'Assess security of IoT devices on the network.',
                'overview' => 'IoT devices are often insecure. Assess and secure them.',
                'objectives' => json_encode([
                    'Inventory IoT devices',
                    'Identify vulnerabilities',
                    'Test for default credentials',
                    'Set up network isolation',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Scan network for IoT devices.',
                    'Identify device types (cameras, printers, etc.).',
                    'Check for default credentials.',
                    'Run vulnerability scan.',
                    'Set up isolated VLAN for IoT.',
                    'Restrict IoT network access.',
                    'Document inventory and risks.',
                ]),
                'tools_list' => json_encode([
                    'Nmap - https://nmap.org',
                    'Shodan - https://shodan.io',
                    'OpenVAS - https://www.openvas.org',
                ]),
                'resources' => json_encode([
                    'IoT Security Foundation',
                    'OWASP IoT Top 10',
                ]),
                'deliverables' => json_encode([
                    'IoT inventory',
                    'Vulnerability report',
                    'Network isolation',
                    'Documentation',
                ]),
                'hints' => 'IoT devices should never be on the same VLAN as workstations.',
                'estimated_time' => '4 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'NET-DEF-019',
                'section' => 'network_defense',
                'title' => 'DDoS Mitigation Strategy',
                'description' => 'Design and test a DDoS mitigation strategy.',
                'overview' => 'DDoS attacks can take down services. Design mitigation.',
                'objectives' => json_encode([
                    'Understand DDoS types',
                    'Set up rate limiting',
                    'Configure CDN protection',
                    'Set up auto-scaling',
                    'Test with simulated attack',
                ]),
                'instructions' => json_encode([
                    'Set up a web service (Nginx).',
                    'Configure rate limiting.',
                    'Set up Cloudflare or AWS Shield.',
                    'Configure auto-scaling.',
                    'Simulate DDoS with hping3 or LOIC.',
                    'Verify mitigation works.',
                    'Document strategy.',
                ]),
                'tools_list' => json_encode([
                    'Cloudflare - https://www.cloudflare.com',
                    'AWS Shield - https://aws.amazon.com/shield',
                    'hping3 - https://github.com/antirez/hping',
                ]),
                'resources' => json_encode([
                    'DDoS Mitigation - Cloudflare',
                    'NIST DDoS Guide',
                ]),
                'deliverables' => json_encode([
                    'Mitigation setup',
                    'Test results',
                    'Documentation',
                    'Cost analysis',
                ]),
                'hints' => 'Cloudflare Free Tier offers basic DDoS protection.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'NET-DEF-020',
                'section' => 'network_defense',
                'title' => 'Network Access Control with RADIUS',
                'description' => 'Set up RADIUS for centralized network authentication.',
                'overview' => 'RADIUS centralizes authentication. Set it up.',
                'objectives' => json_encode([
                    'Understand RADIUS',
                    'Set up FreeRADIUS',
                    'Configure 802.1X',
                    'Integrate with AD',
                    'Test authentication',
                ]),
                'instructions' => json_encode([
                    'Install FreeRADIUS on Linux.',
                    'Configure with test users.',
                    'Set up EAP-TLS.',
                    'Integrate with Active Directory.',
                    'Configure a test switch for 802.1X.',
                    'Test authentication.',
                    'Document setup.',
                ]),
                'tools_list' => json_encode([
                    'FreeRADIUS - https://freeradius.org',
                    'PacketFence - https://packetfence.org',
                    'Cisco ISE',
                ]),
                'resources' => json_encode([
                    'FreeRADIUS Documentation',
                    '802.1X Deployment Guide',
                ]),
                'deliverables' => json_encode([
                    'RADIUS configuration',
                    'Test results',
                    'Integration proof',
                    'Documentation',
                ]),
                'hints' => 'EAP-TLS requires client certificates. Set up a CA first.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== DFIR (5 new) ====================
            [
                'reference_code' => 'DFIR-016',
                'section' => 'dfir',
                'title' => 'Live Response with Velociraptor',
                'description' => 'Use Velociraptor for live incident response.',
                'overview' => 'Live response is critical during incidents. Learn Velociraptor.',
                'objectives' => json_encode([
                    'Understand live response',
                    'Deploy Velociraptor',
                    'Collect artifacts remotely',
                    'Analyze findings',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up Velociraptor server.',
                    'Deploy agents on test VMs.',
                    'Create collection: processes, network, registry.',
                    'Run on live systems.',
                    'Analyze results in UI.',
                    'Export artifacts.',
                    'Document workflow.',
                ]),
                'tools_list' => json_encode([
                    'Velociraptor - https://docs.velociraptor.app',
                    'GRR - https://github.com/google/grr',
                    'osquery - https://osquery.io',
                ]),
                'resources' => json_encode([
                    'Velociraptor Documentation',
                    'SANS Live Response',
                ]),
                'deliverables' => json_encode([
                    'Velociraptor setup',
                    'Collection artifacts',
                    'Analysis notes',
                    'Documentation',
                ]),
                'hints' => 'Velociraptor is powerful and free.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DFIR-017',
                'section' => 'dfir',
                'title' => 'USB Device Forensics',
                'description' => 'Analyze USB device history and artifacts.',
                'overview' => 'USB devices leave traces. Learn to analyze them.',
                'objectives' => json_encode([
                    'Understand USB artifacts',
                    'Extract USB history',
                    'Analyze SetupAPI logs',
                    'Track file transfers',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Get a Windows image with USB activity.',
                    'Analyze SetupAPI.dev.log.',
                    'Extract USB history from Registry.',
                    'Use USBDeview for analysis.',
                    'Check for file transfers.',
                    'Correlate with timeline.',
                    'Document findings.',
                ]),
                'tools_list' => json_encode([
                    'USBDeview - https://www.nirsoft.net/utils/usb_devices_view.html',
                    'Autopsy - https://www.autopsy.com',
                    'RegRipper - https://github.com/keydet89/RegRipper3.0',
                ]),
                'resources' => json_encode([
                    'USB Forensics Guide',
                    'SANS USB Forensics',
                ]),
                'deliverables' => json_encode([
                    'USB history',
                    'File transfer evidence',
                    'Timeline',
                    'Report',
                ]),
                'hints' => 'SetupAPI.dev.log is a goldmine for USB forensics.',
                'estimated_time' => '4 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DFIR-018',
                'section' => 'dfir',
                'title' => 'PowerShell Logging Analysis',
                'description' => 'Analyze PowerShell logs for malicious activity.',
                'overview' => 'Attackers abuse PowerShell. Learn to analyze logs.',
                'objectives' => json_encode([
                    'Enable PowerShell logging',
                    'Analyze ScriptBlock logs',
                    'Detect obfuscation',
                    'Extract IOCs',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Enable PowerShell logging (GPO).',
                    'Generate malicious activity (Empire).',
                    'Analyze Event ID 4104 (ScriptBlock).',
                    'Look for: Base64 encoding, downloads, AMSI bypass.',
                    'Use PSDecode to decode obfuscated.',
                    'Extract IOCs.',
                    'Document findings.',
                ]),
                'tools_list' => json_encode([
                    'PSDecode - https://github.com/R3MRUM/PSDecode',
                    'Event Viewer',
                    'PowerShell Empire - https://github.com/BC-SECURITY/Empire',
                ]),
                'resources' => json_encode([
                    'PowerShell Logging Guide - Microsoft',
                    'SANS PowerShell Forensics',
                ]),
                'deliverables' => json_encode([
                    'Log analysis',
                    'Decoded scripts',
                    'IOC list',
                    'Report',
                ]),
                'hints' => 'Event ID 4104 contains all script blocks.',
                'estimated_time' => '4 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DFIR-019',
                'section' => 'dfir',
                'title' => 'Ransomware Response Simulation',
                'description' => 'Simulate a full ransomware incident response.',
                'overview' => 'Practice the full ransomware response workflow.',
                'objectives' => json_encode([
                    'Detect ransomware',
                    'Isolate affected systems',
                    'Preserve evidence',
                    'Restore from backup',
                    'Write after-action report',
                ]),
                'instructions' => json_encode([
                    'Set up test environment with backups.',
                    'Simulate ransomware (safe simulation).',
                    'Detect via monitoring.',
                    'Isolate affected systems.',
                    'Preserve memory and disk.',
                    'Restore from backup.',
                    'Write after-action report.',
                ]),
                'tools_list' => json_encode([
                    'VirtualBox - https://www.virtualbox.org',
                    'Backup Software',
                    'Velociraptor - https://docs.velociraptor.app',
                ]),
                'resources' => json_encode([
                    'NIST Ransomware Guide',
                    'CISA Ransomware Guide',
                ]),
                'deliverables' => json_encode([
                    'Response timeline',
                    'Evidence collection',
                    'Restoration proof',
                    'After-action report',
                ]),
                'hints' => 'Never run real ransomware. Use simulators.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DFIR-020',
                'section' => 'dfir',
                'title' => 'Chain of Custody Documentation',
                'description' => 'Document chain of custody for digital evidence.',
                'overview' => 'Legal cases require chain of custody. Learn to document.',
                'objectives' => json_encode([
                    'Understand chain of custody',
                    'Create documentation form',
                    'Practice evidence handling',
                    'Maintain integrity',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Get sample evidence (USB, disk).',
                    'Create chain of custody form.',
                    'Document: who, what, when, where.',
                    'Photograph and hash evidence.',
                    'Transfer to secure storage.',
                    'Maintain log throughout.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Chain of Custody Templates',
                    'HashCalc - https://www.slavasoft.com/hashcalc',
                ]),
                'resources' => json_encode([
                    'NIST Chain of Custody Guide',
                    'SWGDE Standards',
                ]),
                'deliverables' => json_encode([
                    'Chain of custody form',
                    'Hashes',
                    'Photographs',
                    'Documentation',
                ]),
                'hints' => 'Hash every piece of evidence. Keep original.',
                'estimated_time' => '3 hours',
                'difficulty' => 3,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== PENTEST (5 new) ====================
            [
                'reference_code' => 'PT-016',
                'section' => 'pentest',
                'title' => 'Password Cracking with Hashcat',
                'description' => 'Crack password hashes with Hashcat.',
                'overview' => 'Password cracking is essential. Learn Hashcat.',
                'objectives' => json_encode([
                    'Understand hash types',
                    'Set up Hashcat',
                    'Use wordlists',
                    'Use rules and masks',
                    'Document techniques',
                ]),
                'instructions' => json_encode([
                    'Install Hashcat.',
                    'Get sample hashes (NTLM, SHA1).',
                    'Crack with rockyou.txt.',
                    'Apply rules (best64.rule).',
                    'Use mask attack for patterns.',
                    'Try hybrid attack.',
                    'Document successful methods.',
                ]),
                'tools_list' => json_encode([
                    'Hashcat - https://hashcat.net',
                    'John the Ripper - https://www.openwall.com/john',
                    'rockyou.txt',
                ]),
                'resources' => json_encode([
                    'Hashcat Documentation',
                    'Password Cracking Guide',
                ]),
                'deliverables' => json_encode([
                    'Cracked passwords',
                    'Methods used',
                    'Time analysis',
                    'Documentation',
                ]),
                'hints' => 'Rules can dramatically improve success rate.',
                'estimated_time' => '4 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'PT-017',
                'section' => 'pentest',
                'title' => 'Post-Exploitation Enumeration',
                'description' => 'Perform post-exploitation enumeration on Windows.',
                'overview' => 'After access, enumerate to escalate. Learn techniques.',
                'objectives' => json_encode([
                    'Understand post-exploitation',
                    'Enumerate system info',
                    'Enumerate user data',
                    'Find credentials',
                    'Document findings',
                ]),
                'instructions' => json_encode([
                    'Get initial access to Windows VM.',
                    'Run systeminfo, whoami /priv.',
                    'Enumerate network, users, groups.',
                    'Search for credentials in files, registry.',
                    'Use Mimikatz for credential extraction.',
                    'Check for shares, sessions.',
                    'Document findings.',
                ]),
                'tools_list' => json_encode([
                    'Mimikatz - https://github.com/gentilkiwi/mimikatz',
                    'Seatbelt - https://github.com/GhostPack/Seatbelt',
                    'SharpUp - https://github.com/GhostPack/SharpUp',
                ]),
                'resources' => json_encode([
                    'Post-Exploitation Guide - HackTricks',
                    'Windows Privilege Escalation',
                ]),
                'deliverables' => json_encode([
                    'Enumeration output',
                    'Credential list',
                    'Attack paths',
                    'Report',
                ]),
                'hints' => 'Mimikatz is powerful but often flagged by AV.',
                'estimated_time' => '5 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'PT-018',
                'section' => 'pentest',
                'title' => 'Burp Suite Advanced Techniques',
                'description' => 'Master advanced Burp Suite features.',
                'overview' => 'Burp is essential for web pentesting. Master it.',
                'objectives' => json_encode([
                    'Use Intruder effectively',
                    'Use Repeater',
                    'Set up macros',
                    'Use extensions',
                    'Document techniques',
                ]),
                'instructions' => json_encode([
                    'Set up DVWA with Burp.',
                    'Test Intruder: Sniper, Cluster bomb.',
                    'Use Repeater for manual testing.',
                    'Set up macro for CSRF token handling.',
                    'Install extensions (Logger++, Turbo Intruder).',
                    'Practice on PortSwigger labs.',
                    'Document techniques.',
                ]),
                'tools_list' => json_encode([
                    'Burp Suite - https://portswigger.net/burp',
                    'PortSwigger Academy - https://portswigger.net/web-security',
                ]),
                'resources' => json_encode([
                    'Burp Documentation',
                    'PortSwigger Academy',
                ]),
                'deliverables' => json_encode([
                    'Burp configurations',
                    'Intruder attacks',
                    'Extension usage',
                    'Documentation',
                ]),
                'hints' => 'PortSwigger Academy is free and excellent.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'PT-019',
                'section' => 'pentest',
                'title' => 'Phishing with Evilginx2',
                'description' => 'Perform advanced phishing with Evilginx2.',
                'overview' => 'Evilginx2 bypasses 2FA. Learn advanced phishing.',
                'objectives' => json_encode([
                    'Understand reverse proxy phishing',
                    'Set up Evilginx2',
                    'Configure phishlet',
                    'Bypass 2FA',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Install Evilginx2.',
                    'Get domain and SSL.',
                    'Configure phishlet (e.g., Gmail).',
                    'Set up DNS.',
                    'Test phishing attack.',
                    'Capture credentials and session.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Evilginx2 - https://github.com/kgretzky/evilginx2',
                    'GoPhish - https://getgophish.com',
                ]),
                'resources' => json_encode([
                    'Evilginx2 Documentation',
                    'Reverse Proxy Phishing Guide',
                ]),
                'deliverables' => json_encode([
                    'Evilginx setup',
                    'Phishlet config',
                    'Attack proof',
                    'Report',
                ]),
                'hints' => 'Only test with written authorization.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'PT-020',
                'section' => 'pentest',
                'title' => 'Internal Network Pivoting',
                'description' => 'Pivot through compromised hosts to reach internal networks.',
                'overview' => 'Pivoting expands access. Learn techniques.',
                'objectives' => json_encode([
                    'Understand pivoting',
                    'Set up port forwarding',
                    'Use SSH tunneling',
                    'Use Metasploit autoroute',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up multi-network lab.',
                    'Compromise DMZ host.',
                    'Set up SSH tunnel to internal.',
                    'Use proxychains with Nmap.',
                    'Set up Metasploit autoroute.',
                    'Scan internal network.',
                    'Document pivoting chain.',
                ]),
                'tools_list' => json_encode([
                    'SSH - https://www.openssh.com',
                    'proxychains - https://github.com/haad/proxychains',
                    'Metasploit - https://www.metasploit.com',
                    'Chisel - https://github.com/jpillora/chisel',
                ]),
                'resources' => json_encode([
                    'Pivoting Guide - HackTricks',
                    'Network Pivoting - SANS',
                ]),
                'deliverables' => json_encode([
                    'Pivot setup',
                    'Internal scan results',
                    'Attack path',
                    'Documentation',
                ]),
                'hints' => 'Chisel is simpler than SSH tunneling for complex pivots.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== DEVSECOPS (5 new) ====================
            [
                'reference_code' => 'DEVSEC-016',
                'section' => 'devsecops',
                'title' => 'Security Champions Program',
                'description' => 'Establish a security champions program.',
                'overview' => 'Security champions scale security. Establish a program.',
                'objectives' => json_encode([
                    'Understand champions program',
                    'Identify champions',
                    'Define roles',
                    'Set up training',
                    'Measure success',
                ]),
                'instructions' => json_encode([
                    'Research champions programs.',
                    'Identify potential champions.',
                    'Define roles and responsibilities.',
                    'Set up training curriculum.',
                    'Launch program.',
                    'Measure engagement.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Confluence',
                    'Slack / Teams',
                    'Training Platforms',
                ]),
                'resources' => json_encode([
                    'Security Champions Playbook - OWASP',
                    'Champions Program - Security Journey',
                ]),
                'deliverables' => json_encode([
                    'Program definition',
                    'Champion list',
                    'Training plan',
                    'Metrics',
                ]),
                'hints' => 'Start with 1-2 champions. Scale gradually.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DEVSEC-017',
                'section' => 'devsecops',
                'title' => 'Secure Feature Flags',
                'description' => 'Implement secure feature flag management.',
                'overview' => 'Feature flags control production. Secure them.',
                'objectives' => json_encode([
                    'Understand feature flags',
                    'Set up LaunchDarkly or Unleash',
                    'Configure access controls',
                    'Audit flag changes',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up Unleash or LaunchDarkly.',
                    'Integrate with app.',
                    'Configure RBAC for flag management.',
                    'Set up audit logging.',
                    'Test flag changes.',
                    'Document governance.',
                ]),
                'tools_list' => json_encode([
                    'Unleash - https://www.getunleash.io',
                    'LaunchDarkly - https://launchdarkly.com',
                    'Flagsmith - https://flagsmith.com',
                ]),
                'resources' => json_encode([
                    'Feature Flag Best Practices',
                    'Unleash Documentation',
                ]),
                'deliverables' => json_encode([
                    'Flag setup',
                    'RBAC config',
                    'Audit logs',
                    'Documentation',
                ]),
                'hints' => 'Never expose flags to unauthorized users.',
                'estimated_time' => '4 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DEVSEC-018',
                'section' => 'devsecops',
                'title' => 'Dependency Confusion Defense',
                'description' => 'Defend against dependency confusion attacks.',
                'overview' => 'Dependency confusion attacks target internal packages. Defend.',
                'objectives' => json_encode([
                    'Understand dependency confusion',
                    'Identify internal packages',
                    'Set up private registry',
                    'Configure scoped packages',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Identify internal packages.',
                    'Set up private registry (Nexus, Artifactory).',
                    'Configure scoped packages (@company/*).',
                    'Set up registry priority.',
                    'Test with simulated attack.',
                    'Document defense.',
                ]),
                'tools_list' => json_encode([
                    'Nexus Repository - https://www.sonatype.com/nexus-repository',
                    'Artifactory - https://jfrog.com/artifactory',
                    'Verdaccio - https://verdaccio.org',
                ]),
                'resources' => json_encode([
                    'Dependency Confusion - Alex Birsan',
                    'NPM Security Best Practices',
                ]),
                'deliverables' => json_encode([
                    'Private registry',
                    'Scoped config',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'Always use scoped packages for internal code.',
                'estimated_time' => '5 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DEVSEC-019',
                'section' => 'devsecops',
                'title' => 'Runtime Application Self-Protection (RASP)',
                'description' => 'Implement RASP for runtime protection.',
                'overview' => 'RASP protects apps at runtime. Implement it.',
                'objectives' => json_encode([
                    'Understand RASP',
                    'Set up open-source RASP',
                    'Configure rules',
                    'Test detection',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Choose RASP: OpenRASP or Sqreen.',
                    'Integrate with test app.',
                    'Configure detection rules.',
                    'Test with OWASP attacks.',
                    'Verify detection and blocking.',
                    'Monitor performance impact.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'OpenRASP - https://github.com/baidu/openrasp',
                    'Contrast Security - https://www.contrastsecurity.com',
                    'Sqreen - https://snyk.io',
                ]),
                'resources' => json_encode([
                    'RASP Guide - Gartner',
                    'OpenRASP Documentation',
                ]),
                'deliverables' => json_encode([
                    'RASP setup',
                    'Detection rules',
                    'Test results',
                    'Documentation',
                ]),
                'hints' => 'RASP has performance impact. Test carefully.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DEVSEC-020',
                'section' => 'devsecops',
                'title' => 'API Versioning Security',
                'description' => 'Secure API versioning to prevent attacks.',
                'overview' => 'Old API versions are security risks. Manage them.',
                'objectives' => json_encode([
                    'Understand API versioning',
                    'Design secure versioning',
                    'Deprecate old versions',
                    'Monitor usage',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Review current API versions.',
                    'Design versioning strategy.',
                    'Deprecate old versions.',
                    'Set up monitoring.',
                    'Communicate to consumers.',
                    'Test end-of-life process.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Postman - https://www.postman.com',
                    'Kong - https://konghq.com',
                    'AWS API Gateway',
                ]),
                'resources' => json_encode([
                    'API Versioning Best Practices',
                    'OWASP API Security',
                ]),
                'deliverables' => json_encode([
                    'Versioning strategy',
                    'Deprecation plan',
                    'Monitoring setup',
                    'Documentation',
                ]),
                'hints' => 'Deprecated versions should be shut down, not just ignored.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== GRC (5 new) ====================
            [
                'reference_code' => 'GRC-016',
                'section' => 'grc',
                'title' => 'Data Retention Policy',
                'description' => 'Create a data retention and disposal policy.',
                'overview' => 'Data retention is a legal requirement. Create policy.',
                'objectives' => json_encode([
                    'Understand retention requirements',
                    'Classify data',
                    'Define retention periods',
                    'Document disposal procedures',
                    'Train employees',
                ]),
                'instructions' => json_encode([
                    'Identify regulatory requirements.',
                    'Classify data by type.',
                    'Define retention periods.',
                    'Document disposal procedures.',
                    'Create policy document.',
                    'Train employees.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Word / Confluence',
                    'Data Retention Templates',
                ]),
                'resources' => json_encode([
                    'GDPR Retention Guidelines',
                    'ISO 27001 Retention',
                ]),
                'deliverables' => json_encode([
                    'Retention policy',
                    'Data classification',
                    'Disposal procedures',
                    'Training materials',
                ]),
                'hints' => 'Legal requirements vary by jurisdiction.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'GRC-017',
                'section' => 'grc',
                'title' => 'Insider Threat Program',
                'description' => 'Establish an insider threat program.',
                'overview' => 'Insiders are a top risk. Establish a program.',
                'objectives' => json_encode([
                    'Understand insider threats',
                    'Identify risk indicators',
                    'Set up monitoring',
                    'Define response',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Research insider threat indicators.',
                    'Set up UEBA monitoring.',
                    'Define escalation process.',
                    'Create response plan.',
                    'Train HR and managers.',
                    'Document program.',
                ]),
                'tools_list' => json_encode([
                    'Microsoft Sentinel - https://azure.microsoft.com',
                    'Splunk UBA',
                    'DTEX - https://www.dtexsystems.com',
                ]),
                'resources' => json_encode([
                    'CERT Insider Threat Guide',
                    'NIST Insider Threat',
                ]),
                'deliverables' => json_encode([
                    'Program definition',
                    'Monitoring setup',
                    'Response plan',
                    'Documentation',
                ]),
                'hints' => 'Balance monitoring with privacy. Consult legal.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'GRC-018',
                'section' => 'grc',
                'title' => 'Security Governance Structure',
                'description' => 'Establish a security governance structure.',
                'overview' => 'Governance aligns security with business. Establish it.',
                'objectives' => json_encode([
                    'Understand governance models',
                    'Define roles (CISO, steering committee)',
                    'Set up reporting lines',
                    'Define decision rights',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Research governance models.',
                    'Define roles and responsibilities.',
                    'Set up steering committee.',
                    'Define meeting cadence.',
                    'Document governance structure.',
                    'Get executive buy-in.',
                ]),
                'tools_list' => json_encode([
                    'Confluence / SharePoint',
                    'Governance Templates',
                ]),
                'resources' => json_encode([
                    'Security Governance - ISACA',
                    'NIST Governance Guide',
                ]),
                'deliverables' => json_encode([
                    'Governance model',
                    'Roles document',
                    'Meeting schedule',
                    'Documentation',
                ]),
                'hints' => 'Executive buy-in is essential for governance.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'GRC-019',
                'section' => 'grc',
                'title' => 'Security Exception Management',
                'description' => 'Set up a security exception management process.',
                'overview' => 'Exceptions must be managed. Set up a process.',
                'objectives' => json_encode([
                    'Understand exception management',
                    'Define exception process',
                    'Set up tracking',
                    'Establish review cycle',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Define what requires an exception.',
                    'Create exception request form.',
                    'Set up approval workflow.',
                    'Track exceptions in register.',
                    'Set up periodic review.',
                    'Document process.',
                ]),
                'tools_list' => json_encode([
                    'Jira - https://www.atlassian.com/software/jira',
                    'ServiceNow',
                    'Excel',
                ]),
                'resources' => json_encode([
                    'Exception Management Best Practices',
                    'Risk Acceptance Guide',
                ]),
                'deliverables' => json_encode([
                    'Exception policy',
                    'Request form',
                    'Register',
                    'Documentation',
                ]),
                'hints' => 'Every exception needs an expiry date.',
                'estimated_time' => '4 hours',
                'difficulty' => 3,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'GRC-020',
                'section' => 'grc',
                'title' => 'Security Budget Planning',
                'description' => 'Plan security budget aligned with business.',
                'overview' => 'Security needs budget. Plan it strategically.',
                'objectives' => json_encode([
                    'Understand security budgeting',
                    'Identify needs',
                    'Prioritize investments',
                    'Justify to management',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Assess current security posture.',
                    'Identify gaps and needs.',
                    'Prioritize by risk.',
                    'Estimate costs.',
                    'Create business case.',
                    'Present to management.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Excel',
                    'Business Case Templates',
                ]),
                'resources' => json_encode([
                    'Security Budgeting - Gartner',
                    'CISO Budget Guide',
                ]),
                'deliverables' => json_encode([
                    'Budget plan',
                    'Business case',
                    'Prioritization',
                    'Documentation',
                ]),
                'hints' => 'Speak business language, not security jargon.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== AUTOMATION (5 new) ====================
            [
                'reference_code' => 'AUTO-016',
                'section' => 'automation',
                'title' => 'Automated OSINT Collection',
                'description' => 'Automate OSINT collection for threat intelligence.',
                'overview' => 'OSINT is valuable for threat intel. Automate it.',
                'objectives' => json_encode([
                    'Understand OSINT sources',
                    'Set up collection',
                    'Aggregate data',
                    'Analyze trends',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Identify OSINT sources (Twitter, RSS, forums).',
                    'Set up collection scripts.',
                    'Filter for relevance.',
                    'Aggregate in Elasticsearch.',
                    'Create dashboards.',
                    'Set up alerts for keywords.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Python (BeautifulSoup)',
                    'Elasticsearch - https://www.elastic.co',
                    'Kibana - https://www.elastic.co/kibana',
                ]),
                'resources' => json_encode([
                    'OSINT Techniques (Book)',
                    'Bellingcat Guides',
                ]),
                'deliverables' => json_encode([
                    'Collection scripts',
                    'Aggregated data',
                    'Dashboards',
                    'Documentation',
                ]),
                'hints' => 'Respect robots.txt and rate limits.',
                'estimated_time' => '6 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'AUTO-017',
                'section' => 'automation',
                'title' => 'Automated Incident Triage',
                'description' => 'Automate initial incident triage.',
                'overview' => 'Triage takes time. Automate it.',
                'objectives' => json_encode([
                    'Understand triage workflow',
                    'Set up automation',
                    'Enrich alerts',
                    'Route by severity',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Define triage criteria.',
                    'Set up n8n workflow.',
                    'Trigger on new alert.',
                    'Enrich with threat intel.',
                    'Calculate severity.',
                    'Route to appropriate queue.',
                    'Document workflow.',
                ]),
                'tools_list' => json_encode([
                    'n8n - https://n8n.io',
                    'TheHive - https://thehive-project.org',
                    'Cortex - https://github.com/TheHive-Project/Cortex',
                ]),
                'resources' => json_encode([
                    'Incident Triage Guide - SANS',
                    'TheHive Documentation',
                ]),
                'deliverables' => json_encode([
                    'Workflow',
                    'Test results',
                    'Severity matrix',
                    'Documentation',
                ]),
                'hints' => 'Start with simple rules. Add complexity later.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'AUTO-018',
                'section' => 'automation',
                'title' => 'Automated Security Reports',
                'description' => 'Automate security report generation.',
                'overview' => 'Reports are tedious. Automate them.',
                'objectives' => json_encode([
                    'Identify report needs',
                    'Set up data collection',
                    'Generate reports',
                    'Schedule delivery',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'List required reports (daily, weekly, monthly).',
                    'Identify data sources.',
                    'Write Python scripts.',
                    'Generate PDF/HTML.',
                    'Schedule with cron.',
                    'Email to stakeholders.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Python (ReportLab)',
                    'Jinja2',
                    'Cron',
                ]),
                'resources' => json_encode([
                    'Report Automation Guide',
                    'Python Reporting Libraries',
                ]),
                'deliverables' => json_encode([
                    'Report scripts',
                    'Sample reports',
                    'Schedule',
                    'Documentation',
                ]),
                'hints' => 'Start with one report. Expand over time.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'AUTO-019',
                'section' => 'automation',
                'title' => 'Automated Firewall Rules Audit',
                'description' => 'Automate firewall rule auditing.',
                'overview' => 'Firewall rules accumulate. Audit them automatically.',
                'objectives' => json_encode([
                    'Understand rule auditing',
                    'Set up collection',
                    'Analyze rules',
                    'Find unused rules',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Export firewall rules (iptables, pfSense).',
                    'Parse rules into database.',
                    'Analyze usage logs.',
                    'Identify unused rules.',
                    'Identify overly permissive rules.',
                    'Generate report.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Python',
                    'Firewall Audit Tools',
                    'Excel',
                ]),
                'resources' => json_encode([
                    'Firewall Audit Best Practices',
                    'NIST Firewall Guide',
                ]),
                'deliverables' => json_encode([
                    'Audit script',
                    'Unused rules list',
                    'Report',
                    'Documentation',
                ]),
                'hints' => 'Unused rules should be removed. Fewer rules, less risk.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'AUTO-020',
                'section' => 'automation',
                'title' => 'Automated Threat Modeling',
                'description' => 'Automate threat modeling for new features.',
                'overview' => 'Threat modeling is manual. Automate parts of it.',
                'objectives' => json_encode([
                    'Understand threat modeling',
                    'Set up automation',
                    'Integrate with CI/CD',
                    'Generate reports',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Use Threatspec or similar.',
                    'Write threat model as code.',
                    'Integrate into PR process.',
                    'Auto-generate diagrams.',
                    'Alert on new threats.',
                    'Document workflow.',
                ]),
                'tools_list' => json_encode([
                    'Threatspec - https://threatspec.org',
                    'IriusRisk - https://iriusrisk.com',
                    'pytm - https://github.com/izar/pytm',
                ]),
                'resources' => json_encode([
                    'Threat Modeling as Code',
                    'OWASP Threat Modeling',
                ]),
                'deliverables' => json_encode([
                    'Threat model code',
                    'CI/CD integration',
                    'Generated diagrams',
                    'Documentation',
                ]),
                'hints' => 'Threat modeling as code is emerging. Great for DevOps.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
        ];

        foreach ($tasks as $task) {
            $task['created_at'] = now();
            $task['updated_at'] = now();
            DB::table('cyber_tasks')->updateOrInsert(
                ['reference_code' => $task['reference_code']],
                $task
            );
        }

        echo "Phase 5 - Cyber Tasks created!\n";
        echo "Total: " . count($tasks) . " new tasks\n";
        echo "  - Network Defense: 5\n";
        echo "  - DFIR: 5\n";
        echo "  - Pentest: 5\n";
        echo "  - DevSecOps: 5\n";
        echo "  - GRC: 5\n";
        echo "  - Automation: 5\n";
    }
}