<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CyberTasksPhase4Seeder extends Seeder
{
    public function run(): void
    {
        $tasks = [
            // ==================== NETWORK DEFENSE (5 new) ====================
            [
                'reference_code' => 'NET-DEF-011',
                'section' => 'network_defense',
                'title' => 'IDS/IPS Signature Tuning',
                'description' => 'Tune IDS/IPS signatures to reduce false positives and improve detection.',
                'overview' => 'IDS/IPS systems generate many false positives. In this task, you will tune signatures to focus on real threats.',
                'objectives' => json_encode([
                    'Understand IDS/IPS signature structure',
                    'Analyze false positive patterns',
                    'Tune signatures for your environment',
                    'Test detection with real attacks',
                    'Document tuning decisions',
                ]),
                'instructions' => json_encode([
                    'Set up Suricata or Snort with default rules.',
                    'Run for 24 hours in monitoring mode.',
                    'Analyze alerts for false positives.',
                    'Categorize alerts: real threats vs noise.',
                    'Disable or modify noisy signatures.',
                    'Write custom signatures for your assets.',
                    'Re-test with simulated attacks.',
                    'Document all changes with justification.',
                ]),
                'tools_list' => json_encode([
                    'Suricata - https://suricata.io',
                    'Snort - https://www.snort.org',
                    'Arkime - https://arkime.com',
                ]),
                'resources' => json_encode([
                    'Suricata Rule Writing - https://suricata.readthedocs.io',
                    'Snort Rule Writing Guide',
                    'Emerging Threats Rules',
                ]),
                'deliverables' => json_encode([
                    'Before/after alert counts',
                    'Modified signatures list',
                    'Custom signatures',
                    'Tuning report',
                ]),
                'hints' => 'Start by disabling the noisiest rules, then write custom ones.',
                'estimated_time' => '5 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'NET-DEF-012',
                'section' => 'network_defense',
                'title' => 'Cloud Security Posture Management (CSPM)',
                'description' => 'Set up CSPM to monitor cloud misconfigurations.',
                'overview' => 'Cloud misconfigurations are the #1 cloud risk. Use CSPM to detect them.',
                'objectives' => json_encode([
                    'Understand CSPM',
                    'Set up ScoutSuite or Prowler',
                    'Scan AWS/Azure environment',
                    'Fix critical findings',
                    'Set up continuous monitoring',
                ]),
                'instructions' => json_encode([
                    'Set up a free AWS account.',
                    'Install ScoutSuite: pip install scoutsuite',
                    'Run: scoutsuite aws',
                    'Review findings.',
                    'Fix critical issues (public S3, open SGs).',
                    'Set up Prowler for continuous checks.',
                    'Automate with cron.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'ScoutSuite - https://github.com/nccgroup/ScoutSuite',
                    'Prowler - https://github.com/prowler-cloud/prowler',
                    'CloudSploit - https://github.com/aquasecurity/cloudsploit',
                ]),
                'resources' => json_encode([
                    'AWS Security Best Practices',
                    'CIS AWS Foundations Benchmark',
                ]),
                'deliverables' => json_encode([
                    'Scan results',
                    'Fixed configs',
                    'Continuous check setup',
                    'Documentation',
                ]),
                'hints' => 'Use AWS Free Tier. Disable unused services.',
                'estimated_time' => '5 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'NET-DEF-013',
                'section' => 'network_defense',
                'title' => 'Network Access Control (NAC) Implementation',
                'description' => 'Implement NAC to control device access to the network.',
                'overview' => 'NAC ensures only authorized devices connect. Implement it.',
                'objectives' => json_encode([
                    'Understand NAC concepts',
                    'Set up PacketFence',
                    'Configure 802.1X',
                    'Test with authorized/unauthorized devices',
                    'Document policies',
                ]),
                'instructions' => json_encode([
                    'Set up PacketFence on a VM.',
                    'Configure with a test switch or RADIUS.',
                    'Enable 802.1X.',
                    'Register authorized devices.',
                    'Attempt to connect unauthorized device.',
                    'Verify it is blocked.',
                    'Document policies and onboarding process.',
                ]),
                'tools_list' => json_encode([
                    'PacketFence - https://packetfence.org',
                    'FreeRADIUS - https://freeradius.org',
                    'Cisco ISE (enterprise)',
                ]),
                'resources' => json_encode([
                    'PacketFence Documentation',
                    '802.1X Best Practices - Cisco',
                ]),
                'deliverables' => json_encode([
                    'PacketFence setup',
                    'Test results',
                    'Policy document',
                    'Onboarding process',
                ]),
                'hints' => 'Start with MAC-based NAC. Move to 802.1X later.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'NET-DEF-014',
                'section' => 'network_defense',
                'title' => 'SSL/TLS Certificate Management',
                'description' => 'Audit and manage SSL/TLS certificates across the organization.',
                'overview' => 'Expired or weak certificates cause outages and vulnerabilities. Manage them.',
                'objectives' => json_encode([
                    'Inventory all certificates',
                    'Audit expiration dates',
                    'Check for weak algorithms',
                    'Automate renewal',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Scan network for SSL/TLS services.',
                    'Use SSL Labs or testssl.sh.',
                    'List all certificates with expiration.',
                    'Check for MD5, SHA1, weak keys.',
                    'Set up Let\'s Encrypt where possible.',
                    'Configure auto-renewal.',
                    'Set up expiration alerts.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'testssl.sh - https://testssl.sh',
                    'SSL Labs - https://www.ssllabs.com',
                    'Certbot - https://certbot.eff.org',
                ]),
                'resources' => json_encode([
                    'SSL/TLS Best Practices - OWASP',
                    'Let\'s Encrypt Documentation',
                ]),
                'deliverables' => json_encode([
                    'Certificate inventory',
                    'Audit results',
                    'Auto-renewal setup',
                    'Alert configuration',
                ]),
                'hints' => 'Let\'s Encrypt is free and automatable.',
                'estimated_time' => '4 hours',
                'difficulty' => 3,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'NET-DEF-015',
                'section' => 'network_defense',
                'title' => 'Honeypot Deployment & Monitoring',
                'description' => 'Deploy a honeypot to detect attackers early.',
                'overview' => 'Honeypots are traps for attackers. Detect early intrusions.',
                'objectives' => json_encode([
                    'Understand honeypots',
                    'Deploy T-Pot or Cowrie',
                    'Monitor attacks',
                    'Analyze attacker TTPs',
                    'Document findings',
                ]),
                'instructions' => json_encode([
                    'Set up a VM in DMZ.',
                    'Deploy T-Pot or Cowrie.',
                    'Expose SSH/HTTP ports.',
                    'Monitor for connection attempts.',
                    'Analyze attacker commands.',
                    'Extract IOCs (IPs, hashes).',
                    'Feed into threat intel.',
                    'Document findings.',
                ]),
                'tools_list' => json_encode([
                    'T-Pot - https://github.com/telekom-security/tpotce',
                    'Cowrie - https://github.com/cowrie/cowrie',
                    'Dionaea - https://github.com/DinoTools/dionaea',
                ]),
                'resources' => json_encode([
                    'Honeypot Best Practices',
                    'SANS Honeypot Guide',
                ]),
                'deliverables' => json_encode([
                    'Honeypot deployment',
                    'Attack logs',
                    'IOC list',
                    'Analysis report',
                ]),
                'hints' => 'Never deploy honeypot on production network.',
                'estimated_time' => '4 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== DFIR (5 new) ====================
            [
                'reference_code' => 'DFIR-011',
                'section' => 'dfir',
                'title' => 'Timeline Analysis with Plaso/log2timeline',
                'description' => 'Create a forensic timeline from a compromised system.',
                'overview' => 'Timelines are critical for investigations. Build one with Plaso.',
                'objectives' => json_encode([
                    'Understand timeline analysis',
                    'Use log2timeline',
                    'Analyze with Timesketch',
                    'Identify attack events',
                    'Document timeline',
                ]),
                'instructions' => json_encode([
                    'Acquire disk image from test system.',
                    'Install Plaso: pip install plaso',
                    'Run: log2timeline.py output.plaso disk.img',
                    'Process: psort.py -o timesketch output.plaso',
                    'Import to Timesketch.',
                    'Filter events by time and type.',
                    'Identify attack events.',
                    'Document timeline.',
                ]),
                'tools_list' => json_encode([
                    'Plaso - https://github.com/log2timeline/plaso',
                    'Timesketch - https://timesketch.org',
                    'Autopsy - https://www.autopsy.com',
                ]),
                'resources' => json_encode([
                    'Plaso Documentation',
                    'SANS Timeline Analysis',
                ]),
                'deliverables' => json_encode([
                    'Plaso file',
                    'Timesketch project',
                    'Attack timeline',
                    'Report',
                ]),
                'hints' => 'Start with specific event types. Expand as needed.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DFIR-012',
                'section' => 'dfir',
                'title' => 'Malware Unpacking & Analysis',
                'description' => 'Unpack and analyze a packed malware sample.',
                'overview' => 'Packed malware hides its code. Learn to unpack it.',
                'objectives' => json_encode([
                    'Understand packing techniques',
                    'Identify packer',
                    'Unpack sample',
                    'Analyze unpacked code',
                    'Document IOCs',
                ]),
                'instructions' => json_encode([
                    'Get a packed sample (MalwareBazaar).',
                    'Use PEiD or Detect It Easy to identify packer.',
                    'Set up x64dbg in isolated VM.',
                    'Set breakpoints at OEP.',
                    'Dump unpacked process.',
                    'Fix imports with Scylla.',
                    'Analyze with IDA/Ghidra.',
                    'Document IOCs.',
                ]),
                'tools_list' => json_encode([
                    'x64dbg - https://x64dbg.com',
                    'Detect It Easy - https://github.com/horsicq/Detect-It-Easy',
                    'Scylla - https://github.com/NtQuery/Scylla',
                    'Ghidra - https://ghidra-sre.org',
                ]),
                'resources' => json_encode([
                    'Practical Malware Analysis (Book)',
                    'Malware Unpacking Tutorials',
                ]),
                'deliverables' => json_encode([
                    'Unpacked binary',
                    'Analysis notes',
                    'IOC list',
                    'Report',
                ]),
                'hints' => 'Use isolated VM. Never run malware on host.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DFIR-013',
                'section' => 'dfir',
                'title' => 'Cloud Forensics (AWS)',
                'description' => 'Perform forensic investigation in AWS.',
                'overview' => 'Cloud forensics is different from on-prem. Learn AWS forensics.',
                'objectives' => json_encode([
                    'Understand cloud forensic challenges',
                    'Collect CloudTrail logs',
                    'Analyze EC2 forensics',
                    'Investigate S3 access',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up AWS account with sample activity.',
                    'Enable CloudTrail.',
                    'Simulate suspicious activity.',
                    'Collect CloudTrail logs.',
                    'Analyze for unauthorized API calls.',
                    'Snapshot EC2 instance for analysis.',
                    'Review S3 access logs.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'AWS CloudTrail',
                    'AWS CloudWatch Logs',
                    'CloudTrail Lake',
                ]),
                'resources' => json_encode([
                    'AWS Security Incident Response Guide',
                    'Cloud Forensics - SANS',
                ]),
                'deliverables' => json_encode([
                    'CloudTrail analysis',
                    'EC2 snapshot',
                    'S3 access report',
                    'Incident report',
                ]),
                'hints' => 'CloudTrail is your best friend in AWS.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DFIR-014',
                'section' => 'dfir',
                'title' => 'Network Forensic - Full Attack Reconstruction',
                'description' => 'Reconstruct a full attack from network captures.',
                'overview' => 'Full attack reconstruction from PCAPs.',
                'objectives' => json_encode([
                    'Analyze multi-stage attack',
                    'Identify initial access',
                    'Trace lateral movement',
                    'Find exfiltration',
                    'Document timeline',
                ]),
                'instructions' => json_encode([
                    'Get multi-stage PCAP (from CTF or malware-traffic).',
                    'Identify victim IPs.',
                    'Trace initial access (phishing, exploit).',
                    'Follow lateral movement.',
                    'Find exfiltration.',
                    'Reconstruct attacker actions.',
                    'Document full timeline.',
                ]),
                'tools_list' => json_encode([
                    'Wireshark - https://www.wireshark.org',
                    'NetworkMiner - https://www.netresec.com/networkminer',
                    'Zeek - https://zeek.org',
                    'Arkime - https://arkime.com',
                ]),
                'resources' => json_encode([
                    'Malware Traffic Analysis',
                    'Wireshark Network Analysis (Book)',
                ]),
                'deliverables' => json_encode([
                    'Full timeline',
                    'IOC list',
                    'Attack reconstruction',
                    'Report',
                ]),
                'hints' => 'Start from the end (exfiltration) and work backwards.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DFIR-015',
                'section' => 'dfir',
                'title' => 'Anti-Forensics Detection',
                'description' => 'Detect anti-forensic techniques used by attackers.',
                'overview' => 'Attackers hide traces. Learn to detect anti-forensics.',
                'objectives' => json_encode([
                    'Understand anti-forensics',
                    'Detect timestomping',
                    'Detect log deletion',
                    'Detect encrypted containers',
                    'Document techniques',
                ]),
                'instructions' => json_encode([
                    'Set up test system.',
                    'Apply anti-forensic techniques (timestomp, log delete).',
                    'Analyze with Autopsy.',
                    'Detect inconsistencies in timestamps.',
                    'Detect gaps in logs.',
                    'Detect hidden volumes.',
                    'Document all techniques.',
                ]),
                'tools_list' => json_encode([
                    'Autopsy - https://www.autopsy.com',
                    'Volatility - https://www.volatilityfoundation.org',
                    'Sleuth Kit - https://www.sleuthkit.org',
                ]),
                'resources' => json_encode([
                    'Anti-Forensics Guide',
                    'SANS Anti-Forensics',
                ]),
                'deliverables' => json_encode([
                    'Detection methods',
                    'Analysis report',
                    'Technique documentation',
                ]),
                'hints' => 'Timestomping often leaves $SI and $FN inconsistencies.',
                'estimated_time' => '5 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== PENTEST (5 new) ====================
            [
                'reference_code' => 'PT-011',
                'section' => 'pentest',
                'title' => 'Web Application Firewall (WAF) Bypass',
                'description' => 'Learn to bypass WAF protections.',
                'overview' => 'WAFs are not foolproof. Learn bypass techniques.',
                'objectives' => json_encode([
                    'Understand WAF types',
                    'Set up ModSecurity',
                    'Test bypass techniques',
                    'Document working bypasses',
                    'Recommend hardening',
                ]),
                'instructions' => json_encode([
                    'Set up ModSecurity with OWASP CRS.',
                    'Deploy DVWA behind WAF.',
                    'Attempt SQLi with encoding, case variation.',
                    'Attempt XSS with encoding.',
                    'Use WAFW00F to fingerprint.',
                    'Document bypasses.',
                    'Recommend WAF tuning.',
                ]),
                'tools_list' => json_encode([
                    'ModSecurity - https://modsecurity.org',
                    'WAFW00F - https://github.com/EnableSecurity/wafw00f',
                    'Burp Suite - https://portswigger.net/burp',
                ]),
                'resources' => json_encode([
                    'WAF Bypass Cheat Sheet',
                    'OWASP CRS Documentation',
                ]),
                'deliverables' => json_encode([
                    'WAF setup',
                    'Bypass techniques',
                    'Documentation',
                    'Hardening recommendations',
                ]),
                'hints' => 'Encoding, case variation, and comments are common bypasses.',
                'estimated_time' => '5 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'PT-012',
                'section' => 'pentest',
                'title' => 'Social Engineering Toolkit (SET) Attack',
                'description' => 'Perform social engineering attacks with SET.',
                'overview' => 'SET automates social engineering. Learn to use it.',
                'objectives' => json_encode([
                    'Understand SET',
                    'Create phishing page',
                    'Clone legitimate site',
                    'Perform credential harvesting',
                    'Document findings',
                ]),
                'instructions' => json_encode([
                    'Install SET.',
                    'Create credential harvester.',
                    'Clone a login page (e.g., Gmail).',
                    'Set up email template.',
                    'Send test campaign.',
                    'Capture credentials.',
                    'Document effectiveness.',
                ]),
                'tools_list' => json_encode([
                    'SET - https://github.com/trustedsec/social-engineer-toolkit',
                    'GoPhish - https://getgophish.com',
                ]),
                'resources' => json_encode([
                    'SET Documentation',
                    'Social Engineering - SANS',
                ]),
                'deliverables' => json_encode([
                    'Phishing page',
                    'Campaign results',
                    'Analysis',
                    'Report',
                ]),
                'hints' => 'Only test with consent. Never on real users without permission.',
                'estimated_time' => '4 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'PT-013',
                'section' => 'pentest',
                'title' => 'Wireless Pentesting - WPA3 Attacks',
                'description' => 'Test WPA3 wireless networks for vulnerabilities.',
                'overview' => 'WPA3 is newer but not invincible. Learn attacks.',
                'objectives' => json_encode([
                    'Understand WPA3',
                    'Set up WPA3 AP',
                    'Test Dragonblood attacks',
                    'Test downgrade attacks',
                    'Document findings',
                ]),
                'instructions' => json_encode([
                    'Set up WPA3 AP (hostapd).',
                    'Install WiFi adapter in monitor mode.',
                    'Test Dragonblood (CVE-2019-9494).',
                    'Attempt downgrade to WPA2.',
                    'Capture handshakes.',
                    'Document resistance.',
                ]),
                'tools_list' => json_encode([
                    'Aircrack-ng - https://www.aircrack-ng.org',
                    'hostapd - https://w1.fi/hostapd',
                    'Kali Linux',
                ]),
                'resources' => json_encode([
                    'WPA3 Specification',
                    'Dragonblood Paper',
                ]),
                'deliverables' => json_encode([
                    'Test results',
                    'Attack attempts',
                    'Documentation',
                ]),
                'hints' => 'WPA3 is much harder to attack than WPA2. Document resistance.',
                'estimated_time' => '5 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'PT-014',
                'section' => 'pentest',
                'title' => 'Docker Container Escape',
                'description' => 'Attempt to escape a Docker container.',
                'overview' => 'Containers are not sandboxes. Learn escape techniques.',
                'objectives' => json_encode([
                    'Understand container isolation',
                    'Detect misconfigurations',
                    'Escape privileged container',
                    'Access host',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up Docker with vulnerable container.',
                    'Run with --privileged or mounted docker.sock.',
                    'Detect: ls /dev, mount, cat /proc/1/cgroup.',
                    'Escape via /dev, docker.sock, or cgroups.',
                    'Access host filesystem.',
                    'Document techniques.',
                    'Recommend hardening.',
                ]),
                'tools_list' => json_encode([
                    'Docker - https://www.docker.com',
                    'Deepce - https://github.com/stealthcopter/deepce',
                    'CDK - https://github.com/cdk-team/CDK',
                ]),
                'resources' => json_encode([
                    'Container Security - Liz Rice',
                    'Docker Security Best Practices',
                ]),
                'deliverables' => json_encode([
                    'Escape proof',
                    'Host access',
                    'Documentation',
                    'Hardening recommendations',
                ]),
                'hints' => 'Never run privileged containers in production.',
                'estimated_time' => '4 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'PT-015',
                'section' => 'pentest',
                'title' => 'Cloud Pentesting (AWS)',
                'description' => 'Perform penetration testing in AWS.',
                'overview' => 'Cloud pentesting requires different tools. Learn AWS testing.',
                'objectives' => json_encode([
                    'Understand AWS pentest methodology',
                    'Enumerate AWS resources',
                    'Find misconfigurations',
                    'Attempt privilege escalation',
                    'Document findings',
                ]),
                'instructions' => json_encode([
                    'Set up test AWS account.',
                    'Use Pacu or ScoutSuite.',
                    'Enumerate: IAM, S3, EC2, Lambda.',
                    'Find public S3 buckets.',
                    'Attempt IAM privilege escalation.',
                    'Check for exposed credentials.',
                    'Document findings.',
                    'Provide remediation.',
                ]),
                'tools_list' => json_encode([
                    'Pacu - https://github.com/RhinoSecurityLabs/pacu',
                    'ScoutSuite - https://github.com/nccgroup/ScoutSuite',
                    'Cloudsplaining - https://github.com/salesforce/cloudsplaining',
                ]),
                'resources' => json_encode([
                    'AWS Pentest Guide',
                    'Hacking the Cloud - https://hackingthe.cloud',
                ]),
                'deliverables' => json_encode([
                    'Enumeration report',
                    'Escalation proof',
                    'Findings',
                    'Remediation plan',
                ]),
                'hints' => 'Get written permission. AWS pentest has specific rules.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== DEVSECOPS (5 new) ====================
            [
                'reference_code' => 'DEVSEC-011',
                'section' => 'devsecops',
                'title' => 'SBOM Generation & Management',
                'description' => 'Generate and manage Software Bill of Materials.',
                'overview' => 'SBOMs are now required by many regulations. Generate them.',
                'objectives' => json_encode([
                    'Understand SBOM standards',
                    'Generate SBOM for a project',
                    'Sign and store SBOMs',
                    'Integrate into CI/CD',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Choose SBOM format (SPDX, CycloneDX).',
                    'Install Syft: brew install syft.',
                    'Generate SBOM: syft <image> -o spdx-json',
                    'Sign with Cosign.',
                    'Store in artifact registry.',
                    'Integrate into build pipeline.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Syft - https://github.com/anchore/syft',
                    'CycloneDX - https://cyclonedx.org',
                    'SPDX - https://spdx.dev',
                ]),
                'resources' => json_encode([
                    'NTIA SBOM Guide',
                    'SPDX Specification',
                ]),
                'deliverables' => json_encode([
                    'SBOM files',
                    'Signature',
                    'Pipeline integration',
                    'Documentation',
                ]),
                'hints' => 'CycloneDX is more compact. SPDX is more established.',
                'estimated_time' => '4 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DEVSEC-012',
                'section' => 'devsecops',
                'title' => 'Kubernetes Security Hardening',
                'description' => 'Harden a Kubernetes cluster.',
                'overview' => 'K8s default config is insecure. Harden it.',
                'objectives' => json_encode([
                    'Understand K8s security',
                    'Enable RBAC',
                    'Configure Network Policies',
                    'Enable Pod Security Standards',
                    'Document hardening',
                ]),
                'instructions' => json_encode([
                    'Set up K8s cluster.',
                    'Enable RBAC with least privilege.',
                    'Configure Network Policies (deny all, allow specific).',
                    'Enable Pod Security Standards.',
                    'Set up audit logging.',
                    'Use kube-bench to audit.',
                    'Fix findings.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Kubernetes - https://kubernetes.io',
                    'kube-bench - https://github.com/aquasecurity/kube-bench',
                    'kube-hunter - https://github.com/aquasecurity/kube-hunter',
                ]),
                'resources' => json_encode([
                    'K8s Security Docs - https://kubernetes.io/docs/concepts/security',
                    'CIS Kubernetes Benchmark',
                ]),
                'deliverables' => json_encode([
                    'Hardened cluster',
                    'kube-bench report',
                    'Configurations',
                    'Documentation',
                ]),
                'hints' => 'kube-bench finds most issues. Fix them one by one.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DEVSEC-013',
                'section' => 'devsecops',
                'title' => 'Secure API Gateway Configuration',
                'description' => 'Configure an API Gateway securely.',
                'overview' => 'API Gateways are single points of failure. Configure them securely.',
                'objectives' => json_encode([
                    'Understand API Gateway security',
                    'Set up Kong or AWS API Gateway',
                    'Configure authentication',
                    'Set up rate limiting',
                    'Enable logging',
                ]),
                'instructions' => json_encode([
                    'Set up Kong in Docker.',
                    'Configure JWT authentication.',
                    'Set up rate limiting.',
                    'Enable access logs.',
                    'Configure CORS properly.',
                    'Test with Postman.',
                    'Document configuration.',
                ]),
                'tools_list' => json_encode([
                    'Kong - https://konghq.com',
                    'AWS API Gateway - https://aws.amazon.com/api-gateway',
                    'Tyk - https://tyk.io',
                ]),
                'resources' => json_encode([
                    'API Gateway Security - OWASP',
                    'Kong Documentation',
                ]),
                'deliverables' => json_encode([
                    'Gateway configuration',
                    'Test results',
                    'Logs',
                    'Documentation',
                ]),
                'hints' => 'Always enable authentication and rate limiting.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DEVSEC-014',
                'section' => 'devsecops',
                'title' => 'Secure Code Review',
                'description' => 'Perform manual secure code review.',
                'overview' => 'Automated tools miss logic flaws. Review code manually.',
                'objectives' => json_encode([
                    'Understand common code flaws',
                    'Review authentication code',
                    'Review authorization code',
                    'Review input validation',
                    'Document findings',
                ]),
                'instructions' => json_encode([
                    'Take an open-source project (e.g., Flask app).',
                    'Review authentication logic.',
                    'Review authorization checks.',
                    'Review input validation.',
                    'Look for: SQLi, XSS, CSRF, IDOR, race conditions.',
                    'Document findings with line numbers.',
                    'Suggest fixes.',
                ]),
                'tools_list' => json_encode([
                    'Semgrep - https://semgrep.dev',
                    'SonarQube - https://www.sonarqube.org',
                    'VS Code',
                ]),
                'resources' => json_encode([
                    'Secure Code Review Guide - OWASP',
                    'Code Review Best Practices',
                ]),
                'deliverables' => json_encode([
                    'Review notes',
                    'Vulnerabilities found',
                    'Fix suggestions',
                    'Report',
                ]),
                'hints' => 'Focus on authentication and authorization first.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'DEVSEC-015',
                'section' => 'devsecops',
                'title' => 'Zero Trust for Microservices',
                'description' => 'Implement Zero Trust for microservices.',
                'overview' => 'Microservices need Zero Trust. Implement mTLS and auth.',
                'objectives' => json_encode([
                    'Understand Zero Trust for microservices',
                    'Implement mTLS',
                    'Set up service mesh',
                    'Configure service auth',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up Istio or Linkerd.',
                    'Enable mTLS between services.',
                    'Configure service-to-service auth.',
                    'Set up authorization policies.',
                    'Test with sample services.',
                    'Enable observability.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Istio - https://istio.io',
                    'Linkerd - https://linkerd.io',
                    'SPIFFE - https://spiffe.io',
                ]),
                'resources' => json_encode([
                    'Istio Security Docs',
                    'Zero Trust for Microservices - Google',
                ]),
                'deliverables' => json_encode([
                    'Service mesh setup',
                    'mTLS config',
                    'Auth policies',
                    'Documentation',
                ]),
                'hints' => 'Start with Istio. It has better documentation.',
                'estimated_time' => '7 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== GRC (5 new) ====================
            [
                'reference_code' => 'GRC-011',
                'section' => 'grc',
                'title' => 'Business Impact Analysis (BIA)',
                'description' => 'Conduct a Business Impact Analysis for critical processes.',
                'overview' => 'BIA identifies what matters most. Conduct one.',
                'objectives' => json_encode([
                    'Understand BIA methodology',
                    'Identify critical processes',
                    'Determine RTO/RPO',
                    'Rank by impact',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'List all business processes.',
                    'Identify critical ones.',
                    'For each: determine RTO, RPO.',
                    'Analyze financial/reputational impact.',
                    'Rank processes.',
                    'Document in BIA report.',
                ]),
                'tools_list' => json_encode([
                    'BIA Templates - https://www.ready.gov',
                    'Excel',
                ]),
                'resources' => json_encode([
                    'FEMA BIA Guide',
                    'ISO 22301',
                ]),
                'deliverables' => json_encode([
                    'Process list',
                    'RTO/RPO',
                    'Impact analysis',
                    'BIA report',
                ]),
                'hints' => 'Focus on processes, not systems.',
                'estimated_time' => '6 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'GRC-012',
                'section' => 'grc',
                'title' => 'Security Architecture Review',
                'description' => 'Review the security architecture of a system.',
                'overview' => 'Architecture reviews catch issues early.',
                'objectives' => json_encode([
                    'Understand architecture review',
                    'Review defense in depth',
                    'Review network segmentation',
                    'Review identity architecture',
                    'Document recommendations',
                ]),
                'instructions' => json_encode([
                    'Choose a system to review.',
                    'Create architecture diagram.',
                    'Review each layer: network, identity, data, app.',
                    'Check for: single points of failure, missing controls, weak auth.',
                    'Compare with best practices.',
                    'Document recommendations.',
                ]),
                'tools_list' => json_encode([
                    'Draw.io - https://app.diagrams.net',
                    'Threat Dragon - https://owasp.org/www-project-threat-dragon',
                ]),
                'resources' => json_encode([
                    'Security Architecture - SABSA',
                    'NIST SP 800-53',
                ]),
                'deliverables' => json_encode([
                    'Architecture diagram',
                    'Review notes',
                    'Recommendations',
                    'Report',
                ]),
                'hints' => 'Always diagram first. It reveals gaps.',
                'estimated_time' => '7 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'GRC-013',
                'section' => 'grc',
                'title' => 'Security Awareness Metrics',
                'description' => 'Track and report security awareness metrics.',
                'overview' => 'Awareness programs need metrics. Track them.',
                'objectives' => json_encode([
                    'Define awareness metrics',
                    'Collect data',
                    'Analyze trends',
                    'Report to management',
                    'Improve program',
                ]),
                'instructions' => json_encode([
                    'Choose metrics: phishing click rate, training completion, incident reports.',
                    'Collect data from campaigns.',
                    'Track over time.',
                    'Create dashboard.',
                    'Report monthly.',
                    'Improve program based on data.',
                ]),
                'tools_list' => json_encode([
                    'KnowBe4 - https://www.knowbe4.com',
                    'Excel / Power BI',
                ]),
                'resources' => json_encode([
                    'SANS Awareness Metrics',
                    'Gartner Awareness KPIs',
                ]),
                'deliverables' => json_encode([
                    'Metric definitions',
                    'Dashboard',
                    'Reports',
                    'Improvement plan',
                ]),
                'hints' => 'Phishing click rate is the most actionable metric.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'GRC-014',
                'section' => 'grc',
                'title' => 'Cyber Insurance Assessment',
                'description' => 'Assess requirements for cyber insurance.',
                'overview' => 'Cyber insurance requires specific controls. Assess readiness.',
                'objectives' => json_encode([
                    'Understand cyber insurance requirements',
                    'Assess current controls',
                    'Identify gaps',
                    'Get quotes',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Research cyber insurance requirements.',
                    'Check controls: MFA, EDR, backups, training.',
                    'Document current state.',
                    'Identify gaps.',
                    'Get quotes from 3 insurers.',
                    'Review policies.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Insurance Comparison Sites',
                    'Excel',
                ]),
                'resources' => json_encode([
                    'Cyber Insurance Guide - Marsh',
                    'Insurance Requirements - AIG',
                ]),
                'deliverables' => json_encode([
                    'Requirements checklist',
                    'Gap analysis',
                    'Quotes',
                    'Recommendations',
                ]),
                'hints' => 'MFA and backups are usually required.',
                'estimated_time' => '5 hours',
                'difficulty' => 3,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'GRC-015',
                'section' => 'grc',
                'title' => 'Security Policy Review Cycle',
                'description' => 'Establish a security policy review cycle.',
                'overview' => 'Policies go stale. Establish review cycles.',
                'objectives' => json_encode([
                    'Inventory all policies',
                    'Define review schedule',
                    'Assign owners',
                    'Establish review process',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'List all security policies.',
                    'Assign owners.',
                    'Define review frequency (annual, semi-annual).',
                    'Create review checklist.',
                    'Set up calendar reminders.',
                    'Track reviews.',
                    'Document process.',
                ]),
                'tools_list' => json_encode([
                    'Confluence - https://www.atlassian.com/software/confluence',
                    'SharePoint',
                    'Excel',
                ]),
                'resources' => json_encode([
                    'Policy Management Best Practices',
                    'ISO 27001 Documentation',
                ]),
                'deliverables' => json_encode([
                    'Policy inventory',
                    'Review schedule',
                    'Process document',
                    'Tracking system',
                ]),
                'hints' => 'Not all policies need annual review. High-risk ones do.',
                'estimated_time' => '4 hours',
                'difficulty' => 3,
                'points' => 100,
                'is_active' => true,
            ],

            // ==================== AUTOMATION (5 new) ====================
            [
                'reference_code' => 'AUTO-011',
                'section' => 'automation',
                'title' => 'Automated IOC Enrichment',
                'description' => 'Automate IOC enrichment from multiple sources.',
                'overview' => 'Manual enrichment is slow. Automate it.',
                'objectives' => json_encode([
                    'Identify IOC sources',
                    'Set up enrichment pipeline',
                    'Query multiple APIs',
                    'Aggregate results',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Choose APIs: VirusTotal, AbuseIPDB, Shodan.',
                    'Get API keys.',
                    'Write Python script.',
                    'Input: IOC (IP, domain, hash).',
                    'Query each API.',
                    'Aggregate results.',
                    'Output JSON report.',
                    'Test with sample IOCs.',
                ]),
                'tools_list' => json_encode([
                    'Python',
                    'VirusTotal API - https://developers.virustotal.com',
                    'AbuseIPDB - https://www.abuseipdb.com',
                    'Shodan - https://shodan.io',
                ]),
                'resources' => json_encode([
                    'Threat Intel APIs Guide',
                    'Python Requests Library',
                ]),
                'deliverables' => json_encode([
                    'Python script',
                    'Sample reports',
                    'API integration',
                    'Documentation',
                ]),
                'hints' => 'Use free tiers first. Cache results to avoid rate limits.',
                'estimated_time' => '5 hours',
                'difficulty' => 4,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'AUTO-012',
                'section' => 'automation',
                'title' => 'Automated Phishing Response',
                'description' => 'Automate response to reported phishing emails.',
                'overview' => 'Phishing reports need fast response. Automate it.',
                'objectives' => json_encode([
                    'Understand phishing response workflow',
                    'Set up email ingestion',
                    'Extract IOCs',
                    'Auto-remediate',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Set up a mailbox for phishing reports.',
                    'Write script to read emails.',
                    'Extract URLs, attachments, headers.',
                    'Query VirusTotal for URLs.',
                    'If malicious: block in firewall.',
                    'Notify reporter.',
                    'Log incident.',
                    'Document workflow.',
                ]),
                'tools_list' => json_encode([
                    'Python (imaplib)',
                    'VirusTotal API',
                    'Firewall API',
                    'TheHive - https://thehive-project.org',
                ]),
                'resources' => json_encode([
                    'Phishing Response Playbook - SANS',
                    'TheHive Documentation',
                ]),
                'deliverables' => json_encode([
                    'Workflow script',
                    'Test results',
                    'Integration',
                    'Documentation',
                ]),
                'hints' => 'Use a dedicated mailbox. Never auto-delete emails.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'AUTO-013',
                'section' => 'automation',
                'title' => 'Automated Compliance Checks',
                'description' => 'Automate compliance checks for cloud environments.',
                'overview' => 'Compliance checks are repetitive. Automate them.',
                'objectives' => json_encode([
                    'Understand compliance automation',
                    'Set up Cloud Custodian',
                    'Write policies',
                    'Schedule checks',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Install Cloud Custodian.',
                    'Write policies: no public S3, require MFA, encryption enabled.',
                    'Test policies against AWS.',
                    'Configure auto-remediation.',
                    'Schedule checks.',
                    'Generate reports.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Cloud Custodian - https://cloudcustodian.io',
                    'AWS Config',
                    'Azure Policy',
                ]),
                'resources' => json_encode([
                    'Cloud Custodian Docs',
                    'CIS Benchmarks',
                ]),
                'deliverables' => json_encode([
                    'Policy files',
                    'Schedule',
                    'Reports',
                    'Documentation',
                ]),
                'hints' => 'Cloud Custodian works on AWS, Azure, GCP.',
                'estimated_time' => '6 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'AUTO-014',
                'section' => 'automation',
                'title' => 'Automated User Onboarding/Offboarding',
                'description' => 'Automate user account lifecycle management.',
                'overview' => 'Manual user management is slow and error-prone. Automate it.',
                'objectives' => json_encode([
                    'Understand lifecycle automation',
                    'Set up orchestration',
                    'Automate provisioning',
                    'Automate deprovisioning',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Choose orchestration tool (Ansible, n8n).',
                    'Create workflow for onboarding: create AD, email, MFA, apps.',
                    'Create workflow for offboarding: disable, backup, delete.',
                    'Test with sample users.',
                    'Log all actions.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Ansible - https://www.ansible.com',
                    'n8n - https://n8n.io',
                    'Okta - https://www.okta.com',
                ]),
                'resources' => json_encode([
                    'IAM Lifecycle Best Practices',
                    'Ansible Documentation',
                ]),
                'deliverables' => json_encode([
                    'Workflow files',
                    'Test results',
                    'Logs',
                    'Documentation',
                ]),
                'hints' => 'Offboarding should be same-day. Automate it.',
                'estimated_time' => '7 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
            [
                'reference_code' => 'AUTO-015',
                'section' => 'automation',
                'title' => 'Security Chatbot for Helpdesk',
                'description' => 'Build a security chatbot for common questions.',
                'overview' => 'Chatbots reduce helpdesk load. Build a security one.',
                'objectives' => json_encode([
                    'Understand chatbot use cases',
                    'Set up Rasa or Dialogflow',
                    'Train with security FAQs',
                    'Integrate with helpdesk',
                    'Document',
                ]),
                'instructions' => json_encode([
                    'Install Rasa or use Dialogflow.',
                    'Define intents: password reset, phishing report, VPN.',
                    'Train with sample dialogs.',
                    'Integrate with Slack/Teams.',
                    'Connect to helpdesk API.',
                    'Test with sample queries.',
                    'Document.',
                ]),
                'tools_list' => json_encode([
                    'Rasa - https://rasa.com',
                    'Dialogflow - https://cloud.google.com/dialogflow',
                    'Botpress - https://botpress.com',
                ]),
                'resources' => json_encode([
                    'Rasa Documentation',
                    'Chatbot Best Practices',
                ]),
                'deliverables' => json_encode([
                    'Chatbot setup',
                    'Training data',
                    'Integration',
                    'Documentation',
                ]),
                'hints' => 'Start with 5 intents. Expand over time.',
                'estimated_time' => '8 hours',
                'difficulty' => 5,
                'points' => 100,
                'is_active' => true,
            ],
        ];

        foreach ($tasks as $task) {
            $task['created_at'] = now();
            $task['updated_at'] = now();
            DB::table('cyber_tasks')->updateOrInsert(
                ['reference_code' => $task['reference_code']],
                $task
            );
        }

        echo "Phase 4 - Cyber Tasks created!\n";
        echo "Total: " . count($tasks) . " new tasks\n";
        echo "  - Network Defense: 5\n";
        echo "  - DFIR: 5\n";
        echo "  - Pentest: 5\n";
        echo "  - DevSecOps: 5\n";
        echo "  - GRC: 5\n";
        echo "  - Automation: 5\n";
    }
}