<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ITAndSecurityScenariosSeeder extends Seeder
{
    public function run(): void
    {
        $scenarios = [
            // ============ IT PROFESSIONAL ============
            [
                'title' => 'The Default Credentials',
                'description' => 'Forgotten default password on firewall',
                'category' => 'it_security',
                'user_type' => 'it_professional',
                'level' => 'easy',
                'stage' => 1,
                'difficulty' => 'beginner',
                'estimated_minutes' => 3,
                'content' => json_encode([
                    'scenario' => 'Ahmed deploys a firewall but forgets to change default credentials admin/admin. Attacker gains access.',
                    'question' => 'What was the mistake?',
                    'options' => [
                        ['text' => 'Deploying firewall', 'correct' => false],
                        ['text' => 'Leaving default credentials', 'correct' => true],
                        ['text' => 'Connecting to internet', 'correct' => false],
                        ['text' => 'Not installing updates', 'correct' => false],
                    ],
                    'explanation' => 'Default credentials must be changed immediately.',
                ]),
            ],
            [
                'title' => 'The Hardcoded API Key',
                'description' => 'Developer exposed credentials in code',
                'category' => 'it_security',
                'user_type' => 'it_professional',
                'level' => 'easy',
                'stage' => 1,
                'difficulty' => 'beginner',
                'estimated_minutes' => 3,
                'content' => json_encode([
                    'scenario' => 'Sara hardcodes database password in source code. GitHub account compromised. Data stolen.',
                    'question' => 'What was the error?',
                    'options' => [
                        ['text' => 'Using GitHub', 'correct' => false],
                        ['text' => 'Hardcoding credentials in code', 'correct' => true],
                        ['text' => 'Developing features', 'correct' => false],
                        ['text' => 'Not using 2FA', 'correct' => false],
                    ],
                    'explanation' => 'Never hardcode credentials. Use environment variables.',
                ]),
            ],
            [
                'title' => 'The Shared Admin Account',
                'description' => 'One admin account for whole team',
                'category' => 'it_security',
                'user_type' => 'it_professional',
                'level' => 'easy',
                'stage' => 1,
                'difficulty' => 'beginner',
                'estimated_minutes' => 3,
                'content' => json_encode([
                    'scenario' => 'IT team uses one shared admin account. Nobody knows who made critical changes.',
                    'question' => 'Why is shared admin dangerous?',
                    'options' => [
                        ['text' => 'Slower work', 'correct' => false],
                        ['text' => 'No accountability', 'correct' => true],
                        ['text' => 'Too many passwords', 'correct' => false],
                        ['text' => 'Higher cost', 'correct' => false],
                    ],
                    'explanation' => 'Each admin needs unique account for accountability.',
                ]),
            ],
            [
                'title' => 'The Open RDP Port',
                'description' => 'Remote Desktop exposed to internet',
                'category' => 'it_security',
                'user_type' => 'it_professional',
                'level' => 'easy',
                'stage' => 1,
                'difficulty' => 'beginner',
                'estimated_minutes' => 3,
                'content' => json_encode([
                    'scenario' => 'Khalid opens RDP port 3389 directly to public IP. Brute force within days.',
                    'question' => 'What should he use?',
                    'options' => [
                        ['text' => 'Stronger password', 'correct' => false],
                        ['text' => 'VPN', 'correct' => true],
                        ['text' => 'Different port', 'correct' => false],
                        ['text' => 'TeamViewer', 'correct' => false],
                    ],
                    'explanation' => 'Never expose RDP directly. Use VPN.',
                ]),
            ],
            [
                'title' => 'The Disabled Antivirus',
                'description' => 'Security software turned off and forgotten',
                'category' => 'it_security',
                'user_type' => 'it_professional',
                'level' => 'easy',
                'stage' => 1,
                'difficulty' => 'beginner',
                'estimated_minutes' => 3,
                'content' => json_encode([
                    'scenario' => 'Fatima disables antivirus for troubleshooting. Forgets to re-enable. Malware installs.',
                    'question' => 'What was the error?',
                    'options' => [
                        ['text' => 'Troubleshooting', 'correct' => false],
                        ['text' => 'Forgetting to re-enable security', 'correct' => true],
                        ['text' => 'Using email on server', 'correct' => false],
                        ['text' => 'Not checking logs', 'correct' => false],
                    ],
                    'explanation' => 'Never leave security software disabled.',
                ]),
            ],
            [
                'title' => 'The Cloud Storage Bucket',
                'description' => 'S3 bucket left public',
                'category' => 'it_security',
                'user_type' => 'it_professional',
                'level' => 'easy',
                'stage' => 1,
                'difficulty' => 'beginner',
                'estimated_minutes' => 3,
                'content' => json_encode([
                    'scenario' => 'Nora deploys S3 bucket with default settings. Customer data exposed publicly.',
                    'question' => 'What should she have done?',
                    'options' => [
                        ['text' => 'Deploy quickly', 'correct' => false],
                        ['text' => 'Configure security settings', 'correct' => true],
                        ['text' => 'Use different provider', 'correct' => false],
                        ['text' => 'Encrypt files', 'correct' => false],
                    ],
                    'explanation' => 'Cloud storage must have proper access controls.',
                ]),
            ],
            [
                'title' => 'The Telnet Connection',
                'description' => 'Unencrypted protocol for device management',
                'category' => 'it_security',
                'user_type' => 'it_professional',
                'level' => 'easy',
                'stage' => 1,
                'difficulty' => 'beginner',
                'estimated_minutes' => 3,
                'content' => json_encode([
                    'scenario' => 'Mohammed uses Telnet for router management. Password captured by packet sniffer.',
                    'question' => 'What should he use?',
                    'options' => [
                        ['text' => 'Faster Telnet', 'correct' => false],
                        ['text' => 'SSH', 'correct' => true],
                        ['text' => 'Stronger passwords', 'correct' => false],
                        ['text' => 'Different cable', 'correct' => false],
                    ],
                    'explanation' => 'Use SSH for encrypted device management.',
                ]),
            ],
            [
                'title' => 'The Log Files Exposure',
                'description' => 'Sensitive logs in public folder',
                'category' => 'it_security',
                'user_type' => 'it_professional',
                'level' => 'easy',
                'stage' => 1,
                'difficulty' => 'beginner',
                'estimated_minutes' => 3,
                'content' => json_encode([
                    'scenario' => 'Rami stores logs in shared folder. Employee finds credentials and steals data.',
                    'question' => 'What was the issue?',
                    'options' => [
                        ['text' => 'Logs too large', 'correct' => false],
                        ['text' => 'Logs in public location', 'correct' => true],
                        ['text' => 'Logs encrypted', 'correct' => false],
                        ['text' => 'Logs too old', 'correct' => false],
                    ],
                    'explanation' => 'Sensitive logs must be in restricted locations.',
                ]),
            ],
            [
                'title' => 'The Guest WiFi',
                'description' => 'Using guest network for work',
                'category' => 'it_security',
                'user_type' => 'it_professional',
                'level' => 'easy',
                'stage' => 1,
                'difficulty' => 'beginner',
                'estimated_minutes' => 3,
                'content' => json_encode([
                    'scenario' => 'Sara uses guest WiFi for work. Data intercepted by attacker.',
                    'question' => 'What should she use?',
                    'options' => [
                        ['text' => 'Guest WiFi', 'correct' => false],
                        ['text' => 'Secure internal network', 'correct' => true],
                        ['text' => 'Mobile data', 'correct' => false],
                        ['text' => 'Bluetooth', 'correct' => false],
                    ],
                    'explanation' => 'Use secure internal network for work.',
                ]),
            ],
            [
                'title' => 'The Unpatched Server',
                'description' => 'Critical updates postponed',
                'category' => 'it_security',
                'user_type' => 'it_professional',
                'level' => 'easy',
                'stage' => 1,
                'difficulty' => 'beginner',
                'estimated_minutes' => 3,
                'content' => json_encode([
                    'scenario' => 'Omar postpones security updates for months. Vulnerability exploited. Backdoor installed.',
                    'question' => 'What was the mistake?',
                    'options' => [
                        ['text' => 'Too many servers', 'correct' => false],
                        ['text' => 'Postponing critical updates', 'correct' => true],
                        ['text' => 'No backups', 'correct' => false],
                        ['text' => 'Using web server', 'correct' => false],
                    ],
                    'explanation' => 'Apply security updates promptly.',
                ]),
            ],

            // ============ SECURITY EXPERT ============
            [
                'title' => 'The SSRF Metadata Attack',
                'description' => 'Server-side request forgery to cloud metadata',
                'category' => 'appsec',
                'user_type' => 'security_expert',
                'level' => 'easy',
                'stage' => 1,
                'difficulty' => 'beginner',
                'estimated_minutes' => 5,
                'content' => json_encode([
                    'scenario' => 'Researcher finds SSRF vulnerability. Crafts request to AWS metadata service. Gets IAM credentials.',
                    'question' => 'What vulnerability?',
                    'options' => [
                        ['text' => 'SQL Injection', 'correct' => false],
                        ['text' => 'SSRF to metadata service', 'correct' => true],
                        ['text' => 'XSS', 'correct' => false],
                        ['text' => 'Buffer overflow', 'correct' => false],
                    ],
                    'explanation' => 'Block access to 169.254.169.254 from web apps.',
                ]),
            ],
            [
                'title' => 'The Dependency Confusion',
                'description' => 'Malicious package in build pipeline',
                'category' => 'appsec',
                'user_type' => 'security_expert',
                'level' => 'easy',
                'stage' => 1,
                'difficulty' => 'beginner',
                'estimated_minutes' => 5,
                'content' => json_encode([
                    'scenario' => 'CI/CD checks public registry first. Attacker uploads malicious package with same name.',
                    'question' => 'How to prevent?',
                    'options' => [
                        ['text' => 'Use only public', 'correct' => false],
                        ['text' => 'Private registry priority', 'correct' => true],
                        ['text' => 'Disable dependencies', 'correct' => false],
                        ['text' => 'Faster servers', 'correct' => false],
                    ],
                    'explanation' => 'Configure private registry priority and pin versions.',
                ]),
            ],
            [
                'title' => 'The Terraform State Exposure',
                'description' => 'Infrastructure secrets in unencrypted state',
                'category' => 'appsec',
                'user_type' => 'security_expert',
                'level' => 'easy',
                'stage' => 1,
                'difficulty' => 'beginner',
                'estimated_minutes' => 5,
                'content' => json_encode([
                    'scenario' => 'Terraform state files stored unencrypted in S3. Passwords and keys exposed.',
                    'question' => 'What should be done?',
                    'options' => [
                        ['text' => 'Store locally', 'correct' => false],
                        ['text' => 'Encrypt state files', 'correct' => true],
                        ['text' => 'Delete after use', 'correct' => false],
                        ['text' => 'Share with all', 'correct' => false],
                    ],
                    'explanation' => 'Encrypt Terraform state files at rest.',
                ]),
            ],
            [
                'title' => 'The IAM AssumeRole',
                'description' => 'Trust policy too permissive',
                'category' => 'appsec',
                'user_type' => 'security_expert',
                'level' => 'easy',
                'stage' => 1,
                'difficulty' => 'beginner',
                'estimated_minutes' => 5,
                'content' => json_encode([
                    'scenario' => 'IAM role trust policy allows any AWS account. Attacker assumes role and exfiltrates.',
                    'question' => 'What was misconfigured?',
                    'options' => [
                        ['text' => 'Role name short', 'correct' => false],
                        ['text' => 'Trust policy too broad', 'correct' => true],
                        ['text' => 'No password', 'correct' => false],
                        ['text' => 'Complex permissions', 'correct' => false],
                    ],
                    'explanation' => 'Restrict trust policies to specific accounts.',
                ]),
            ],
            [
                'title' => 'The Kubernetes ServiceAccount',
                'description' => 'Container escape via over-privileged token',
                'category' => 'appsec',
                'user_type' => 'security_expert',
                'level' => 'easy',
                'stage' => 1,
                'difficulty' => 'beginner',
                'estimated_minutes' => 5,
                'content' => json_encode([
                    'scenario' => 'Attacker exploits web app in pod. ServiceAccount has cluster-admin. Creates privileged pod.',
                    'question' => 'What principle violated?',
                    'options' => [
                        ['text' => 'Using containers', 'correct' => false],
                        ['text' => 'Least privilege', 'correct' => true],
                        ['text' => 'Large cluster', 'correct' => false],
                        ['text' => 'Small pods', 'correct' => false],
                    ],
                    'explanation' => 'ServiceAccounts must follow least privilege.',
                ]),
            ],
            [
                'title' => 'The Log Tampering',
                'description' => 'SIEM blind spot through log injection',
                'category' => 'appsec',
                'user_type' => 'security_expert',
                'level' => 'easy',
                'stage' => 1,
                'difficulty' => 'beginner',
                'estimated_minutes' => 5,
                'content' => json_encode([
                    'scenario' => 'Attacker floods logs with fake entries. Real attack hidden in noise.',
                    'question' => 'What technique?',
                    'options' => [
                        ['text' => 'SQL Injection', 'correct' => false],
                        ['text' => 'Log flooding', 'correct' => true],
                        ['text' => 'XSS', 'correct' => false],
                        ['text' => 'Phishing', 'correct' => false],
                    ],
                    'explanation' => 'Implement anomaly detection for log flooding.',
                ]),
            ],
            [
                'title' => 'The Kerberoasting',
                'description' => 'Service account password cracking',
                'category' => 'appsec',
                'user_type' => 'security_expert',
                'level' => 'easy',
                'stage' => 1,
                'difficulty' => 'beginner',
                'estimated_minutes' => 5,
                'content' => json_encode([
                    'scenario' => 'Researcher performs Kerberoasting. Weak service account password cracked. Domain Admin.',
                    'question' => 'What made it possible?',
                    'options' => [
                        ['text' => 'Old domain', 'correct' => false],
                        ['text' => 'Weak encryption + passwords', 'correct' => true],
                        ['text' => 'Slow network', 'correct' => false],
                        ['text' => 'Too many users', 'correct' => false],
                    ],
                    'explanation' => 'Use AES encryption and strong service account passwords.',
                ]),
            ],
            [
                'title' => 'The Golden Ticket',
                'description' => 'Domain persistence through KRBTGT hash',
                'category' => 'appsec',
                'user_type' => 'security_expert',
                'level' => 'easy',
                'stage' => 1,
                'difficulty' => 'beginner',
                'estimated_minutes' => 5,
                'content' => json_encode([
                    'scenario' => 'Attacker extracts KRBTGT hash. Forges Golden Tickets. Access persists after password resets.',
                    'question' => 'Why dangerous?',
                    'options' => [
                        ['text' => 'Very fast', 'correct' => false],
                        ['text' => 'Persistent access surviving resets', 'correct' => true],
                        ['text' => 'Targets one user', 'correct' => false],
                        ['text' => 'Needs physical access', 'correct' => false],
                    ],
                    'explanation' => 'Reset KRBTGT hash twice to invalidate Golden Tickets.',
                ]),
            ],
            [
                'title' => 'The AD CS ESC1',
                'description' => 'Certificate template allowing SAN',
                'category' => 'appsec',
                'user_type' => 'security_expert',
                'level' => 'easy',
                'stage' => 1,
                'difficulty' => 'beginner',
                'estimated_minutes' => 5,
                'content' => json_encode([
                    'scenario' => 'Certificate template allows user-supplied SAN. Attacker gets Domain Admin certificate.',
                    'question' => 'What vulnerability?',
                    'options' => [
                        ['text' => 'Weak passwords', 'correct' => false],
                        ['text' => 'Template allowing user SAN', 'correct' => true],
                        ['text' => 'Old OS', 'correct' => false],
                        ['text' => 'Firewall issue', 'correct' => false],
                    ],
                    'explanation' => 'Review AD CS templates for SAN permissions.',
                ]),
            ],
            [
                'title' => 'The BOLA API',
                'description' => 'Broken Object Level Authorization',
                'category' => 'appsec',
                'user_type' => 'security_expert',
                'level' => 'easy',
                'stage' => 1,
                'difficulty' => 'beginner',
                'estimated_minutes' => 5,
                'content' => json_encode([
                    'scenario' => 'Researcher changes user ID in URL. Accesses other users data.',
                    'question' => 'What vulnerability?',
                    'options' => [
                        ['text' => 'SQL Injection', 'correct' => false],
                        ['text' => 'BOLA - missing access control', 'correct' => true],
                        ['text' => 'XSS', 'correct' => false],
                        ['text' => 'CSRF', 'correct' => false],
                    ],
                    'explanation' => 'Verify user permission for each object.',
                ]),
            ],
            [
                'title' => 'The NoSQL Injection',
                'description' => 'Bypassing auth via NoSQL operators',
                'category' => 'appsec',
                'user_type' => 'security_expert',
                'level' => 'easy',
                'stage' => 1,
                'difficulty' => 'beginner',
                'estimated_minutes' => 5,
                'content' => json_encode([
                    'scenario' => 'Researcher sends {"username":{"$ne":""},"password":{"$ne":""}}. Bypasses auth.',
                    'question' => 'What injection?',
                    'options' => [
                        ['text' => 'SQL Injection', 'correct' => false],
                        ['text' => 'NoSQL Injection', 'correct' => true],
                        ['text' => 'Command Injection', 'correct' => false],
                        ['text' => 'LDAP Injection', 'correct' => false],
                    ],
                    'explanation' => 'Sanitize all inputs in NoSQL queries.',
                ]),
            ],
            [
                'title' => 'The SSTI',
                'description' => 'Template injection to RCE',
                'category' => 'appsec',
                'user_type' => 'security_expert',
                'level' => 'easy',
                'stage' => 1,
                'difficulty' => 'beginner',
                'estimated_minutes' => 5,
                'content' => json_encode([
                    'scenario' => 'Researcher injects {{7*7}} and sees 49. Escalates to RCE.',
                    'question' => 'What vulnerability?',
                    'options' => [
                        ['text' => 'SQL Injection', 'correct' => false],
                        ['text' => 'SSTI - Server-Side Template Injection', 'correct' => true],
                        ['text' => 'XSS', 'correct' => false],
                        ['text' => 'CSRF', 'correct' => false],
                    ],
                    'explanation' => 'Never pass user input to template engines.',
                ]),
            ],
            [
                'title' => 'The Padding Oracle',
                'description' => 'Decrypting via error messages',
                'category' => 'appsec',
                'user_type' => 'security_expert',
                'level' => 'easy',
                'stage' => 1,
                'difficulty' => 'beginner',
                'estimated_minutes' => 5,
                'content' => json_encode([
                    'scenario' => 'Different errors for padding vs other. Researcher decrypts cookies byte by byte.',
                    'question' => 'What made it possible?',
                    'options' => [
                        ['text' => 'Strong encryption', 'correct' => false],
                        ['text' => 'Different error responses', 'correct' => true],
                        ['text' => 'Fast server', 'correct' => false],
                        ['text' => 'Large cookies', 'correct' => false],
                    ],
                    'explanation' => 'Use uniform error responses.',
                ]),
            ],
            [
                'title' => 'The Process Injection',
                'description' => 'Malware hiding in legitimate processes',
                'category' => 'appsec',
                'user_type' => 'security_expert',
                'level' => 'easy',
                'stage' => 1,
                'difficulty' => 'beginner',
                'estimated_minutes' => 5,
                'content' => json_encode([
                    'scenario' => 'Malware injects code into explorer.exe. No files on disk. Hard to detect.',
                    'question' => 'Why difficult?',
                    'options' => [
                        ['text' => 'Encrypted', 'correct' => false],
                        ['text' => 'Runs in legitimate process', 'correct' => true],
                        ['text' => 'Too small', 'correct' => false],
                        ['text' => 'Old system', 'correct' => false],
                    ],
                    'explanation' => 'Use memory forensics and EDR.',
                ]),
            ],
            [
                'title' => 'The DNS Exfiltration',
                'description' => 'Data hidden in DNS queries',
                'category' => 'appsec',
                'user_type' => 'security_expert',
                'level' => 'easy',
                'stage' => 1,
                'difficulty' => 'beginner',
                'estimated_minutes' => 5,
                'content' => json_encode([
                    'scenario' => 'Data split into chunks and encoded in DNS queries to attacker domain.',
                    'question' => 'What technique?',
                    'options' => [
                        ['text' => 'HTTP tunnel', 'correct' => false],
                        ['text' => 'DNS tunneling', 'correct' => true],
                        ['text' => 'ICMP tunnel', 'correct' => false],
                        ['text' => 'SMTP exfil', 'correct' => false],
                    ],
                    'explanation' => 'Monitor DNS traffic for anomalies.',
                ]),
            ],
        ];

        foreach ($scenarios as $scenario) {
            $scenario['uuid'] = (string) Str::uuid();
            $scenario['is_active'] = true;
            $scenario['version'] = 1;
            DB::table('scenarios')->insert($scenario);
            echo "Added: " . $scenario['title'] . "\n";
        }

        echo "\nTotal: " . count($scenarios) . " scenarios\n";
    }
}